// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tzero/v1/payment_intent/pay_in_provider.proto

package payment_intent

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	ivms "github.com/t-0-network/provider-sdk-go/api/ivms101/v1/ivms"
	common "github.com/t-0-network/provider-sdk-go/api/tzero/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Request for payment details.
type GetPaymentDetailsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The payment intent ID this request relates to.
	// Can be used for logging, reference tracking, or payment reconciliation.
	PaymentIntentId uint64 `protobuf:"varint,10,opt,name=payment_intent_id,json=paymentIntentId,proto3" json:"payment_intent_id,omitempty"`
	// *
	// Payment methods being requested.
	// The provider should return PaymentDetails for each method they support.
	// Methods the provider doesn't support can be omitted from the response.
	PaymentMethods []common.PaymentMethodType `protobuf:"varint,20,rep,packed,name=payment_methods,json=paymentMethods,proto3,enum=tzero.v1.common.PaymentMethodType" json:"payment_methods,omitempty"`
	// *
	// The currency for the pay-in.
	// ISO 4217 currency code (e.g., "EUR", "GBP", "KES").
	Currency string `protobuf:"bytes,30,opt,name=currency,proto3" json:"currency,omitempty"`
	// *
	// The amount to be paid in the specified currency.
	// Payment details should be suitable for receiving this amount.
	Amount *common.Decimal `protobuf:"bytes,40,opt,name=amount,proto3" json:"amount,omitempty"`
	// *
	// Travel rule data for this payment
	TravelRule    *GetPaymentDetailsRequest_TravelRuleData `protobuf:"bytes,50,opt,name=travel_rule,json=travelRule,proto3" json:"travel_rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentDetailsRequest) Reset() {
	*x = GetPaymentDetailsRequest{}
	mi := &file_tzero_v1_payment_intent_pay_in_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentDetailsRequest) ProtoMessage() {}

func (x *GetPaymentDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_intent_pay_in_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentDetailsRequest) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_intent_pay_in_provider_proto_rawDescGZIP(), []int{0}
}

func (x *GetPaymentDetailsRequest) GetPaymentIntentId() uint64 {
	if x != nil {
		return x.PaymentIntentId
	}
	return 0
}

func (x *GetPaymentDetailsRequest) GetPaymentMethods() []common.PaymentMethodType {
	if x != nil {
		return x.PaymentMethods
	}
	return nil
}

func (x *GetPaymentDetailsRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetPaymentDetailsRequest) GetAmount() *common.Decimal {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *GetPaymentDetailsRequest) GetTravelRule() *GetPaymentDetailsRequest_TravelRuleData {
	if x != nil {
		return x.TravelRule
	}
	return nil
}

// *
// Response containing payment details for the requested methods.
type GetPaymentDetailsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Payment details for each supported payment method.
	// May contain fewer items than requested if the provider doesn't support
	// some of the requested payment methods.
	//
	// Each PaymentDetails contains the information needed for an end-user
	// to send a payment (e.g., bank account details, mobile money number).
	PaymentDetails []*common.PaymentDetails `protobuf:"bytes,10,rep,name=payment_details,json=paymentDetails,proto3" json:"payment_details,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPaymentDetailsResponse) Reset() {
	*x = GetPaymentDetailsResponse{}
	mi := &file_tzero_v1_payment_intent_pay_in_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentDetailsResponse) ProtoMessage() {}

func (x *GetPaymentDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_intent_pay_in_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentDetailsResponse) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_intent_pay_in_provider_proto_rawDescGZIP(), []int{1}
}

func (x *GetPaymentDetailsResponse) GetPaymentDetails() []*common.PaymentDetails {
	if x != nil {
		return x.PaymentDetails
	}
	return nil
}

type GetPaymentDetailsRequest_TravelRuleData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The natural or legal person or legal arrangement who is identified
	// by the beneficiary provider as the receiver of the requested payment.
	Beneficiary []*ivms.Person `protobuf:"bytes,20,rep,name=beneficiary,proto3" json:"beneficiary,omitempty"`
	// *
	// Beneficiary provider travel rule data.
	BeneficiaryProvider *ivms.LegalPerson `protobuf:"bytes,30,opt,name=beneficiary_provider,json=beneficiaryProvider,proto3" json:"beneficiary_provider,omitempty"`
	// *
	// Optional travel rule data of the payer
	Payer         *ivms.Person `protobuf:"bytes,40,opt,name=payer,proto3,oneof" json:"payer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentDetailsRequest_TravelRuleData) Reset() {
	*x = GetPaymentDetailsRequest_TravelRuleData{}
	mi := &file_tzero_v1_payment_intent_pay_in_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentDetailsRequest_TravelRuleData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentDetailsRequest_TravelRuleData) ProtoMessage() {}

func (x *GetPaymentDetailsRequest_TravelRuleData) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_intent_pay_in_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentDetailsRequest_TravelRuleData.ProtoReflect.Descriptor instead.
func (*GetPaymentDetailsRequest_TravelRuleData) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_intent_pay_in_provider_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetPaymentDetailsRequest_TravelRuleData) GetBeneficiary() []*ivms.Person {
	if x != nil {
		return x.Beneficiary
	}
	return nil
}

func (x *GetPaymentDetailsRequest_TravelRuleData) GetBeneficiaryProvider() *ivms.LegalPerson {
	if x != nil {
		return x.BeneficiaryProvider
	}
	return nil
}

func (x *GetPaymentDetailsRequest_TravelRuleData) GetPayer() *ivms.Person {
	if x != nil {
		return x.Payer
	}
	return nil
}

var File_tzero_v1_payment_intent_pay_in_provider_proto protoreflect.FileDescriptor

const file_tzero_v1_payment_intent_pay_in_provider_proto_rawDesc = "" +
	"\n" +
	"-tzero/v1/payment_intent/pay_in_provider.proto\x12\x17tzero.v1.payment_intent\x1a\x1ctzero/v1/common/common.proto\x1a$tzero/v1/common/payment_method.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1divms101/v1/ivms/ivms101.proto\"\xd4\x04\n" +
	"\x18GetPaymentDetailsRequest\x123\n" +
	"\x11payment_intent_id\x18\n" +
	" \x01(\x04B\a\xbaH\x042\x02 \x00R\x0fpaymentIntentId\x12U\n" +
	"\x0fpayment_methods\x18\x14 \x03(\x0e2\".tzero.v1.common.PaymentMethodTypeB\b\xbaH\x05\x92\x01\x02\b\x01R\x0epaymentMethods\x120\n" +
	"\bcurrency\x18\x1e \x01(\tB\x14\xbaH\x11r\x0f2\n" +
	"^[A-Z]{3}$\x98\x01\x03R\bcurrency\x128\n" +
	"\x06amount\x18( \x01(\v2\x18.tzero.v1.common.DecimalB\x06\xbaH\x03\xc8\x01\x01R\x06amount\x12i\n" +
	"\vtravel_rule\x182 \x01(\v2@.tzero.v1.payment_intent.GetPaymentDetailsRequest.TravelRuleDataB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"travelRule\x1a\xd4\x01\n" +
	"\x0eTravelRuleData\x12;\n" +
	"\vbeneficiary\x18\x14 \x03(\v2\x0f.ivms101.PersonB\b\xbaH\x05\x92\x01\x02\b\x01R\vbeneficiary\x12O\n" +
	"\x14beneficiary_provider\x18\x1e \x01(\v2\x14.ivms101.LegalPersonB\x06\xbaH\x03\xc8\x01\x01R\x13beneficiaryProvider\x12*\n" +
	"\x05payer\x18( \x01(\v2\x0f.ivms101.PersonH\x00R\x05payer\x88\x01\x01B\b\n" +
	"\x06_payer\"e\n" +
	"\x19GetPaymentDetailsResponse\x12H\n" +
	"\x0fpayment_details\x18\n" +
	" \x03(\v2\x1f.tzero.v1.common.PaymentDetailsR\x0epaymentDetails2\x97\x01\n" +
	"\x14PayInProviderService\x12\x7f\n" +
	"\x11GetPaymentDetails\x121.tzero.v1.payment_intent.GetPaymentDetailsRequest\x1a2.tzero.v1.payment_intent.GetPaymentDetailsResponse\"\x03\x90\x02\x02B\xef\x01\n" +
	"\x1bcom.tzero.v1.payment_intentB\x12PayInProviderProtoP\x01ZBgithub.com/t-0-network/provider-sdk-go/api/tzero/v1/payment_intent\xa2\x02\x03TVP\xaa\x02\x16Tzero.V1.PaymentIntent\xca\x02\x16Tzero\\V1\\PaymentIntent\xe2\x02\"Tzero\\V1\\PaymentIntent\\GPBMetadata\xea\x02\x18Tzero::V1::PaymentIntentb\x06proto3"

var (
	file_tzero_v1_payment_intent_pay_in_provider_proto_rawDescOnce sync.Once
	file_tzero_v1_payment_intent_pay_in_provider_proto_rawDescData []byte
)

func file_tzero_v1_payment_intent_pay_in_provider_proto_rawDescGZIP() []byte {
	file_tzero_v1_payment_intent_pay_in_provider_proto_rawDescOnce.Do(func() {
		file_tzero_v1_payment_intent_pay_in_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tzero_v1_payment_intent_pay_in_provider_proto_rawDesc), len(file_tzero_v1_payment_intent_pay_in_provider_proto_rawDesc)))
	})
	return file_tzero_v1_payment_intent_pay_in_provider_proto_rawDescData
}

var file_tzero_v1_payment_intent_pay_in_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tzero_v1_payment_intent_pay_in_provider_proto_goTypes = []any{
	(*GetPaymentDetailsRequest)(nil),                // 0: tzero.v1.payment_intent.GetPaymentDetailsRequest
	(*GetPaymentDetailsResponse)(nil),               // 1: tzero.v1.payment_intent.GetPaymentDetailsResponse
	(*GetPaymentDetailsRequest_TravelRuleData)(nil), // 2: tzero.v1.payment_intent.GetPaymentDetailsRequest.TravelRuleData
	(common.PaymentMethodType)(0),                   // 3: tzero.v1.common.PaymentMethodType
	(*common.Decimal)(nil),                          // 4: tzero.v1.common.Decimal
	(*common.PaymentDetails)(nil),                   // 5: tzero.v1.common.PaymentDetails
	(*ivms.Person)(nil),                             // 6: ivms101.Person
	(*ivms.LegalPerson)(nil),                        // 7: ivms101.LegalPerson
}
var file_tzero_v1_payment_intent_pay_in_provider_proto_depIdxs = []int32{
	3, // 0: tzero.v1.payment_intent.GetPaymentDetailsRequest.payment_methods:type_name -> tzero.v1.common.PaymentMethodType
	4, // 1: tzero.v1.payment_intent.GetPaymentDetailsRequest.amount:type_name -> tzero.v1.common.Decimal
	2, // 2: tzero.v1.payment_intent.GetPaymentDetailsRequest.travel_rule:type_name -> tzero.v1.payment_intent.GetPaymentDetailsRequest.TravelRuleData
	5, // 3: tzero.v1.payment_intent.GetPaymentDetailsResponse.payment_details:type_name -> tzero.v1.common.PaymentDetails
	6, // 4: tzero.v1.payment_intent.GetPaymentDetailsRequest.TravelRuleData.beneficiary:type_name -> ivms101.Person
	7, // 5: tzero.v1.payment_intent.GetPaymentDetailsRequest.TravelRuleData.beneficiary_provider:type_name -> ivms101.LegalPerson
	6, // 6: tzero.v1.payment_intent.GetPaymentDetailsRequest.TravelRuleData.payer:type_name -> ivms101.Person
	0, // 7: tzero.v1.payment_intent.PayInProviderService.GetPaymentDetails:input_type -> tzero.v1.payment_intent.GetPaymentDetailsRequest
	1, // 8: tzero.v1.payment_intent.PayInProviderService.GetPaymentDetails:output_type -> tzero.v1.payment_intent.GetPaymentDetailsResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_tzero_v1_payment_intent_pay_in_provider_proto_init() }
func file_tzero_v1_payment_intent_pay_in_provider_proto_init() {
	if File_tzero_v1_payment_intent_pay_in_provider_proto != nil {
		return
	}
	file_tzero_v1_payment_intent_pay_in_provider_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tzero_v1_payment_intent_pay_in_provider_proto_rawDesc), len(file_tzero_v1_payment_intent_pay_in_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tzero_v1_payment_intent_pay_in_provider_proto_goTypes,
		DependencyIndexes: file_tzero_v1_payment_intent_pay_in_provider_proto_depIdxs,
		MessageInfos:      file_tzero_v1_payment_intent_pay_in_provider_proto_msgTypes,
	}.Build()
	File_tzero_v1_payment_intent_pay_in_provider_proto = out.File
	file_tzero_v1_payment_intent_pay_in_provider_proto_goTypes = nil
	file_tzero_v1_payment_intent_pay_in_provider_proto_depIdxs = nil
}
