// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tzero/v1/payment/network.proto

package payment

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	ivms "github.com/t-0-network/provider-sdk-go/api/ivms101/v1/ivms"
	common "github.com/t-0-network/provider-sdk-go/api/tzero/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuoteType int32

const (
	QuoteType_QUOTE_TYPE_UNSPECIFIED QuoteType = 0
	QuoteType_QUOTE_TYPE_REALTIME    QuoteType = 1 // real-time quote must be valid at least for 30 seconds (TBD)
)

// Enum value maps for QuoteType.
var (
	QuoteType_name = map[int32]string{
		0: "QUOTE_TYPE_UNSPECIFIED",
		1: "QUOTE_TYPE_REALTIME",
	}
	QuoteType_value = map[string]int32{
		"QUOTE_TYPE_UNSPECIFIED": 0,
		"QUOTE_TYPE_REALTIME":    1,
	}
)

func (x QuoteType) Enum() *QuoteType {
	p := new(QuoteType)
	*p = x
	return p
}

func (x QuoteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuoteType) Descriptor() protoreflect.EnumDescriptor {
	return file_tzero_v1_payment_network_proto_enumTypes[0].Descriptor()
}

func (QuoteType) Type() protoreflect.EnumType {
	return &file_tzero_v1_payment_network_proto_enumTypes[0]
}

func (x QuoteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuoteType.Descriptor instead.
func (QuoteType) EnumDescriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{0}
}

type GetQuoteResponse_Failure_Reason int32

const (
	GetQuoteResponse_Failure_REASON_UNSPECIFIED     GetQuoteResponse_Failure_Reason = 0
	GetQuoteResponse_Failure_REASON_QUOTE_NOT_FOUND GetQuoteResponse_Failure_Reason = 10 // No matching quote par for the specified payout currency found or provider limits would exceed by processing this payment
)

// Enum value maps for GetQuoteResponse_Failure_Reason.
var (
	GetQuoteResponse_Failure_Reason_name = map[int32]string{
		0:  "REASON_UNSPECIFIED",
		10: "REASON_QUOTE_NOT_FOUND",
	}
	GetQuoteResponse_Failure_Reason_value = map[string]int32{
		"REASON_UNSPECIFIED":     0,
		"REASON_QUOTE_NOT_FOUND": 10,
	}
)

func (x GetQuoteResponse_Failure_Reason) Enum() *GetQuoteResponse_Failure_Reason {
	p := new(GetQuoteResponse_Failure_Reason)
	*p = x
	return p
}

func (x GetQuoteResponse_Failure_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetQuoteResponse_Failure_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_tzero_v1_payment_network_proto_enumTypes[1].Descriptor()
}

func (GetQuoteResponse_Failure_Reason) Type() protoreflect.EnumType {
	return &file_tzero_v1_payment_network_proto_enumTypes[1]
}

func (x GetQuoteResponse_Failure_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetQuoteResponse_Failure_Reason.Descriptor instead.
func (GetQuoteResponse_Failure_Reason) EnumDescriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{3, 1, 0}
}

type CreatePaymentResponse_Failure_Reason int32

const (
	CreatePaymentResponse_Failure_REASON_UNSPECIFIED                   CreatePaymentResponse_Failure_Reason = 0
	CreatePaymentResponse_Failure_REASON_QUOTE_NOT_FOUND               CreatePaymentResponse_Failure_Reason = 10 // No matching quote for the specified payout currency found or provider limits would exceed by processing this payment
	CreatePaymentResponse_Failure_REASON_CREDIT_OR_PREDEPOSIT_REQUIRED CreatePaymentResponse_Failure_Reason = 20 // Payments with amount in pay out currency require available credit or pre-deposit
)

// Enum value maps for CreatePaymentResponse_Failure_Reason.
var (
	CreatePaymentResponse_Failure_Reason_name = map[int32]string{
		0:  "REASON_UNSPECIFIED",
		10: "REASON_QUOTE_NOT_FOUND",
		20: "REASON_CREDIT_OR_PREDEPOSIT_REQUIRED",
	}
	CreatePaymentResponse_Failure_Reason_value = map[string]int32{
		"REASON_UNSPECIFIED":                   0,
		"REASON_QUOTE_NOT_FOUND":               10,
		"REASON_CREDIT_OR_PREDEPOSIT_REQUIRED": 20,
	}
)

func (x CreatePaymentResponse_Failure_Reason) Enum() *CreatePaymentResponse_Failure_Reason {
	p := new(CreatePaymentResponse_Failure_Reason)
	*p = x
	return p
}

func (x CreatePaymentResponse_Failure_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreatePaymentResponse_Failure_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_tzero_v1_payment_network_proto_enumTypes[2].Descriptor()
}

func (CreatePaymentResponse_Failure_Reason) Type() protoreflect.EnumType {
	return &file_tzero_v1_payment_network_proto_enumTypes[2]
}

func (x CreatePaymentResponse_Failure_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreatePaymentResponse_Failure_Reason.Descriptor instead.
func (CreatePaymentResponse_Failure_Reason) EnumDescriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{6, 2, 0}
}

// Base currency is always USD, so the quotes are always in USD/currency format.
type UpdateQuoteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Zero or more quotes for pay-out operations, each quote must have a unique currency, and one or more bands, with the
	// unique client_quote_id for each band.
	PayOut []*UpdateQuoteRequest_Quote `protobuf:"bytes,10,rep,name=pay_out,json=payOut,proto3" json:"pay_out,omitempty"`
	// *
	// Zero or more quotes for pay-in operations, each quote must have a unique currency, and one or more bands, with the
	// unique client_quote_id for each band.
	PayIn         []*UpdateQuoteRequest_Quote `protobuf:"bytes,20,rep,name=pay_in,json=payIn,proto3" json:"pay_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuoteRequest) Reset() {
	*x = UpdateQuoteRequest{}
	mi := &file_tzero_v1_payment_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuoteRequest) ProtoMessage() {}

func (x *UpdateQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuoteRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuoteRequest) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateQuoteRequest) GetPayOut() []*UpdateQuoteRequest_Quote {
	if x != nil {
		return x.PayOut
	}
	return nil
}

func (x *UpdateQuoteRequest) GetPayIn() []*UpdateQuoteRequest_Quote {
	if x != nil {
		return x.PayIn
	}
	return nil
}

type UpdateQuoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuoteResponse) Reset() {
	*x = UpdateQuoteResponse{}
	mi := &file_tzero_v1_payment_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuoteResponse) ProtoMessage() {}

func (x *UpdateQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuoteResponse.ProtoReflect.Descriptor instead.
func (*UpdateQuoteResponse) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{1}
}

type GetQuoteRequest struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	Amount         *PaymentAmount           `protobuf:"bytes,20,opt,name=amount,proto3" json:"amount,omitempty"`                                                                           // payment amount - must be either pay-out amount or settlement amount
	PayOutCurrency string                   `protobuf:"bytes,40,opt,name=pay_out_currency,json=payOutCurrency,proto3" json:"pay_out_currency,omitempty"`                                   // ISO 4217 currency code, e.g. EUR, GBP, etc. in which the payout should be made
	PayOutMethod   common.PaymentMethodType `protobuf:"varint,50,opt,name=pay_out_method,json=payOutMethod,proto3,enum=tzero.v1.common.PaymentMethodType" json:"pay_out_method,omitempty"` // payment method to use for the payout, e.g. bank transfer, card, etc.
	QuoteType      QuoteType                `protobuf:"varint,60,opt,name=quote_type,json=quoteType,proto3,enum=tzero.v1.payment.QuoteType" json:"quote_type,omitempty"`                   // type of the quote, e.g. real-time
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetQuoteRequest) Reset() {
	*x = GetQuoteRequest{}
	mi := &file_tzero_v1_payment_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteRequest) ProtoMessage() {}

func (x *GetQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteRequest.ProtoReflect.Descriptor instead.
func (*GetQuoteRequest) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{2}
}

func (x *GetQuoteRequest) GetAmount() *PaymentAmount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *GetQuoteRequest) GetPayOutCurrency() string {
	if x != nil {
		return x.PayOutCurrency
	}
	return ""
}

func (x *GetQuoteRequest) GetPayOutMethod() common.PaymentMethodType {
	if x != nil {
		return x.PayOutMethod
	}
	return common.PaymentMethodType(0)
}

func (x *GetQuoteRequest) GetQuoteType() QuoteType {
	if x != nil {
		return x.QuoteType
	}
	return QuoteType_QUOTE_TYPE_UNSPECIFIED
}

type GetQuoteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetQuoteResponse_Success_
	//	*GetQuoteResponse_Failure_
	Result        isGetQuoteResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuoteResponse) Reset() {
	*x = GetQuoteResponse{}
	mi := &file_tzero_v1_payment_network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteResponse) ProtoMessage() {}

func (x *GetQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteResponse.ProtoReflect.Descriptor instead.
func (*GetQuoteResponse) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{3}
}

func (x *GetQuoteResponse) GetResult() isGetQuoteResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetQuoteResponse) GetSuccess() *GetQuoteResponse_Success {
	if x != nil {
		if x, ok := x.Result.(*GetQuoteResponse_Success_); ok {
			return x.Success
		}
	}
	return nil
}

func (x *GetQuoteResponse) GetFailure() *GetQuoteResponse_Failure {
	if x != nil {
		if x, ok := x.Result.(*GetQuoteResponse_Failure_); ok {
			return x.Failure
		}
	}
	return nil
}

type isGetQuoteResponse_Result interface {
	isGetQuoteResponse_Result()
}

type GetQuoteResponse_Success_ struct {
	// *
	// Success response - the network found a suitable quote for the provided parameters and with available credit or pre-settlement option.
	// The returned quoteId can be used later to call the create payment endpoint.
	Success *GetQuoteResponse_Success `protobuf:"bytes,20,opt,name=success,proto3,oneof"`
}

type GetQuoteResponse_Failure_ struct {
	// *
	// Failure response - means the quote was not found for the specified parameters, or provider limits
	// would exceed by processing the payment amount with the specified amount.
	Failure *GetQuoteResponse_Failure `protobuf:"bytes,30,opt,name=failure,proto3,oneof"`
}

func (*GetQuoteResponse_Success_) isGetQuoteResponse_Result() {}

func (*GetQuoteResponse_Failure_) isGetQuoteResponse_Result() {}

type CreatePaymentRequest struct {
	state           protoimpl.MessageState               `protogen:"open.v1"`
	PaymentClientId string                               `protobuf:"bytes,10,opt,name=payment_client_id,json=paymentClientId,proto3" json:"payment_client_id,omitempty"`     // unique client generated id for this payment
	Amount          *PaymentAmount                       `protobuf:"bytes,30,opt,name=amount,proto3" json:"amount,omitempty"`                                                // payment amount - should be either pay-out amount or settlement amount
	Currency        string                               `protobuf:"bytes,40,opt,name=currency,proto3" json:"currency,omitempty"`                                            // pay-out currency
	PaymentDetails  *common.PaymentDetails               `protobuf:"bytes,50,opt,name=payment_details,json=paymentDetails,proto3" json:"payment_details,omitempty"`          // pay-out payment details
	QuoteId         *QuoteId                             `protobuf:"bytes,60,opt,name=quote_id,json=quoteId,proto3,oneof" json:"quote_id,omitempty"`                         // if specified, must be a valid quoteId that was previously returned by the GetPayoutQuote method otherwise last available quote will be used
	TravelRuleData  *CreatePaymentRequest_TravelRuleData `protobuf:"bytes,100,opt,name=travel_rule_data,json=travelRuleData,proto3,oneof" json:"travel_rule_data,omitempty"` // travel rule data
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_tzero_v1_payment_network_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_network_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePaymentRequest) GetPaymentClientId() string {
	if x != nil {
		return x.PaymentClientId
	}
	return ""
}

func (x *CreatePaymentRequest) GetAmount() *PaymentAmount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *CreatePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePaymentRequest) GetPaymentDetails() *common.PaymentDetails {
	if x != nil {
		return x.PaymentDetails
	}
	return nil
}

func (x *CreatePaymentRequest) GetQuoteId() *QuoteId {
	if x != nil {
		return x.QuoteId
	}
	return nil
}

func (x *CreatePaymentRequest) GetTravelRuleData() *CreatePaymentRequest_TravelRuleData {
	if x != nil {
		return x.TravelRuleData
	}
	return nil
}

type QuoteId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuoteId       int64                  `protobuf:"varint,30,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`          // unique identifier of the quote within the specified provider
	ProviderId    int32                  `protobuf:"varint,40,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"` // provider id of the quote
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteId) Reset() {
	*x = QuoteId{}
	mi := &file_tzero_v1_payment_network_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteId) ProtoMessage() {}

func (x *QuoteId) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_network_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteId.ProtoReflect.Descriptor instead.
func (*QuoteId) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{5}
}

func (x *QuoteId) GetQuoteId() int64 {
	if x != nil {
		return x.QuoteId
	}
	return 0
}

func (x *QuoteId) GetProviderId() int32 {
	if x != nil {
		return x.ProviderId
	}
	return 0
}

type CreatePaymentResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentClientId string                 `protobuf:"bytes,10,opt,name=payment_client_id,json=paymentClientId,proto3" json:"payment_client_id,omitempty"` // client generated id supplied in the request
	// Types that are valid to be assigned to Result:
	//
	//	*CreatePaymentResponse_Accepted_
	//	*CreatePaymentResponse_SettlementRequired_
	//	*CreatePaymentResponse_Failure_
	Result        isCreatePaymentResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_tzero_v1_payment_network_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_network_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePaymentResponse) GetPaymentClientId() string {
	if x != nil {
		return x.PaymentClientId
	}
	return ""
}

func (x *CreatePaymentResponse) GetResult() isCreatePaymentResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CreatePaymentResponse) GetAccepted() *CreatePaymentResponse_Accepted {
	if x != nil {
		if x, ok := x.Result.(*CreatePaymentResponse_Accepted_); ok {
			return x.Accepted
		}
	}
	return nil
}

func (x *CreatePaymentResponse) GetSettlementRequired() *CreatePaymentResponse_SettlementRequired {
	if x != nil {
		if x, ok := x.Result.(*CreatePaymentResponse_SettlementRequired_); ok {
			return x.SettlementRequired
		}
	}
	return nil
}

func (x *CreatePaymentResponse) GetFailure() *CreatePaymentResponse_Failure {
	if x != nil {
		if x, ok := x.Result.(*CreatePaymentResponse_Failure_); ok {
			return x.Failure
		}
	}
	return nil
}

type isCreatePaymentResponse_Result interface {
	isCreatePaymentResponse_Result()
}

type CreatePaymentResponse_Accepted_ struct {
	// *
	// Accepted response - means the payment was accepted, but the payout is not yet completed. This means, the network found
	// a suitable quote for the payout currency and amount, and instructed the payout provider to process the payout.
	Accepted *CreatePaymentResponse_Accepted `protobuf:"bytes,20,opt,name=accepted,proto3,oneof"`
}

type CreatePaymentResponse_SettlementRequired_ struct {
	// *
	// Settlement required response - indicates that the payment requires settlement before payout completion.
	SettlementRequired *CreatePaymentResponse_SettlementRequired `protobuf:"bytes,35,opt,name=settlement_required,json=settlementRequired,proto3,oneof"` //
}

type CreatePaymentResponse_Failure_ struct {
	// *
	// Failure response - means the payment was not accepted, e.g. the network could not find a suitable quote for the
	// payout currency and amount, or the credit limit is exceeded for the available quotes.
	Failure *CreatePaymentResponse_Failure `protobuf:"bytes,30,opt,name=failure,proto3,oneof"`
}

func (*CreatePaymentResponse_Accepted_) isCreatePaymentResponse_Result() {}

func (*CreatePaymentResponse_SettlementRequired_) isCreatePaymentResponse_Result() {}

func (*CreatePaymentResponse_Failure_) isCreatePaymentResponse_Result() {}

// Deprecated: Marked as deprecated in tzero/v1/payment/network.proto.
type ConfirmPayoutRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PaymentId uint64                 `protobuf:"varint,10,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"` // payment id assigned by the network, this is the same payment id that was provided in the PayoutRequest
	// Deprecated: Marked as deprecated in tzero/v1/payment/network.proto.
	PayoutId uint64 `protobuf:"varint,20,opt,name=payout_id,json=payoutId,proto3" json:"payout_id,omitempty"` // deprecated, this is 1->1 mapping between payment and payout ids
	// *
	// Payment receipt might contain metadata about payment recognizable by pay-in provider.
	Receipt       *common.PaymentReceipt `protobuf:"bytes,30,opt,name=receipt,proto3,oneof" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPayoutRequest) Reset() {
	*x = ConfirmPayoutRequest{}
	mi := &file_tzero_v1_payment_network_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPayoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPayoutRequest) ProtoMessage() {}

func (x *ConfirmPayoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_network_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPayoutRequest.ProtoReflect.Descriptor instead.
func (*ConfirmPayoutRequest) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{7}
}

func (x *ConfirmPayoutRequest) GetPaymentId() uint64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

// Deprecated: Marked as deprecated in tzero/v1/payment/network.proto.
func (x *ConfirmPayoutRequest) GetPayoutId() uint64 {
	if x != nil {
		return x.PayoutId
	}
	return 0
}

func (x *ConfirmPayoutRequest) GetReceipt() *common.PaymentReceipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

// Deprecated: Marked as deprecated in tzero/v1/payment/network.proto.
type ConfirmPayoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPayoutResponse) Reset() {
	*x = ConfirmPayoutResponse{}
	mi := &file_tzero_v1_payment_network_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPayoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPayoutResponse) ProtoMessage() {}

func (x *ConfirmPayoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_network_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPayoutResponse.ProtoReflect.Descriptor instead.
func (*ConfirmPayoutResponse) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{8}
}

type CompleteManualAmlCheckRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PaymentId uint64                 `protobuf:"varint,10,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*CompleteManualAmlCheckRequest_Approved_
	//	*CompleteManualAmlCheckRequest_Rejected_
	Result        isCompleteManualAmlCheckRequest_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteManualAmlCheckRequest) Reset() {
	*x = CompleteManualAmlCheckRequest{}
	mi := &file_tzero_v1_payment_network_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteManualAmlCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteManualAmlCheckRequest) ProtoMessage() {}

func (x *CompleteManualAmlCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_network_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteManualAmlCheckRequest.ProtoReflect.Descriptor instead.
func (*CompleteManualAmlCheckRequest) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{9}
}

func (x *CompleteManualAmlCheckRequest) GetPaymentId() uint64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *CompleteManualAmlCheckRequest) GetResult() isCompleteManualAmlCheckRequest_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CompleteManualAmlCheckRequest) GetApproved() *CompleteManualAmlCheckRequest_Approved {
	if x != nil {
		if x, ok := x.Result.(*CompleteManualAmlCheckRequest_Approved_); ok {
			return x.Approved
		}
	}
	return nil
}

func (x *CompleteManualAmlCheckRequest) GetRejected() *CompleteManualAmlCheckRequest_Rejected {
	if x != nil {
		if x, ok := x.Result.(*CompleteManualAmlCheckRequest_Rejected_); ok {
			return x.Rejected
		}
	}
	return nil
}

type isCompleteManualAmlCheckRequest_Result interface {
	isCompleteManualAmlCheckRequest_Result()
}

type CompleteManualAmlCheckRequest_Approved_ struct {
	Approved *CompleteManualAmlCheckRequest_Approved `protobuf:"bytes,30,opt,name=approved,proto3,oneof"`
}

type CompleteManualAmlCheckRequest_Rejected_ struct {
	Rejected *CompleteManualAmlCheckRequest_Rejected `protobuf:"bytes,40,opt,name=rejected,proto3,oneof"`
}

func (*CompleteManualAmlCheckRequest_Approved_) isCompleteManualAmlCheckRequest_Result() {}

func (*CompleteManualAmlCheckRequest_Rejected_) isCompleteManualAmlCheckRequest_Result() {}

type CompleteManualAmlCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*CompleteManualAmlCheckResponse_Approved_
	//	*CompleteManualAmlCheckResponse_Rejected_
	Result        isCompleteManualAmlCheckResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteManualAmlCheckResponse) Reset() {
	*x = CompleteManualAmlCheckResponse{}
	mi := &file_tzero_v1_payment_network_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteManualAmlCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteManualAmlCheckResponse) ProtoMessage() {}

func (x *CompleteManualAmlCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_network_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteManualAmlCheckResponse.ProtoReflect.Descriptor instead.
func (*CompleteManualAmlCheckResponse) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{10}
}

func (x *CompleteManualAmlCheckResponse) GetResult() isCompleteManualAmlCheckResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CompleteManualAmlCheckResponse) GetApproved() *CompleteManualAmlCheckResponse_Approved {
	if x != nil {
		if x, ok := x.Result.(*CompleteManualAmlCheckResponse_Approved_); ok {
			return x.Approved
		}
	}
	return nil
}

func (x *CompleteManualAmlCheckResponse) GetRejected() *CompleteManualAmlCheckResponse_Rejected {
	if x != nil {
		if x, ok := x.Result.(*CompleteManualAmlCheckResponse_Rejected_); ok {
			return x.Rejected
		}
	}
	return nil
}

type isCompleteManualAmlCheckResponse_Result interface {
	isCompleteManualAmlCheckResponse_Result()
}

type CompleteManualAmlCheckResponse_Approved_ struct {
	Approved *CompleteManualAmlCheckResponse_Approved `protobuf:"bytes,30,opt,name=approved,proto3,oneof"`
}

type CompleteManualAmlCheckResponse_Rejected_ struct {
	Rejected *CompleteManualAmlCheckResponse_Rejected `protobuf:"bytes,40,opt,name=rejected,proto3,oneof"`
}

func (*CompleteManualAmlCheckResponse_Approved_) isCompleteManualAmlCheckResponse_Result() {}

func (*CompleteManualAmlCheckResponse_Rejected_) isCompleteManualAmlCheckResponse_Result() {}

// Payment amount could be specified either as settlement amount and then converted to corresponding amount of pay-out amount
// or as pay-out amount, so that the settlement amount is calculated accordingly
type PaymentAmount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Amount:
	//
	//	*PaymentAmount_PayOutAmount
	//	*PaymentAmount_SettlementAmount
	Amount        isPaymentAmount_Amount `protobuf_oneof:"amount"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentAmount) Reset() {
	*x = PaymentAmount{}
	mi := &file_tzero_v1_payment_network_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentAmount) ProtoMessage() {}

func (x *PaymentAmount) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_network_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentAmount.ProtoReflect.Descriptor instead.
func (*PaymentAmount) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{11}
}

func (x *PaymentAmount) GetAmount() isPaymentAmount_Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *PaymentAmount) GetPayOutAmount() *common.Decimal {
	if x != nil {
		if x, ok := x.Amount.(*PaymentAmount_PayOutAmount); ok {
			return x.PayOutAmount
		}
	}
	return nil
}

func (x *PaymentAmount) GetSettlementAmount() *common.Decimal {
	if x != nil {
		if x, ok := x.Amount.(*PaymentAmount_SettlementAmount); ok {
			return x.SettlementAmount
		}
	}
	return nil
}

type isPaymentAmount_Amount interface {
	isPaymentAmount_Amount()
}

type PaymentAmount_PayOutAmount struct {
	PayOutAmount *common.Decimal `protobuf:"bytes,20,opt,name=pay_out_amount,json=payOutAmount,proto3,oneof"` // Amount in the pay-out currency
}

type PaymentAmount_SettlementAmount struct {
	SettlementAmount *common.Decimal `protobuf:"bytes,30,opt,name=settlement_amount,json=settlementAmount,proto3,oneof"` // Settlement amount in the settlement currency
}

func (*PaymentAmount_PayOutAmount) isPaymentAmount_Amount() {}

func (*PaymentAmount_SettlementAmount) isPaymentAmount_Amount() {}

type FinalizePayoutRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PaymentId uint64                 `protobuf:"varint,10,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"` // payment id assigned by the network, this is the same payment id that was provided in the PayoutRequest
	// Types that are valid to be assigned to Result:
	//
	//	*FinalizePayoutRequest_Success_
	//	*FinalizePayoutRequest_Failure_
	Result        isFinalizePayoutRequest_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizePayoutRequest) Reset() {
	*x = FinalizePayoutRequest{}
	mi := &file_tzero_v1_payment_network_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizePayoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizePayoutRequest) ProtoMessage() {}

func (x *FinalizePayoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_network_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizePayoutRequest.ProtoReflect.Descriptor instead.
func (*FinalizePayoutRequest) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{12}
}

func (x *FinalizePayoutRequest) GetPaymentId() uint64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *FinalizePayoutRequest) GetResult() isFinalizePayoutRequest_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *FinalizePayoutRequest) GetSuccess() *FinalizePayoutRequest_Success {
	if x != nil {
		if x, ok := x.Result.(*FinalizePayoutRequest_Success_); ok {
			return x.Success
		}
	}
	return nil
}

func (x *FinalizePayoutRequest) GetFailure() *FinalizePayoutRequest_Failure {
	if x != nil {
		if x, ok := x.Result.(*FinalizePayoutRequest_Failure_); ok {
			return x.Failure
		}
	}
	return nil
}

type isFinalizePayoutRequest_Result interface {
	isFinalizePayoutRequest_Result()
}

type FinalizePayoutRequest_Success_ struct {
	Success *FinalizePayoutRequest_Success `protobuf:"bytes,30,opt,name=success,proto3,oneof"`
}

type FinalizePayoutRequest_Failure_ struct {
	Failure *FinalizePayoutRequest_Failure `protobuf:"bytes,40,opt,name=failure,proto3,oneof"`
}

func (*FinalizePayoutRequest_Success_) isFinalizePayoutRequest_Result() {}

func (*FinalizePayoutRequest_Failure_) isFinalizePayoutRequest_Result() {}

type FinalizePayoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizePayoutResponse) Reset() {
	*x = FinalizePayoutResponse{}
	mi := &file_tzero_v1_payment_network_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizePayoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizePayoutResponse) ProtoMessage() {}

func (x *FinalizePayoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_network_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizePayoutResponse.ProtoReflect.Descriptor instead.
func (*FinalizePayoutResponse) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{13}
}

type UpdateQuoteRequest_Quote struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Currency  string                 `protobuf:"bytes,10,opt,name=currency,proto3" json:"currency,omitempty"` // BRL, EUR, GBP, etc. (ISO 4217 currency code)
	QuoteType QuoteType              `protobuf:"varint,20,opt,name=quote_type,json=quoteType,proto3,enum=tzero.v1.payment.QuoteType" json:"quote_type,omitempty"`
	// Payment method must be specified
	PaymentMethod common.PaymentMethodType         `protobuf:"varint,25,opt,name=payment_method,json=paymentMethod,proto3,enum=tzero.v1.common.PaymentMethodType" json:"payment_method,omitempty"`
	Bands         []*UpdateQuoteRequest_Quote_Band `protobuf:"bytes,30,rep,name=bands,proto3" json:"bands,omitempty"`           // list of bands for this quote
	Expiration    *timestamppb.Timestamp           `protobuf:"bytes,60,opt,name=expiration,proto3" json:"expiration,omitempty"` // expiration time of the quote
	Timestamp     *timestamppb.Timestamp           `protobuf:"bytes,70,opt,name=timestamp,proto3" json:"timestamp,omitempty"`   // timestamp quote was created
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuoteRequest_Quote) Reset() {
	*x = UpdateQuoteRequest_Quote{}
	mi := &file_tzero_v1_payment_network_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuoteRequest_Quote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuoteRequest_Quote) ProtoMessage() {}

func (x *UpdateQuoteRequest_Quote) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_network_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuoteRequest_Quote.ProtoReflect.Descriptor instead.
func (*UpdateQuoteRequest_Quote) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{0, 0}
}

func (x *UpdateQuoteRequest_Quote) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdateQuoteRequest_Quote) GetQuoteType() QuoteType {
	if x != nil {
		return x.QuoteType
	}
	return QuoteType_QUOTE_TYPE_UNSPECIFIED
}

func (x *UpdateQuoteRequest_Quote) GetPaymentMethod() common.PaymentMethodType {
	if x != nil {
		return x.PaymentMethod
	}
	return common.PaymentMethodType(0)
}

func (x *UpdateQuoteRequest_Quote) GetBands() []*UpdateQuoteRequest_Quote_Band {
	if x != nil {
		return x.Bands
	}
	return nil
}

func (x *UpdateQuoteRequest_Quote) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (x *UpdateQuoteRequest_Quote) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type UpdateQuoteRequest_Quote_Band struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientQuoteId string                 `protobuf:"bytes,10,opt,name=client_quote_id,json=clientQuoteId,proto3" json:"client_quote_id,omitempty"` // unique client generated id for this band
	MaxAmount     *common.Decimal        `protobuf:"bytes,40,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`               // max amount of USD this quote is applicable for. Please look into documentation for valid amounts.
	Rate          *common.Decimal        `protobuf:"bytes,50,opt,name=rate,proto3" json:"rate,omitempty"`                                          // USD/currency rate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuoteRequest_Quote_Band) Reset() {
	*x = UpdateQuoteRequest_Quote_Band{}
	mi := &file_tzero_v1_payment_network_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuoteRequest_Quote_Band) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuoteRequest_Quote_Band) ProtoMessage() {}

func (x *UpdateQuoteRequest_Quote_Band) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_network_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuoteRequest_Quote_Band.ProtoReflect.Descriptor instead.
func (*UpdateQuoteRequest_Quote_Band) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *UpdateQuoteRequest_Quote_Band) GetClientQuoteId() string {
	if x != nil {
		return x.ClientQuoteId
	}
	return ""
}

func (x *UpdateQuoteRequest_Quote_Band) GetMaxAmount() *common.Decimal {
	if x != nil {
		return x.MaxAmount
	}
	return nil
}

func (x *UpdateQuoteRequest_Quote_Band) GetRate() *common.Decimal {
	if x != nil {
		return x.Rate
	}
	return nil
}

type GetQuoteResponse_Success struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Rate             *common.Decimal        `protobuf:"bytes,10,opt,name=rate,proto3" json:"rate,omitempty"`                                                 // pay-out quote rate in settlement_currency/pay_out_currency, i.e. USD/pay_out_currency
	Expiration       *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=expiration,proto3" json:"expiration,omitempty"`                                     // expiration time of the payout quote
	QuoteId          *QuoteId               `protobuf:"bytes,30,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`                            // id of the payout quote
	PayOutAmount     *common.Decimal        `protobuf:"bytes,40,opt,name=pay_out_amount,json=payOutAmount,proto3" json:"pay_out_amount,omitempty"`           // pay-out amount in pay-out currency if the quote from response is used
	SettlementAmount *common.Decimal        `protobuf:"bytes,50,opt,name=settlement_amount,json=settlementAmount,proto3" json:"settlement_amount,omitempty"` // settlement amount in settlement currency if the quote from response is used
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetQuoteResponse_Success) Reset() {
	*x = GetQuoteResponse_Success{}
	mi := &file_tzero_v1_payment_network_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuoteResponse_Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteResponse_Success) ProtoMessage() {}

func (x *GetQuoteResponse_Success) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_network_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteResponse_Success.ProtoReflect.Descriptor instead.
func (*GetQuoteResponse_Success) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetQuoteResponse_Success) GetRate() *common.Decimal {
	if x != nil {
		return x.Rate
	}
	return nil
}

func (x *GetQuoteResponse_Success) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (x *GetQuoteResponse_Success) GetQuoteId() *QuoteId {
	if x != nil {
		return x.QuoteId
	}
	return nil
}

func (x *GetQuoteResponse_Success) GetPayOutAmount() *common.Decimal {
	if x != nil {
		return x.PayOutAmount
	}
	return nil
}

func (x *GetQuoteResponse_Success) GetSettlementAmount() *common.Decimal {
	if x != nil {
		return x.SettlementAmount
	}
	return nil
}

type GetQuoteResponse_Failure struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Reason        GetQuoteResponse_Failure_Reason `protobuf:"varint,10,opt,name=reason,proto3,enum=tzero.v1.payment.GetQuoteResponse_Failure_Reason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuoteResponse_Failure) Reset() {
	*x = GetQuoteResponse_Failure{}
	mi := &file_tzero_v1_payment_network_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuoteResponse_Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteResponse_Failure) ProtoMessage() {}

func (x *GetQuoteResponse_Failure) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_network_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteResponse_Failure.ProtoReflect.Descriptor instead.
func (*GetQuoteResponse_Failure) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{3, 1}
}

func (x *GetQuoteResponse_Failure) GetReason() GetQuoteResponse_Failure_Reason {
	if x != nil {
		return x.Reason
	}
	return GetQuoteResponse_Failure_REASON_UNSPECIFIED
}

type CreatePaymentRequest_TravelRuleData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// the natural or legal person that requests payment with originating provider
	Originator []*ivms.Person `protobuf:"bytes,10,rep,name=originator,proto3" json:"originator,omitempty"`
	// *
	// the natural or legal person or legal arrangement who is identified
	// by the originator as the receiver of the requested payment.
	Beneficiary   []*ivms.Person `protobuf:"bytes,20,rep,name=beneficiary,proto3" json:"beneficiary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest_TravelRuleData) Reset() {
	*x = CreatePaymentRequest_TravelRuleData{}
	mi := &file_tzero_v1_payment_network_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest_TravelRuleData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest_TravelRuleData) ProtoMessage() {}

func (x *CreatePaymentRequest_TravelRuleData) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_network_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest_TravelRuleData.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest_TravelRuleData) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{4, 0}
}

func (x *CreatePaymentRequest_TravelRuleData) GetOriginator() []*ivms.Person {
	if x != nil {
		return x.Originator
	}
	return nil
}

func (x *CreatePaymentRequest_TravelRuleData) GetBeneficiary() []*ivms.Person {
	if x != nil {
		return x.Beneficiary
	}
	return nil
}

type CreatePaymentResponse_Accepted struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PaymentId        uint64                 `protobuf:"varint,10,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"` // payment ID assigned by the network
	SettlementAmount *common.Decimal        `protobuf:"bytes,30,opt,name=settlement_amount,json=settlementAmount,proto3" json:"settlement_amount,omitempty"`
	PayoutAmount     *common.Decimal        `protobuf:"bytes,40,opt,name=payout_amount,json=payoutAmount,proto3" json:"payout_amount,omitempty"`
	PayoutProviderId uint32                 `protobuf:"varint,50,opt,name=payout_provider_id,json=payoutProviderId,proto3" json:"payout_provider_id,omitempty"` // payout provider id with the best quote selected for this payment
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreatePaymentResponse_Accepted) Reset() {
	*x = CreatePaymentResponse_Accepted{}
	mi := &file_tzero_v1_payment_network_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse_Accepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse_Accepted) ProtoMessage() {}

func (x *CreatePaymentResponse_Accepted) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_network_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse_Accepted.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse_Accepted) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{6, 0}
}

func (x *CreatePaymentResponse_Accepted) GetPaymentId() uint64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *CreatePaymentResponse_Accepted) GetSettlementAmount() *common.Decimal {
	if x != nil {
		return x.SettlementAmount
	}
	return nil
}

func (x *CreatePaymentResponse_Accepted) GetPayoutAmount() *common.Decimal {
	if x != nil {
		return x.PayoutAmount
	}
	return nil
}

func (x *CreatePaymentResponse_Accepted) GetPayoutProviderId() uint32 {
	if x != nil {
		return x.PayoutProviderId
	}
	return 0
}

type CreatePaymentResponse_SettlementRequired struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PaymentId        uint64                 `protobuf:"varint,10,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"` // payment ID assigned by the network
	SettlementAmount *common.Decimal        `protobuf:"bytes,20,opt,name=settlement_amount,json=settlementAmount,proto3" json:"settlement_amount,omitempty"`
	PayoutProviderId uint32                 `protobuf:"varint,30,opt,name=payout_provider_id,json=payoutProviderId,proto3" json:"payout_provider_id,omitempty"` // payout provider id with the best quote selected for this payment
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreatePaymentResponse_SettlementRequired) Reset() {
	*x = CreatePaymentResponse_SettlementRequired{}
	mi := &file_tzero_v1_payment_network_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse_SettlementRequired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse_SettlementRequired) ProtoMessage() {}

func (x *CreatePaymentResponse_SettlementRequired) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_network_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse_SettlementRequired.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse_SettlementRequired) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{6, 1}
}

func (x *CreatePaymentResponse_SettlementRequired) GetPaymentId() uint64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *CreatePaymentResponse_SettlementRequired) GetSettlementAmount() *common.Decimal {
	if x != nil {
		return x.SettlementAmount
	}
	return nil
}

func (x *CreatePaymentResponse_SettlementRequired) GetPayoutProviderId() uint32 {
	if x != nil {
		return x.PayoutProviderId
	}
	return 0
}

type CreatePaymentResponse_Failure struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Reason        CreatePaymentResponse_Failure_Reason `protobuf:"varint,10,opt,name=reason,proto3,enum=tzero.v1.payment.CreatePaymentResponse_Failure_Reason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResponse_Failure) Reset() {
	*x = CreatePaymentResponse_Failure{}
	mi := &file_tzero_v1_payment_network_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse_Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse_Failure) ProtoMessage() {}

func (x *CreatePaymentResponse_Failure) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_network_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse_Failure.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse_Failure) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{6, 2}
}

func (x *CreatePaymentResponse_Failure) GetReason() CreatePaymentResponse_Failure_Reason {
	if x != nil {
		return x.Reason
	}
	return CreatePaymentResponse_Failure_REASON_UNSPECIFIED
}

type CompleteManualAmlCheckRequest_Approved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteManualAmlCheckRequest_Approved) Reset() {
	*x = CompleteManualAmlCheckRequest_Approved{}
	mi := &file_tzero_v1_payment_network_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteManualAmlCheckRequest_Approved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteManualAmlCheckRequest_Approved) ProtoMessage() {}

func (x *CompleteManualAmlCheckRequest_Approved) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_network_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteManualAmlCheckRequest_Approved.ProtoReflect.Descriptor instead.
func (*CompleteManualAmlCheckRequest_Approved) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{9, 0}
}

type CompleteManualAmlCheckRequest_Rejected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,10,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteManualAmlCheckRequest_Rejected) Reset() {
	*x = CompleteManualAmlCheckRequest_Rejected{}
	mi := &file_tzero_v1_payment_network_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteManualAmlCheckRequest_Rejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteManualAmlCheckRequest_Rejected) ProtoMessage() {}

func (x *CompleteManualAmlCheckRequest_Rejected) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_network_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteManualAmlCheckRequest_Rejected.ProtoReflect.Descriptor instead.
func (*CompleteManualAmlCheckRequest_Rejected) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{9, 1}
}

func (x *CompleteManualAmlCheckRequest_Rejected) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CompleteManualAmlCheckResponse_Approved struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// updated amount based on updated quote approved by the  pay-in provider
	PayOutAmount *common.Decimal `protobuf:"bytes,10,opt,name=pay_out_amount,json=payOutAmount,proto3" json:"pay_out_amount,omitempty"`
	// updated settlement amount based on updated quote approved by the  pay-in provider
	SettlementAmount *common.Decimal `protobuf:"bytes,20,opt,name=settlement_amount,json=settlementAmount,proto3" json:"settlement_amount,omitempty"`
	// unique identifier of the updated pay-out quote
	PayOutQuoteId int64 `protobuf:"varint,30,opt,name=pay_out_quote_id,json=payOutQuoteId,proto3" json:"pay_out_quote_id,omitempty"`
	// client_quote_id of the updated pay-out quote assigned by pay-out provider
	PayOutClientQuoteId string `protobuf:"bytes,40,opt,name=pay_out_client_quote_id,json=payOutClientQuoteId,proto3" json:"pay_out_client_quote_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CompleteManualAmlCheckResponse_Approved) Reset() {
	*x = CompleteManualAmlCheckResponse_Approved{}
	mi := &file_tzero_v1_payment_network_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteManualAmlCheckResponse_Approved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteManualAmlCheckResponse_Approved) ProtoMessage() {}

func (x *CompleteManualAmlCheckResponse_Approved) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_network_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteManualAmlCheckResponse_Approved.ProtoReflect.Descriptor instead.
func (*CompleteManualAmlCheckResponse_Approved) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{10, 0}
}

func (x *CompleteManualAmlCheckResponse_Approved) GetPayOutAmount() *common.Decimal {
	if x != nil {
		return x.PayOutAmount
	}
	return nil
}

func (x *CompleteManualAmlCheckResponse_Approved) GetSettlementAmount() *common.Decimal {
	if x != nil {
		return x.SettlementAmount
	}
	return nil
}

func (x *CompleteManualAmlCheckResponse_Approved) GetPayOutQuoteId() int64 {
	if x != nil {
		return x.PayOutQuoteId
	}
	return 0
}

func (x *CompleteManualAmlCheckResponse_Approved) GetPayOutClientQuoteId() string {
	if x != nil {
		return x.PayOutClientQuoteId
	}
	return ""
}

// Rejected means that the updated quotes were rejected by pay-in provider, and the payout provider should not proceed
// with the payout.
type CompleteManualAmlCheckResponse_Rejected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteManualAmlCheckResponse_Rejected) Reset() {
	*x = CompleteManualAmlCheckResponse_Rejected{}
	mi := &file_tzero_v1_payment_network_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteManualAmlCheckResponse_Rejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteManualAmlCheckResponse_Rejected) ProtoMessage() {}

func (x *CompleteManualAmlCheckResponse_Rejected) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_network_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteManualAmlCheckResponse_Rejected.ProtoReflect.Descriptor instead.
func (*CompleteManualAmlCheckResponse_Rejected) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{10, 1}
}

type FinalizePayoutRequest_Success struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Payment receipt might contain metadata about payment recognizable by pay-in provider.
	Receipt       *common.PaymentReceipt `protobuf:"bytes,30,opt,name=receipt,proto3,oneof" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizePayoutRequest_Success) Reset() {
	*x = FinalizePayoutRequest_Success{}
	mi := &file_tzero_v1_payment_network_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizePayoutRequest_Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizePayoutRequest_Success) ProtoMessage() {}

func (x *FinalizePayoutRequest_Success) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_network_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizePayoutRequest_Success.ProtoReflect.Descriptor instead.
func (*FinalizePayoutRequest_Success) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{12, 0}
}

func (x *FinalizePayoutRequest_Success) GetReceipt() *common.PaymentReceipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

type FinalizePayoutRequest_Failure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,10,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizePayoutRequest_Failure) Reset() {
	*x = FinalizePayoutRequest_Failure{}
	mi := &file_tzero_v1_payment_network_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizePayoutRequest_Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizePayoutRequest_Failure) ProtoMessage() {}

func (x *FinalizePayoutRequest_Failure) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_network_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizePayoutRequest_Failure.ProtoReflect.Descriptor instead.
func (*FinalizePayoutRequest_Failure) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_network_proto_rawDescGZIP(), []int{12, 1}
}

func (x *FinalizePayoutRequest_Failure) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_tzero_v1_payment_network_proto protoreflect.FileDescriptor

const file_tzero_v1_payment_network_proto_rawDesc = "" +
	"\n" +
	"\x1etzero/v1/payment/network.proto\x12\x10tzero.v1.payment\x1a\x1ctzero/v1/common/common.proto\x1a$tzero/v1/common/payment_method.proto\x1a%tzero/v1/common/payment_receipt.proto\x1a\x1divms101/v1/ivms/ivms101.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\xfb\x05\n" +
	"\x12UpdateQuoteRequest\x12C\n" +
	"\apay_out\x18\n" +
	" \x03(\v2*.tzero.v1.payment.UpdateQuoteRequest.QuoteR\x06payOut\x12A\n" +
	"\x06pay_in\x18\x14 \x03(\v2*.tzero.v1.payment.UpdateQuoteRequest.QuoteR\x05payIn\x1a\xdc\x04\n" +
	"\x05Quote\x120\n" +
	"\bcurrency\x18\n" +
	" \x01(\tB\x14\xbaH\x11r\x0f2\n" +
	"^[A-Z]{3}$\x98\x01\x03R\bcurrency\x12B\n" +
	"\n" +
	"quote_type\x18\x14 \x01(\x0e2\x1b.tzero.v1.payment.QuoteTypeB\x06\xbaH\x03\xc8\x01\x01R\tquoteType\x12Q\n" +
	"\x0epayment_method\x18\x19 \x01(\x0e2\".tzero.v1.common.PaymentMethodTypeB\x06\xbaH\x03\xc8\x01\x01R\rpaymentMethod\x12O\n" +
	"\x05bands\x18\x1e \x03(\v2/.tzero.v1.payment.UpdateQuoteRequest.Quote.BandB\b\xbaH\x05\x92\x01\x02\b\x01R\x05bands\x12D\n" +
	"\n" +
	"expiration\x18< \x01(\v2\x1a.google.protobuf.TimestampB\b\xbaH\x05\xb2\x01\x02@\x01R\n" +
	"expiration\x12@\n" +
	"\ttimestamp\x18F \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\ttimestamp\x1a\xb0\x01\n" +
	"\x04Band\x121\n" +
	"\x0fclient_quote_id\x18\n" +
	" \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\rclientQuoteId\x12?\n" +
	"\n" +
	"max_amount\x18( \x01(\v2\x18.tzero.v1.common.DecimalB\x06\xbaH\x03\xc8\x01\x01R\tmaxAmount\x124\n" +
	"\x04rate\x182 \x01(\v2\x18.tzero.v1.common.DecimalB\x06\xbaH\x03\xc8\x01\x01R\x04rate\"\x15\n" +
	"\x13UpdateQuoteResponse\"\xa8\x02\n" +
	"\x0fGetQuoteRequest\x12?\n" +
	"\x06amount\x18\x14 \x01(\v2\x1f.tzero.v1.payment.PaymentAmountB\x06\xbaH\x03\xc8\x01\x01R\x06amount\x12>\n" +
	"\x10pay_out_currency\x18( \x01(\tB\x14\xbaH\x11r\x0f2\n" +
	"^[A-Z]{3}$\x98\x01\x03R\x0epayOutCurrency\x12P\n" +
	"\x0epay_out_method\x182 \x01(\x0e2\".tzero.v1.common.PaymentMethodTypeB\x06\xbaH\x03\xc8\x01\x01R\fpayOutMethod\x12B\n" +
	"\n" +
	"quote_type\x18< \x01(\x0e2\x1b.tzero.v1.payment.QuoteTypeB\x06\xbaH\x03\xc8\x01\x01R\tquoteType\"\xa5\x05\n" +
	"\x10GetQuoteResponse\x12F\n" +
	"\asuccess\x18\x14 \x01(\v2*.tzero.v1.payment.GetQuoteResponse.SuccessH\x00R\asuccess\x12F\n" +
	"\afailure\x18\x1e \x01(\v2*.tzero.v1.payment.GetQuoteResponse.FailureH\x00R\afailure\x1a\xda\x02\n" +
	"\aSuccess\x124\n" +
	"\x04rate\x18\n" +
	" \x01(\v2\x18.tzero.v1.common.DecimalB\x06\xbaH\x03\xc8\x01\x01R\x04rate\x12D\n" +
	"\n" +
	"expiration\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampB\b\xbaH\x05\xb2\x01\x02@\x01R\n" +
	"expiration\x12<\n" +
	"\bquote_id\x18\x1e \x01(\v2\x19.tzero.v1.payment.QuoteIdB\x06\xbaH\x03\xc8\x01\x01R\aquoteId\x12F\n" +
	"\x0epay_out_amount\x18( \x01(\v2\x18.tzero.v1.common.DecimalB\x06\xbaH\x03\xc8\x01\x01R\fpayOutAmount\x12M\n" +
	"\x11settlement_amount\x182 \x01(\v2\x18.tzero.v1.common.DecimalB\x06\xbaH\x03\xc8\x01\x01R\x10settlementAmount\x1a\x92\x01\n" +
	"\aFailure\x12I\n" +
	"\x06reason\x18\n" +
	" \x01(\x0e21.tzero.v1.payment.GetQuoteResponse.Failure.ReasonR\x06reason\"<\n" +
	"\x06Reason\x12\x16\n" +
	"\x12REASON_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16REASON_QUOTE_NOT_FOUND\x10\n" +
	"B\x0f\n" +
	"\x06result\x12\x05\xbaH\x02\b\x01\"\xe0\x04\n" +
	"\x14CreatePaymentRequest\x125\n" +
	"\x11payment_client_id\x18\n" +
	" \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\x0fpaymentClientId\x12?\n" +
	"\x06amount\x18\x1e \x01(\v2\x1f.tzero.v1.payment.PaymentAmountB\x06\xbaH\x03\xc8\x01\x01R\x06amount\x120\n" +
	"\bcurrency\x18( \x01(\tB\x14\xbaH\x11r\x0f2\n" +
	"^[A-Z]{3}$\x98\x01\x03R\bcurrency\x12P\n" +
	"\x0fpayment_details\x182 \x01(\v2\x1f.tzero.v1.common.PaymentDetailsB\x06\xbaH\x03\xc8\x01\x01R\x0epaymentDetails\x129\n" +
	"\bquote_id\x18< \x01(\v2\x19.tzero.v1.payment.QuoteIdH\x00R\aquoteId\x88\x01\x01\x12d\n" +
	"\x10travel_rule_data\x18d \x01(\v25.tzero.v1.payment.CreatePaymentRequest.TravelRuleDataH\x01R\x0etravelRuleData\x88\x01\x01\x1a\x88\x01\n" +
	"\x0eTravelRuleData\x129\n" +
	"\n" +
	"originator\x18\n" +
	" \x03(\v2\x0f.ivms101.PersonB\b\xbaH\x05\x92\x01\x02\b\x01R\n" +
	"originator\x12;\n" +
	"\vbeneficiary\x18\x14 \x03(\v2\x0f.ivms101.PersonB\b\xbaH\x05\x92\x01\x02\b\x01R\vbeneficiaryB\v\n" +
	"\t_quote_idB\x13\n" +
	"\x11_travel_rule_data\"W\n" +
	"\aQuoteId\x12\"\n" +
	"\bquote_id\x18\x1e \x01(\x03B\a\xbaH\x04\"\x02 \x00R\aquoteId\x12(\n" +
	"\vprovider_id\x18( \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\n" +
	"providerId\"\xf4\a\n" +
	"\x15CreatePaymentResponse\x123\n" +
	"\x11payment_client_id\x18\n" +
	" \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0fpaymentClientId\x12N\n" +
	"\baccepted\x18\x14 \x01(\v20.tzero.v1.payment.CreatePaymentResponse.AcceptedH\x00R\baccepted\x12m\n" +
	"\x13settlement_required\x18# \x01(\v2:.tzero.v1.payment.CreatePaymentResponse.SettlementRequiredH\x00R\x12settlementRequired\x12K\n" +
	"\afailure\x18\x1e \x01(\v2/.tzero.v1.payment.CreatePaymentResponse.FailureH\x00R\afailure\x1a\xff\x01\n" +
	"\bAccepted\x12&\n" +
	"\n" +
	"payment_id\x18\n" +
	" \x01(\x04B\a\xbaH\x042\x02 \x00R\tpaymentId\x12M\n" +
	"\x11settlement_amount\x18\x1e \x01(\v2\x18.tzero.v1.common.DecimalB\x06\xbaH\x03\xc8\x01\x01R\x10settlementAmount\x12E\n" +
	"\rpayout_amount\x18( \x01(\v2\x18.tzero.v1.common.DecimalB\x06\xbaH\x03\xc8\x01\x01R\fpayoutAmount\x125\n" +
	"\x12payout_provider_id\x182 \x01(\rB\a\xbaH\x04*\x02 \x00R\x10payoutProviderId\x1a\xc2\x01\n" +
	"\x12SettlementRequired\x12&\n" +
	"\n" +
	"payment_id\x18\n" +
	" \x01(\x04B\a\xbaH\x042\x02 \x00R\tpaymentId\x12M\n" +
	"\x11settlement_amount\x18\x14 \x01(\v2\x18.tzero.v1.common.DecimalB\x06\xbaH\x03\xc8\x01\x01R\x10settlementAmount\x125\n" +
	"\x12payout_provider_id\x18\x1e \x01(\rB\a\xbaH\x04*\x02 \x00R\x10payoutProviderId\x1a\xc1\x01\n" +
	"\aFailure\x12N\n" +
	"\x06reason\x18\n" +
	" \x01(\x0e26.tzero.v1.payment.CreatePaymentResponse.Failure.ReasonR\x06reason\"f\n" +
	"\x06Reason\x12\x16\n" +
	"\x12REASON_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16REASON_QUOTE_NOT_FOUND\x10\n" +
	"\x12(\n" +
	"$REASON_CREDIT_OR_PREDEPOSIT_REQUIRED\x10\x14B\x0f\n" +
	"\x06result\x12\x05\xbaH\x02\b\x01\"\xb6\x01\n" +
	"\x14ConfirmPayoutRequest\x12&\n" +
	"\n" +
	"payment_id\x18\n" +
	" \x01(\x04B\a\xbaH\x042\x02 \x00R\tpaymentId\x12&\n" +
	"\tpayout_id\x18\x14 \x01(\x04B\t\xbaH\x042\x02 \x00\x18\x01R\bpayoutId\x12>\n" +
	"\areceipt\x18\x1e \x01(\v2\x1f.tzero.v1.common.PaymentReceiptH\x00R\areceipt\x88\x01\x01:\x02\x18\x01B\n" +
	"\n" +
	"\b_receipt\"\x1b\n" +
	"\x15ConfirmPayoutResponse:\x02\x18\x01\"\xc2\x02\n" +
	"\x1dCompleteManualAmlCheckRequest\x12&\n" +
	"\n" +
	"payment_id\x18\n" +
	" \x01(\x04B\a\xbaH\x042\x02 \x00R\tpaymentId\x12V\n" +
	"\bapproved\x18\x1e \x01(\v28.tzero.v1.payment.CompleteManualAmlCheckRequest.ApprovedH\x00R\bapproved\x12V\n" +
	"\brejected\x18( \x01(\v28.tzero.v1.payment.CompleteManualAmlCheckRequest.RejectedH\x00R\brejected\x1a\n" +
	"\n" +
	"\bApproved\x1a,\n" +
	"\bRejected\x12 \n" +
	"\x06reason\x18\n" +
	" \x01(\tB\b\xbaH\x05r\x03\x18\x80\bR\x06reasonB\x0f\n" +
	"\x06result\x12\x05\xbaH\x02\b\x01\"\x84\x04\n" +
	"\x1eCompleteManualAmlCheckResponse\x12W\n" +
	"\bapproved\x18\x1e \x01(\v29.tzero.v1.payment.CompleteManualAmlCheckResponse.ApprovedH\x00R\bapproved\x12W\n" +
	"\brejected\x18( \x01(\v29.tzero.v1.payment.CompleteManualAmlCheckResponse.RejectedH\x00R\brejected\x1a\x92\x02\n" +
	"\bApproved\x12F\n" +
	"\x0epay_out_amount\x18\n" +
	" \x01(\v2\x18.tzero.v1.common.DecimalB\x06\xbaH\x03\xc8\x01\x01R\fpayOutAmount\x12M\n" +
	"\x11settlement_amount\x18\x14 \x01(\v2\x18.tzero.v1.common.DecimalB\x06\xbaH\x03\xc8\x01\x01R\x10settlementAmount\x120\n" +
	"\x10pay_out_quote_id\x18\x1e \x01(\x03B\a\xbaH\x04\"\x02 \x00R\rpayOutQuoteId\x12=\n" +
	"\x17pay_out_client_quote_id\x18( \x01(\tB\a\xbaH\x04r\x02\x18@R\x13payOutClientQuoteId\x1a\n" +
	"\n" +
	"\bRejectedB\x0f\n" +
	"\x06result\x12\x05\xbaH\x02\b\x01\"\xab\x01\n" +
	"\rPaymentAmount\x12@\n" +
	"\x0epay_out_amount\x18\x14 \x01(\v2\x18.tzero.v1.common.DecimalH\x00R\fpayOutAmount\x12G\n" +
	"\x11settlement_amount\x18\x1e \x01(\v2\x18.tzero.v1.common.DecimalH\x00R\x10settlementAmountB\x0f\n" +
	"\x06amount\x12\x05\xbaH\x02\b\x01\"\xe4\x02\n" +
	"\x15FinalizePayoutRequest\x12&\n" +
	"\n" +
	"payment_id\x18\n" +
	" \x01(\x04B\a\xbaH\x042\x02 \x00R\tpaymentId\x12K\n" +
	"\asuccess\x18\x1e \x01(\v2/.tzero.v1.payment.FinalizePayoutRequest.SuccessH\x00R\asuccess\x12K\n" +
	"\afailure\x18( \x01(\v2/.tzero.v1.payment.FinalizePayoutRequest.FailureH\x00R\afailure\x1aU\n" +
	"\aSuccess\x12>\n" +
	"\areceipt\x18\x1e \x01(\v2\x1f.tzero.v1.common.PaymentReceiptH\x00R\areceipt\x88\x01\x01B\n" +
	"\n" +
	"\b_receipt\x1a!\n" +
	"\aFailure\x12\x16\n" +
	"\x06reason\x18\n" +
	" \x01(\tR\x06reasonB\x0f\n" +
	"\x06result\x12\x05\xbaH\x02\b\x01\"\x18\n" +
	"\x16FinalizePayoutResponse*@\n" +
	"\tQuoteType\x12\x1a\n" +
	"\x16QUOTE_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13QUOTE_TYPE_REALTIME\x10\x012\x87\x05\n" +
	"\x0eNetworkService\x12_\n" +
	"\vUpdateQuote\x12$.tzero.v1.payment.UpdateQuoteRequest\x1a%.tzero.v1.payment.UpdateQuoteResponse\"\x03\x90\x02\x02\x12V\n" +
	"\bGetQuote\x12!.tzero.v1.payment.GetQuoteRequest\x1a\".tzero.v1.payment.GetQuoteResponse\"\x03\x90\x02\x01\x12e\n" +
	"\rCreatePayment\x12&.tzero.v1.payment.CreatePaymentRequest\x1a'.tzero.v1.payment.CreatePaymentResponse\"\x03\x90\x02\x02\x12h\n" +
	"\rConfirmPayout\x12&.tzero.v1.payment.ConfirmPayoutRequest\x1a'.tzero.v1.payment.ConfirmPayoutResponse\"\x06\x88\x02\x01\x90\x02\x02\x12h\n" +
	"\x0eFinalizePayout\x12'.tzero.v1.payment.FinalizePayoutRequest\x1a(.tzero.v1.payment.FinalizePayoutResponse\"\x03\x90\x02\x02\x12\x80\x01\n" +
	"\x16CompleteManualAmlCheck\x12/.tzero.v1.payment.CompleteManualAmlCheckRequest\x1a0.tzero.v1.payment.CompleteManualAmlCheckResponse\"\x03\x90\x02\x02B\xc3\x01\n" +
	"\x14com.tzero.v1.paymentB\fNetworkProtoP\x01Z;github.com/t-0-network/provider-sdk-go/api/tzero/v1/payment\xa2\x02\x03TVP\xaa\x02\x10Tzero.V1.Payment\xca\x02\x10Tzero\\V1\\Payment\xe2\x02\x1cTzero\\V1\\Payment\\GPBMetadata\xea\x02\x12Tzero::V1::Paymentb\x06proto3"

var (
	file_tzero_v1_payment_network_proto_rawDescOnce sync.Once
	file_tzero_v1_payment_network_proto_rawDescData []byte
)

func file_tzero_v1_payment_network_proto_rawDescGZIP() []byte {
	file_tzero_v1_payment_network_proto_rawDescOnce.Do(func() {
		file_tzero_v1_payment_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tzero_v1_payment_network_proto_rawDesc), len(file_tzero_v1_payment_network_proto_rawDesc)))
	})
	return file_tzero_v1_payment_network_proto_rawDescData
}

var file_tzero_v1_payment_network_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_tzero_v1_payment_network_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_tzero_v1_payment_network_proto_goTypes = []any{
	(QuoteType)(0),                                   // 0: tzero.v1.payment.QuoteType
	(GetQuoteResponse_Failure_Reason)(0),             // 1: tzero.v1.payment.GetQuoteResponse.Failure.Reason
	(CreatePaymentResponse_Failure_Reason)(0),        // 2: tzero.v1.payment.CreatePaymentResponse.Failure.Reason
	(*UpdateQuoteRequest)(nil),                       // 3: tzero.v1.payment.UpdateQuoteRequest
	(*UpdateQuoteResponse)(nil),                      // 4: tzero.v1.payment.UpdateQuoteResponse
	(*GetQuoteRequest)(nil),                          // 5: tzero.v1.payment.GetQuoteRequest
	(*GetQuoteResponse)(nil),                         // 6: tzero.v1.payment.GetQuoteResponse
	(*CreatePaymentRequest)(nil),                     // 7: tzero.v1.payment.CreatePaymentRequest
	(*QuoteId)(nil),                                  // 8: tzero.v1.payment.QuoteId
	(*CreatePaymentResponse)(nil),                    // 9: tzero.v1.payment.CreatePaymentResponse
	(*ConfirmPayoutRequest)(nil),                     // 10: tzero.v1.payment.ConfirmPayoutRequest
	(*ConfirmPayoutResponse)(nil),                    // 11: tzero.v1.payment.ConfirmPayoutResponse
	(*CompleteManualAmlCheckRequest)(nil),            // 12: tzero.v1.payment.CompleteManualAmlCheckRequest
	(*CompleteManualAmlCheckResponse)(nil),           // 13: tzero.v1.payment.CompleteManualAmlCheckResponse
	(*PaymentAmount)(nil),                            // 14: tzero.v1.payment.PaymentAmount
	(*FinalizePayoutRequest)(nil),                    // 15: tzero.v1.payment.FinalizePayoutRequest
	(*FinalizePayoutResponse)(nil),                   // 16: tzero.v1.payment.FinalizePayoutResponse
	(*UpdateQuoteRequest_Quote)(nil),                 // 17: tzero.v1.payment.UpdateQuoteRequest.Quote
	(*UpdateQuoteRequest_Quote_Band)(nil),            // 18: tzero.v1.payment.UpdateQuoteRequest.Quote.Band
	(*GetQuoteResponse_Success)(nil),                 // 19: tzero.v1.payment.GetQuoteResponse.Success
	(*GetQuoteResponse_Failure)(nil),                 // 20: tzero.v1.payment.GetQuoteResponse.Failure
	(*CreatePaymentRequest_TravelRuleData)(nil),      // 21: tzero.v1.payment.CreatePaymentRequest.TravelRuleData
	(*CreatePaymentResponse_Accepted)(nil),           // 22: tzero.v1.payment.CreatePaymentResponse.Accepted
	(*CreatePaymentResponse_SettlementRequired)(nil), // 23: tzero.v1.payment.CreatePaymentResponse.SettlementRequired
	(*CreatePaymentResponse_Failure)(nil),            // 24: tzero.v1.payment.CreatePaymentResponse.Failure
	(*CompleteManualAmlCheckRequest_Approved)(nil),   // 25: tzero.v1.payment.CompleteManualAmlCheckRequest.Approved
	(*CompleteManualAmlCheckRequest_Rejected)(nil),   // 26: tzero.v1.payment.CompleteManualAmlCheckRequest.Rejected
	(*CompleteManualAmlCheckResponse_Approved)(nil),  // 27: tzero.v1.payment.CompleteManualAmlCheckResponse.Approved
	(*CompleteManualAmlCheckResponse_Rejected)(nil),  // 28: tzero.v1.payment.CompleteManualAmlCheckResponse.Rejected
	(*FinalizePayoutRequest_Success)(nil),            // 29: tzero.v1.payment.FinalizePayoutRequest.Success
	(*FinalizePayoutRequest_Failure)(nil),            // 30: tzero.v1.payment.FinalizePayoutRequest.Failure
	(common.PaymentMethodType)(0),                    // 31: tzero.v1.common.PaymentMethodType
	(*common.PaymentDetails)(nil),                    // 32: tzero.v1.common.PaymentDetails
	(*common.PaymentReceipt)(nil),                    // 33: tzero.v1.common.PaymentReceipt
	(*common.Decimal)(nil),                           // 34: tzero.v1.common.Decimal
	(*timestamppb.Timestamp)(nil),                    // 35: google.protobuf.Timestamp
	(*ivms.Person)(nil),                              // 36: ivms101.Person
}
var file_tzero_v1_payment_network_proto_depIdxs = []int32{
	17, // 0: tzero.v1.payment.UpdateQuoteRequest.pay_out:type_name -> tzero.v1.payment.UpdateQuoteRequest.Quote
	17, // 1: tzero.v1.payment.UpdateQuoteRequest.pay_in:type_name -> tzero.v1.payment.UpdateQuoteRequest.Quote
	14, // 2: tzero.v1.payment.GetQuoteRequest.amount:type_name -> tzero.v1.payment.PaymentAmount
	31, // 3: tzero.v1.payment.GetQuoteRequest.pay_out_method:type_name -> tzero.v1.common.PaymentMethodType
	0,  // 4: tzero.v1.payment.GetQuoteRequest.quote_type:type_name -> tzero.v1.payment.QuoteType
	19, // 5: tzero.v1.payment.GetQuoteResponse.success:type_name -> tzero.v1.payment.GetQuoteResponse.Success
	20, // 6: tzero.v1.payment.GetQuoteResponse.failure:type_name -> tzero.v1.payment.GetQuoteResponse.Failure
	14, // 7: tzero.v1.payment.CreatePaymentRequest.amount:type_name -> tzero.v1.payment.PaymentAmount
	32, // 8: tzero.v1.payment.CreatePaymentRequest.payment_details:type_name -> tzero.v1.common.PaymentDetails
	8,  // 9: tzero.v1.payment.CreatePaymentRequest.quote_id:type_name -> tzero.v1.payment.QuoteId
	21, // 10: tzero.v1.payment.CreatePaymentRequest.travel_rule_data:type_name -> tzero.v1.payment.CreatePaymentRequest.TravelRuleData
	22, // 11: tzero.v1.payment.CreatePaymentResponse.accepted:type_name -> tzero.v1.payment.CreatePaymentResponse.Accepted
	23, // 12: tzero.v1.payment.CreatePaymentResponse.settlement_required:type_name -> tzero.v1.payment.CreatePaymentResponse.SettlementRequired
	24, // 13: tzero.v1.payment.CreatePaymentResponse.failure:type_name -> tzero.v1.payment.CreatePaymentResponse.Failure
	33, // 14: tzero.v1.payment.ConfirmPayoutRequest.receipt:type_name -> tzero.v1.common.PaymentReceipt
	25, // 15: tzero.v1.payment.CompleteManualAmlCheckRequest.approved:type_name -> tzero.v1.payment.CompleteManualAmlCheckRequest.Approved
	26, // 16: tzero.v1.payment.CompleteManualAmlCheckRequest.rejected:type_name -> tzero.v1.payment.CompleteManualAmlCheckRequest.Rejected
	27, // 17: tzero.v1.payment.CompleteManualAmlCheckResponse.approved:type_name -> tzero.v1.payment.CompleteManualAmlCheckResponse.Approved
	28, // 18: tzero.v1.payment.CompleteManualAmlCheckResponse.rejected:type_name -> tzero.v1.payment.CompleteManualAmlCheckResponse.Rejected
	34, // 19: tzero.v1.payment.PaymentAmount.pay_out_amount:type_name -> tzero.v1.common.Decimal
	34, // 20: tzero.v1.payment.PaymentAmount.settlement_amount:type_name -> tzero.v1.common.Decimal
	29, // 21: tzero.v1.payment.FinalizePayoutRequest.success:type_name -> tzero.v1.payment.FinalizePayoutRequest.Success
	30, // 22: tzero.v1.payment.FinalizePayoutRequest.failure:type_name -> tzero.v1.payment.FinalizePayoutRequest.Failure
	0,  // 23: tzero.v1.payment.UpdateQuoteRequest.Quote.quote_type:type_name -> tzero.v1.payment.QuoteType
	31, // 24: tzero.v1.payment.UpdateQuoteRequest.Quote.payment_method:type_name -> tzero.v1.common.PaymentMethodType
	18, // 25: tzero.v1.payment.UpdateQuoteRequest.Quote.bands:type_name -> tzero.v1.payment.UpdateQuoteRequest.Quote.Band
	35, // 26: tzero.v1.payment.UpdateQuoteRequest.Quote.expiration:type_name -> google.protobuf.Timestamp
	35, // 27: tzero.v1.payment.UpdateQuoteRequest.Quote.timestamp:type_name -> google.protobuf.Timestamp
	34, // 28: tzero.v1.payment.UpdateQuoteRequest.Quote.Band.max_amount:type_name -> tzero.v1.common.Decimal
	34, // 29: tzero.v1.payment.UpdateQuoteRequest.Quote.Band.rate:type_name -> tzero.v1.common.Decimal
	34, // 30: tzero.v1.payment.GetQuoteResponse.Success.rate:type_name -> tzero.v1.common.Decimal
	35, // 31: tzero.v1.payment.GetQuoteResponse.Success.expiration:type_name -> google.protobuf.Timestamp
	8,  // 32: tzero.v1.payment.GetQuoteResponse.Success.quote_id:type_name -> tzero.v1.payment.QuoteId
	34, // 33: tzero.v1.payment.GetQuoteResponse.Success.pay_out_amount:type_name -> tzero.v1.common.Decimal
	34, // 34: tzero.v1.payment.GetQuoteResponse.Success.settlement_amount:type_name -> tzero.v1.common.Decimal
	1,  // 35: tzero.v1.payment.GetQuoteResponse.Failure.reason:type_name -> tzero.v1.payment.GetQuoteResponse.Failure.Reason
	36, // 36: tzero.v1.payment.CreatePaymentRequest.TravelRuleData.originator:type_name -> ivms101.Person
	36, // 37: tzero.v1.payment.CreatePaymentRequest.TravelRuleData.beneficiary:type_name -> ivms101.Person
	34, // 38: tzero.v1.payment.CreatePaymentResponse.Accepted.settlement_amount:type_name -> tzero.v1.common.Decimal
	34, // 39: tzero.v1.payment.CreatePaymentResponse.Accepted.payout_amount:type_name -> tzero.v1.common.Decimal
	34, // 40: tzero.v1.payment.CreatePaymentResponse.SettlementRequired.settlement_amount:type_name -> tzero.v1.common.Decimal
	2,  // 41: tzero.v1.payment.CreatePaymentResponse.Failure.reason:type_name -> tzero.v1.payment.CreatePaymentResponse.Failure.Reason
	34, // 42: tzero.v1.payment.CompleteManualAmlCheckResponse.Approved.pay_out_amount:type_name -> tzero.v1.common.Decimal
	34, // 43: tzero.v1.payment.CompleteManualAmlCheckResponse.Approved.settlement_amount:type_name -> tzero.v1.common.Decimal
	33, // 44: tzero.v1.payment.FinalizePayoutRequest.Success.receipt:type_name -> tzero.v1.common.PaymentReceipt
	3,  // 45: tzero.v1.payment.NetworkService.UpdateQuote:input_type -> tzero.v1.payment.UpdateQuoteRequest
	5,  // 46: tzero.v1.payment.NetworkService.GetQuote:input_type -> tzero.v1.payment.GetQuoteRequest
	7,  // 47: tzero.v1.payment.NetworkService.CreatePayment:input_type -> tzero.v1.payment.CreatePaymentRequest
	10, // 48: tzero.v1.payment.NetworkService.ConfirmPayout:input_type -> tzero.v1.payment.ConfirmPayoutRequest
	15, // 49: tzero.v1.payment.NetworkService.FinalizePayout:input_type -> tzero.v1.payment.FinalizePayoutRequest
	12, // 50: tzero.v1.payment.NetworkService.CompleteManualAmlCheck:input_type -> tzero.v1.payment.CompleteManualAmlCheckRequest
	4,  // 51: tzero.v1.payment.NetworkService.UpdateQuote:output_type -> tzero.v1.payment.UpdateQuoteResponse
	6,  // 52: tzero.v1.payment.NetworkService.GetQuote:output_type -> tzero.v1.payment.GetQuoteResponse
	9,  // 53: tzero.v1.payment.NetworkService.CreatePayment:output_type -> tzero.v1.payment.CreatePaymentResponse
	11, // 54: tzero.v1.payment.NetworkService.ConfirmPayout:output_type -> tzero.v1.payment.ConfirmPayoutResponse
	16, // 55: tzero.v1.payment.NetworkService.FinalizePayout:output_type -> tzero.v1.payment.FinalizePayoutResponse
	13, // 56: tzero.v1.payment.NetworkService.CompleteManualAmlCheck:output_type -> tzero.v1.payment.CompleteManualAmlCheckResponse
	51, // [51:57] is the sub-list for method output_type
	45, // [45:51] is the sub-list for method input_type
	45, // [45:45] is the sub-list for extension type_name
	45, // [45:45] is the sub-list for extension extendee
	0,  // [0:45] is the sub-list for field type_name
}

func init() { file_tzero_v1_payment_network_proto_init() }
func file_tzero_v1_payment_network_proto_init() {
	if File_tzero_v1_payment_network_proto != nil {
		return
	}
	file_tzero_v1_payment_network_proto_msgTypes[3].OneofWrappers = []any{
		(*GetQuoteResponse_Success_)(nil),
		(*GetQuoteResponse_Failure_)(nil),
	}
	file_tzero_v1_payment_network_proto_msgTypes[4].OneofWrappers = []any{}
	file_tzero_v1_payment_network_proto_msgTypes[6].OneofWrappers = []any{
		(*CreatePaymentResponse_Accepted_)(nil),
		(*CreatePaymentResponse_SettlementRequired_)(nil),
		(*CreatePaymentResponse_Failure_)(nil),
	}
	file_tzero_v1_payment_network_proto_msgTypes[7].OneofWrappers = []any{}
	file_tzero_v1_payment_network_proto_msgTypes[9].OneofWrappers = []any{
		(*CompleteManualAmlCheckRequest_Approved_)(nil),
		(*CompleteManualAmlCheckRequest_Rejected_)(nil),
	}
	file_tzero_v1_payment_network_proto_msgTypes[10].OneofWrappers = []any{
		(*CompleteManualAmlCheckResponse_Approved_)(nil),
		(*CompleteManualAmlCheckResponse_Rejected_)(nil),
	}
	file_tzero_v1_payment_network_proto_msgTypes[11].OneofWrappers = []any{
		(*PaymentAmount_PayOutAmount)(nil),
		(*PaymentAmount_SettlementAmount)(nil),
	}
	file_tzero_v1_payment_network_proto_msgTypes[12].OneofWrappers = []any{
		(*FinalizePayoutRequest_Success_)(nil),
		(*FinalizePayoutRequest_Failure_)(nil),
	}
	file_tzero_v1_payment_network_proto_msgTypes[26].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tzero_v1_payment_network_proto_rawDesc), len(file_tzero_v1_payment_network_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tzero_v1_payment_network_proto_goTypes,
		DependencyIndexes: file_tzero_v1_payment_network_proto_depIdxs,
		EnumInfos:         file_tzero_v1_payment_network_proto_enumTypes,
		MessageInfos:      file_tzero_v1_payment_network_proto_msgTypes,
	}.Build()
	File_tzero_v1_payment_network_proto = out.File
	file_tzero_v1_payment_network_proto_goTypes = nil
	file_tzero_v1_payment_network_proto_depIdxs = nil
}
