// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tzero/v1/payment/provider.proto

package payment

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	ivms "github.com/t-0-network/provider-sdk-go/api/ivms101/v1/ivms"
	common "github.com/t-0-network/provider-sdk-go/api/tzero/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppendLedgerEntriesRequest_AccountType int32

const (
	AppendLedgerEntriesRequest_ACCOUNT_TYPE_UNSPECIFIED    AppendLedgerEntriesRequest_AccountType = 0
	AppendLedgerEntriesRequest_ACCOUNT_TYPE_BALANCE        AppendLedgerEntriesRequest_AccountType = 20
	AppendLedgerEntriesRequest_ACCOUNT_TYPE_PAY_IN         AppendLedgerEntriesRequest_AccountType = 40
	AppendLedgerEntriesRequest_ACCOUNT_TYPE_PAY_OUT        AppendLedgerEntriesRequest_AccountType = 50
	AppendLedgerEntriesRequest_ACCOUNT_TYPE_FEE_EXPENSE    AppendLedgerEntriesRequest_AccountType = 60 // Reflects the fees that the provider has to pay for the services provided by the network.
	AppendLedgerEntriesRequest_ACCOUNT_TYPE_SETTLEMENT_IN  AppendLedgerEntriesRequest_AccountType = 80
	AppendLedgerEntriesRequest_ACCOUNT_TYPE_SETTLEMENT_OUT AppendLedgerEntriesRequest_AccountType = 90
)

// Enum value maps for AppendLedgerEntriesRequest_AccountType.
var (
	AppendLedgerEntriesRequest_AccountType_name = map[int32]string{
		0:  "ACCOUNT_TYPE_UNSPECIFIED",
		20: "ACCOUNT_TYPE_BALANCE",
		40: "ACCOUNT_TYPE_PAY_IN",
		50: "ACCOUNT_TYPE_PAY_OUT",
		60: "ACCOUNT_TYPE_FEE_EXPENSE",
		80: "ACCOUNT_TYPE_SETTLEMENT_IN",
		90: "ACCOUNT_TYPE_SETTLEMENT_OUT",
	}
	AppendLedgerEntriesRequest_AccountType_value = map[string]int32{
		"ACCOUNT_TYPE_UNSPECIFIED":    0,
		"ACCOUNT_TYPE_BALANCE":        20,
		"ACCOUNT_TYPE_PAY_IN":         40,
		"ACCOUNT_TYPE_PAY_OUT":        50,
		"ACCOUNT_TYPE_FEE_EXPENSE":    60,
		"ACCOUNT_TYPE_SETTLEMENT_IN":  80,
		"ACCOUNT_TYPE_SETTLEMENT_OUT": 90,
	}
)

func (x AppendLedgerEntriesRequest_AccountType) Enum() *AppendLedgerEntriesRequest_AccountType {
	p := new(AppendLedgerEntriesRequest_AccountType)
	*p = x
	return p
}

func (x AppendLedgerEntriesRequest_AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppendLedgerEntriesRequest_AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_tzero_v1_payment_provider_proto_enumTypes[0].Descriptor()
}

func (AppendLedgerEntriesRequest_AccountType) Type() protoreflect.EnumType {
	return &file_tzero_v1_payment_provider_proto_enumTypes[0]
}

func (x AppendLedgerEntriesRequest_AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppendLedgerEntriesRequest_AccountType.Descriptor instead.
func (AppendLedgerEntriesRequest_AccountType) EnumDescriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{0, 0}
}

type PayoutResponse_Failed_Reason int32

const (
	PayoutResponse_Failed_REASON_UNSPECIFIED PayoutResponse_Failed_Reason = 0
)

// Enum value maps for PayoutResponse_Failed_Reason.
var (
	PayoutResponse_Failed_Reason_name = map[int32]string{
		0: "REASON_UNSPECIFIED",
	}
	PayoutResponse_Failed_Reason_value = map[string]int32{
		"REASON_UNSPECIFIED": 0,
	}
)

func (x PayoutResponse_Failed_Reason) Enum() *PayoutResponse_Failed_Reason {
	p := new(PayoutResponse_Failed_Reason)
	*p = x
	return p
}

func (x PayoutResponse_Failed_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayoutResponse_Failed_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_tzero_v1_payment_provider_proto_enumTypes[1].Descriptor()
}

func (PayoutResponse_Failed_Reason) Type() protoreflect.EnumType {
	return &file_tzero_v1_payment_provider_proto_enumTypes[1]
}

func (x PayoutResponse_Failed_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayoutResponse_Failed_Reason.Descriptor instead.
func (PayoutResponse_Failed_Reason) EnumDescriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{3, 2, 0}
}

type UpdatePaymentRequest_Failed_Reason int32

const (
	UpdatePaymentRequest_Failed_REASON_UNSPECIFIED                       UpdatePaymentRequest_Failed_Reason = 0
	UpdatePaymentRequest_Failed_REASON_NO_QUOTE_AFTER_AML_APPROVAL       UpdatePaymentRequest_Failed_Reason = 1 // AML review completed, but the pay-out provider no longer has a valid quote available.
	UpdatePaymentRequest_Failed_REASON_QUOTE_REJECTED_AFTER_AML_APPROVAL UpdatePaymentRequest_Failed_Reason = 2 // AML review completed and a new quote was required, but the pay-in provider rejected the updated quote (e.g. due to rate change after AML delay).
	UpdatePaymentRequest_Failed_REASON_AML_RISK_CHECK_FAILED             UpdatePaymentRequest_Failed_Reason = 3 // Payment was rejected by the pay-out provider because the AML / risk checks failed.
)

// Enum value maps for UpdatePaymentRequest_Failed_Reason.
var (
	UpdatePaymentRequest_Failed_Reason_name = map[int32]string{
		0: "REASON_UNSPECIFIED",
		1: "REASON_NO_QUOTE_AFTER_AML_APPROVAL",
		2: "REASON_QUOTE_REJECTED_AFTER_AML_APPROVAL",
		3: "REASON_AML_RISK_CHECK_FAILED",
	}
	UpdatePaymentRequest_Failed_Reason_value = map[string]int32{
		"REASON_UNSPECIFIED":                       0,
		"REASON_NO_QUOTE_AFTER_AML_APPROVAL":       1,
		"REASON_QUOTE_REJECTED_AFTER_AML_APPROVAL": 2,
		"REASON_AML_RISK_CHECK_FAILED":             3,
	}
)

func (x UpdatePaymentRequest_Failed_Reason) Enum() *UpdatePaymentRequest_Failed_Reason {
	p := new(UpdatePaymentRequest_Failed_Reason)
	*p = x
	return p
}

func (x UpdatePaymentRequest_Failed_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdatePaymentRequest_Failed_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_tzero_v1_payment_provider_proto_enumTypes[2].Descriptor()
}

func (UpdatePaymentRequest_Failed_Reason) Type() protoreflect.EnumType {
	return &file_tzero_v1_payment_provider_proto_enumTypes[2]
}

func (x UpdatePaymentRequest_Failed_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdatePaymentRequest_Failed_Reason.Descriptor instead.
func (UpdatePaymentRequest_Failed_Reason) EnumDescriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{4, 1, 0}
}

type AppendLedgerEntriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// This is a list of transactions that were appended to the ledger of the provider.
	// The transaction_id should be used to identify the transaction and ensure that it is processed only once.
	Transactions  []*AppendLedgerEntriesRequest_Transaction `protobuf:"bytes,20,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendLedgerEntriesRequest) Reset() {
	*x = AppendLedgerEntriesRequest{}
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendLedgerEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendLedgerEntriesRequest) ProtoMessage() {}

func (x *AppendLedgerEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendLedgerEntriesRequest.ProtoReflect.Descriptor instead.
func (*AppendLedgerEntriesRequest) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{0}
}

func (x *AppendLedgerEntriesRequest) GetTransactions() []*AppendLedgerEntriesRequest_Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type AppendLedgerEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendLedgerEntriesResponse) Reset() {
	*x = AppendLedgerEntriesResponse{}
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendLedgerEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendLedgerEntriesResponse) ProtoMessage() {}

func (x *AppendLedgerEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendLedgerEntriesResponse.ProtoReflect.Descriptor instead.
func (*AppendLedgerEntriesResponse) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{1}
}

type PayoutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// payment id assigned by the network (provider should store this id to provide details in UpdatePayout later)
	PaymentId uint64 `protobuf:"varint,10,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	// *
	// payout_id is deprecated now, since it's 1->1 mapping between payout_id and payment_id
	//
	// Deprecated: Marked as deprecated in tzero/v1/payment/provider.proto.
	PayoutId uint64 `protobuf:"varint,20,opt,name=payout_id,json=payoutId,proto3" json:"payout_id,omitempty"`
	// *
	// currency of the payout (participant could support multiple currencies)
	// This is the currency in which the payout should be made.
	Currency string `protobuf:"bytes,30,opt,name=currency,proto3" json:"currency,omitempty"`
	// *
	// client quote id of the quote used for this payout (the provider provides the quote IDs in the UpdateQuote rpc)
	// This is the identifier of the quote that was used to calculate the payout amount.
	ClientQuoteId string `protobuf:"bytes,40,opt,name=client_quote_id,json=clientQuoteId,proto3" json:"client_quote_id,omitempty"`
	// *
	// amount in currency of the payout
	// This is the amount that should be paid out to the recipient.
	Amount *common.Decimal `protobuf:"bytes,50,opt,name=amount,proto3" json:"amount,omitempty"`
	// *
	// payout_method is the payment method for the payout, e.g. bank transfer, crypto transfer, etc.
	// This is used to specify how the payout should be made.
	PayoutDetails *common.PaymentDetails `protobuf:"bytes,60,opt,name=payout_details,json=payoutDetails,proto3,oneof" json:"payout_details,omitempty"`
	// *
	// Pay-in provider id which initiated the pay out.
	PayInProviderId uint32                        `protobuf:"varint,80,opt,name=pay_in_provider_id,json=payInProviderId,proto3" json:"pay_in_provider_id,omitempty"`
	TravelRuleData  *PayoutRequest_TravelRuleData `protobuf:"bytes,200,opt,name=travel_rule_data,json=travelRuleData,proto3,oneof" json:"travel_rule_data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PayoutRequest) Reset() {
	*x = PayoutRequest{}
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayoutRequest) ProtoMessage() {}

func (x *PayoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayoutRequest.ProtoReflect.Descriptor instead.
func (*PayoutRequest) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{2}
}

func (x *PayoutRequest) GetPaymentId() uint64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

// Deprecated: Marked as deprecated in tzero/v1/payment/provider.proto.
func (x *PayoutRequest) GetPayoutId() uint64 {
	if x != nil {
		return x.PayoutId
	}
	return 0
}

func (x *PayoutRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PayoutRequest) GetClientQuoteId() string {
	if x != nil {
		return x.ClientQuoteId
	}
	return ""
}

func (x *PayoutRequest) GetAmount() *common.Decimal {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *PayoutRequest) GetPayoutDetails() *common.PaymentDetails {
	if x != nil {
		return x.PayoutDetails
	}
	return nil
}

func (x *PayoutRequest) GetPayInProviderId() uint32 {
	if x != nil {
		return x.PayInProviderId
	}
	return 0
}

func (x *PayoutRequest) GetTravelRuleData() *PayoutRequest_TravelRuleData {
	if x != nil {
		return x.TravelRuleData
	}
	return nil
}

type PayoutResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*PayoutResponse_Accepted_
	//	*PayoutResponse_Failed_
	//	*PayoutResponse_ManualAmlCheck_
	Result        isPayoutResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayoutResponse) Reset() {
	*x = PayoutResponse{}
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayoutResponse) ProtoMessage() {}

func (x *PayoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayoutResponse.ProtoReflect.Descriptor instead.
func (*PayoutResponse) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{3}
}

func (x *PayoutResponse) GetResult() isPayoutResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *PayoutResponse) GetAccepted() *PayoutResponse_Accepted {
	if x != nil {
		if x, ok := x.Result.(*PayoutResponse_Accepted_); ok {
			return x.Accepted
		}
	}
	return nil
}

func (x *PayoutResponse) GetFailed() *PayoutResponse_Failed {
	if x != nil {
		if x, ok := x.Result.(*PayoutResponse_Failed_); ok {
			return x.Failed
		}
	}
	return nil
}

func (x *PayoutResponse) GetManualAmlCheck() *PayoutResponse_ManualAmlCheck {
	if x != nil {
		if x, ok := x.Result.(*PayoutResponse_ManualAmlCheck_); ok {
			return x.ManualAmlCheck
		}
	}
	return nil
}

type isPayoutResponse_Result interface {
	isPayoutResponse_Result()
}

type PayoutResponse_Accepted_ struct {
	// *
	// Accepted response - means the payout was accepted by the pay-out provider and pay-out provider is obligated to
	// make a pay-out.
	Accepted *PayoutResponse_Accepted `protobuf:"bytes,20,opt,name=accepted,proto3,oneof"`
}

type PayoutResponse_Failed_ struct {
	// *
	// Failure response - means the payout was not executed successfully, e.g. the payout provider could not process the payout.
	Failed *PayoutResponse_Failed `protobuf:"bytes,30,opt,name=failed,proto3,oneof"`
}

type PayoutResponse_ManualAmlCheck_ struct {
	// *
	// Manual AML check required - means the payout provider requires additional Anti-Money Laundering (AML)
	// verification before the payment can proceed. The pay-out provider will need to perform the manual AML check
	// and then call CompleteManualAmlCheck rpc with the result of the check.
	ManualAmlCheck *PayoutResponse_ManualAmlCheck `protobuf:"bytes,40,opt,name=manual_aml_check,json=manualAmlCheck,proto3,oneof"`
}

func (*PayoutResponse_Accepted_) isPayoutResponse_Result() {}

func (*PayoutResponse_Failed_) isPayoutResponse_Result() {}

func (*PayoutResponse_ManualAmlCheck_) isPayoutResponse_Result() {}

type UpdatePaymentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// payment_id is a payment id in the T-0 network.
	PaymentId uint64 `protobuf:"varint,5,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	// *
	// payment_client_id is a payment id assigned by the client, this is the same id that was provided in the CreatePaymentRequest.
	PaymentClientId string `protobuf:"bytes,10,opt,name=payment_client_id,json=paymentClientId,proto3" json:"payment_client_id,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*UpdatePaymentRequest_Accepted_
	//	*UpdatePaymentRequest_Failed_
	//	*UpdatePaymentRequest_Confirmed_
	//	*UpdatePaymentRequest_ManualAmlCheck_
	Result        isUpdatePaymentRequest_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentRequest) Reset() {
	*x = UpdatePaymentRequest{}
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentRequest) ProtoMessage() {}

func (x *UpdatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePaymentRequest) GetPaymentId() uint64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *UpdatePaymentRequest) GetPaymentClientId() string {
	if x != nil {
		return x.PaymentClientId
	}
	return ""
}

func (x *UpdatePaymentRequest) GetResult() isUpdatePaymentRequest_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UpdatePaymentRequest) GetAccepted() *UpdatePaymentRequest_Accepted {
	if x != nil {
		if x, ok := x.Result.(*UpdatePaymentRequest_Accepted_); ok {
			return x.Accepted
		}
	}
	return nil
}

func (x *UpdatePaymentRequest) GetFailed() *UpdatePaymentRequest_Failed {
	if x != nil {
		if x, ok := x.Result.(*UpdatePaymentRequest_Failed_); ok {
			return x.Failed
		}
	}
	return nil
}

func (x *UpdatePaymentRequest) GetConfirmed() *UpdatePaymentRequest_Confirmed {
	if x != nil {
		if x, ok := x.Result.(*UpdatePaymentRequest_Confirmed_); ok {
			return x.Confirmed
		}
	}
	return nil
}

func (x *UpdatePaymentRequest) GetManualAmlCheck() *UpdatePaymentRequest_ManualAmlCheck {
	if x != nil {
		if x, ok := x.Result.(*UpdatePaymentRequest_ManualAmlCheck_); ok {
			return x.ManualAmlCheck
		}
	}
	return nil
}

type isUpdatePaymentRequest_Result interface {
	isUpdatePaymentRequest_Result()
}

type UpdatePaymentRequest_Accepted_ struct {
	// *
	// Accepted response - means the payout was accepted by the pay-out provider and pay-out provider is obligated to
	// make a pay-out.
	Accepted *UpdatePaymentRequest_Accepted `protobuf:"bytes,20,opt,name=accepted,proto3,oneof"`
}

type UpdatePaymentRequest_Failed_ struct {
	// *
	// Payment failed and would not be retried.
	Failed *UpdatePaymentRequest_Failed `protobuf:"bytes,30,opt,name=failed,proto3,oneof"`
}

type UpdatePaymentRequest_Confirmed_ struct {
	// *
	// Confirmed response - final state meaning the payout was executed successfully and the payment is now complete.
	// This happens when the payout is successfully processed by the payout provider, and the payment was made to the recipient.
	Confirmed *UpdatePaymentRequest_Confirmed `protobuf:"bytes,40,opt,name=confirmed,proto3,oneof"`
}

type UpdatePaymentRequest_ManualAmlCheck_ struct {
	// In case of manual AML check, pay-out provider needs to perform additional checks and then call CompleteManualAmlCheck
	// rpc with the result of the check.
	ManualAmlCheck *UpdatePaymentRequest_ManualAmlCheck `protobuf:"bytes,50,opt,name=manual_aml_check,json=manualAmlCheck,proto3,oneof"`
}

func (*UpdatePaymentRequest_Accepted_) isUpdatePaymentRequest_Result() {}

func (*UpdatePaymentRequest_Failed_) isUpdatePaymentRequest_Result() {}

func (*UpdatePaymentRequest_Confirmed_) isUpdatePaymentRequest_Result() {}

func (*UpdatePaymentRequest_ManualAmlCheck_) isUpdatePaymentRequest_Result() {}

type UpdatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentResponse) Reset() {
	*x = UpdatePaymentResponse{}
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentResponse) ProtoMessage() {}

func (x *UpdatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentResponse.ProtoReflect.Descriptor instead.
func (*UpdatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{5}
}

// All the amounts are in USD
type UpdateLimitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// can contain one or more Limit messages, each representing a credit limit for a specific counterparty provider.
	Limits        []*UpdateLimitRequest_Limit `protobuf:"bytes,10,rep,name=limits,proto3" json:"limits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLimitRequest) Reset() {
	*x = UpdateLimitRequest{}
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLimitRequest) ProtoMessage() {}

func (x *UpdateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLimitRequest.ProtoReflect.Descriptor instead.
func (*UpdateLimitRequest) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateLimitRequest) GetLimits() []*UpdateLimitRequest_Limit {
	if x != nil {
		return x.Limits
	}
	return nil
}

// *
// Empty message - means no response is needed.
type UpdateLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLimitResponse) Reset() {
	*x = UpdateLimitResponse{}
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLimitResponse) ProtoMessage() {}

func (x *UpdateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLimitResponse.ProtoReflect.Descriptor instead.
func (*UpdateLimitResponse) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{7}
}

type ApprovePaymentQuoteRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PaymentId        uint64                 `protobuf:"varint,10,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	PayOutQuoteId    int64                  `protobuf:"varint,20,opt,name=pay_out_quote_id,json=payOutQuoteId,proto3" json:"pay_out_quote_id,omitempty"`
	PayOutRate       *common.Decimal        `protobuf:"bytes,30,opt,name=pay_out_rate,json=payOutRate,proto3" json:"pay_out_rate,omitempty"`
	PayOutAmount     *common.Decimal        `protobuf:"bytes,40,opt,name=pay_out_amount,json=payOutAmount,proto3" json:"pay_out_amount,omitempty"`
	SettlementAmount *common.Decimal        `protobuf:"bytes,50,opt,name=settlement_amount,json=settlementAmount,proto3" json:"settlement_amount,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ApprovePaymentQuoteRequest) Reset() {
	*x = ApprovePaymentQuoteRequest{}
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovePaymentQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovePaymentQuoteRequest) ProtoMessage() {}

func (x *ApprovePaymentQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovePaymentQuoteRequest.ProtoReflect.Descriptor instead.
func (*ApprovePaymentQuoteRequest) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{8}
}

func (x *ApprovePaymentQuoteRequest) GetPaymentId() uint64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *ApprovePaymentQuoteRequest) GetPayOutQuoteId() int64 {
	if x != nil {
		return x.PayOutQuoteId
	}
	return 0
}

func (x *ApprovePaymentQuoteRequest) GetPayOutRate() *common.Decimal {
	if x != nil {
		return x.PayOutRate
	}
	return nil
}

func (x *ApprovePaymentQuoteRequest) GetPayOutAmount() *common.Decimal {
	if x != nil {
		return x.PayOutAmount
	}
	return nil
}

func (x *ApprovePaymentQuoteRequest) GetSettlementAmount() *common.Decimal {
	if x != nil {
		return x.SettlementAmount
	}
	return nil
}

type ApprovePaymentQuoteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ApprovePaymentQuoteResponse_Accepted_
	//	*ApprovePaymentQuoteResponse_Rejected_
	Result        isApprovePaymentQuoteResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovePaymentQuoteResponse) Reset() {
	*x = ApprovePaymentQuoteResponse{}
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovePaymentQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovePaymentQuoteResponse) ProtoMessage() {}

func (x *ApprovePaymentQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovePaymentQuoteResponse.ProtoReflect.Descriptor instead.
func (*ApprovePaymentQuoteResponse) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{9}
}

func (x *ApprovePaymentQuoteResponse) GetResult() isApprovePaymentQuoteResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ApprovePaymentQuoteResponse) GetAccepted() *ApprovePaymentQuoteResponse_Accepted {
	if x != nil {
		if x, ok := x.Result.(*ApprovePaymentQuoteResponse_Accepted_); ok {
			return x.Accepted
		}
	}
	return nil
}

func (x *ApprovePaymentQuoteResponse) GetRejected() *ApprovePaymentQuoteResponse_Rejected {
	if x != nil {
		if x, ok := x.Result.(*ApprovePaymentQuoteResponse_Rejected_); ok {
			return x.Rejected
		}
	}
	return nil
}

type isApprovePaymentQuoteResponse_Result interface {
	isApprovePaymentQuoteResponse_Result()
}

type ApprovePaymentQuoteResponse_Accepted_ struct {
	Accepted *ApprovePaymentQuoteResponse_Accepted `protobuf:"bytes,10,opt,name=accepted,proto3,oneof"`
}

type ApprovePaymentQuoteResponse_Rejected_ struct {
	Rejected *ApprovePaymentQuoteResponse_Rejected `protobuf:"bytes,20,opt,name=rejected,proto3,oneof"`
}

func (*ApprovePaymentQuoteResponse_Accepted_) isApprovePaymentQuoteResponse_Result() {}

func (*ApprovePaymentQuoteResponse_Rejected_) isApprovePaymentQuoteResponse_Result() {}

type AppendLedgerEntriesRequest_Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// transaction_id is an incrementally growing identifier for the transaction.
	// It could have gaps and could be out of order, but it is unique for each transaction.
	TransactionId uint64 `protobuf:"varint,10,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	// *
	// entries is a list of ledger entries that were appended to the ledger of the provider.
	// Each entry represents a financial event that occurred in the provider's accounts.
	Entries []*AppendLedgerEntriesRequest_LedgerEntry `protobuf:"bytes,30,rep,name=entries,proto3" json:"entries,omitempty"`
	// *
	// transaction_details is a oneof field that contains details about the transaction.
	// It can be one of the following: PayIn, PayoutReservation, Payout, ProviderSettlement, FeeSettlement, PayoutReservationRelease.
	//
	// Types that are valid to be assigned to TransactionDetails:
	//
	//	*AppendLedgerEntriesRequest_Transaction_Payout_
	//	*AppendLedgerEntriesRequest_Transaction_ProviderSettlement_
	//	*AppendLedgerEntriesRequest_Transaction_FeeSettlement_
	TransactionDetails isAppendLedgerEntriesRequest_Transaction_TransactionDetails `protobuf_oneof:"transaction_details"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AppendLedgerEntriesRequest_Transaction) Reset() {
	*x = AppendLedgerEntriesRequest_Transaction{}
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendLedgerEntriesRequest_Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendLedgerEntriesRequest_Transaction) ProtoMessage() {}

func (x *AppendLedgerEntriesRequest_Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendLedgerEntriesRequest_Transaction.ProtoReflect.Descriptor instead.
func (*AppendLedgerEntriesRequest_Transaction) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AppendLedgerEntriesRequest_Transaction) GetTransactionId() uint64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *AppendLedgerEntriesRequest_Transaction) GetEntries() []*AppendLedgerEntriesRequest_LedgerEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AppendLedgerEntriesRequest_Transaction) GetTransactionDetails() isAppendLedgerEntriesRequest_Transaction_TransactionDetails {
	if x != nil {
		return x.TransactionDetails
	}
	return nil
}

func (x *AppendLedgerEntriesRequest_Transaction) GetPayout() *AppendLedgerEntriesRequest_Transaction_Payout {
	if x != nil {
		if x, ok := x.TransactionDetails.(*AppendLedgerEntriesRequest_Transaction_Payout_); ok {
			return x.Payout
		}
	}
	return nil
}

func (x *AppendLedgerEntriesRequest_Transaction) GetProviderSettlement() *AppendLedgerEntriesRequest_Transaction_ProviderSettlement {
	if x != nil {
		if x, ok := x.TransactionDetails.(*AppendLedgerEntriesRequest_Transaction_ProviderSettlement_); ok {
			return x.ProviderSettlement
		}
	}
	return nil
}

func (x *AppendLedgerEntriesRequest_Transaction) GetFeeSettlement() *AppendLedgerEntriesRequest_Transaction_FeeSettlement {
	if x != nil {
		if x, ok := x.TransactionDetails.(*AppendLedgerEntriesRequest_Transaction_FeeSettlement_); ok {
			return x.FeeSettlement
		}
	}
	return nil
}

type isAppendLedgerEntriesRequest_Transaction_TransactionDetails interface {
	isAppendLedgerEntriesRequest_Transaction_TransactionDetails()
}

type AppendLedgerEntriesRequest_Transaction_Payout_ struct {
	Payout *AppendLedgerEntriesRequest_Transaction_Payout `protobuf:"bytes,130,opt,name=payout,proto3,oneof"`
}

type AppendLedgerEntriesRequest_Transaction_ProviderSettlement_ struct {
	ProviderSettlement *AppendLedgerEntriesRequest_Transaction_ProviderSettlement `protobuf:"bytes,140,opt,name=provider_settlement,json=providerSettlement,proto3,oneof"`
}

type AppendLedgerEntriesRequest_Transaction_FeeSettlement_ struct {
	FeeSettlement *AppendLedgerEntriesRequest_Transaction_FeeSettlement `protobuf:"bytes,150,opt,name=fee_settlement,json=feeSettlement,proto3,oneof"`
}

func (*AppendLedgerEntriesRequest_Transaction_Payout_) isAppendLedgerEntriesRequest_Transaction_TransactionDetails() {
}

func (*AppendLedgerEntriesRequest_Transaction_ProviderSettlement_) isAppendLedgerEntriesRequest_Transaction_TransactionDetails() {
}

func (*AppendLedgerEntriesRequest_Transaction_FeeSettlement_) isAppendLedgerEntriesRequest_Transaction_TransactionDetails() {
}

type AppendLedgerEntriesRequest_LedgerEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1 is network account, others are ids of participants
	AccountOwnerId uint32 `protobuf:"varint,10,opt,name=account_owner_id,json=accountOwnerId,proto3" json:"account_owner_id,omitempty"`
	// *
	// account_type is the type of the account that the entry belongs to.
	// It is used to categorize the entries and understand the nature of the financial event.
	AccountType AppendLedgerEntriesRequest_AccountType `protobuf:"varint,20,opt,name=account_type,json=accountType,proto3,enum=tzero.v1.payment.AppendLedgerEntriesRequest_AccountType" json:"account_type,omitempty"`
	// *
	// debit is the amount that was debited from the account.
	// If the entry is a credit, this field should be 0.
	Debit *common.Decimal `protobuf:"bytes,40,opt,name=debit,proto3" json:"debit,omitempty"`
	// *
	// credit is the amount that was credited to the account.
	// If the entry is a debit, this field should be 0.
	Credit        *common.Decimal `protobuf:"bytes,50,opt,name=credit,proto3" json:"credit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendLedgerEntriesRequest_LedgerEntry) Reset() {
	*x = AppendLedgerEntriesRequest_LedgerEntry{}
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendLedgerEntriesRequest_LedgerEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendLedgerEntriesRequest_LedgerEntry) ProtoMessage() {}

func (x *AppendLedgerEntriesRequest_LedgerEntry) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendLedgerEntriesRequest_LedgerEntry.ProtoReflect.Descriptor instead.
func (*AppendLedgerEntriesRequest_LedgerEntry) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{0, 1}
}

func (x *AppendLedgerEntriesRequest_LedgerEntry) GetAccountOwnerId() uint32 {
	if x != nil {
		return x.AccountOwnerId
	}
	return 0
}

func (x *AppendLedgerEntriesRequest_LedgerEntry) GetAccountType() AppendLedgerEntriesRequest_AccountType {
	if x != nil {
		return x.AccountType
	}
	return AppendLedgerEntriesRequest_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *AppendLedgerEntriesRequest_LedgerEntry) GetDebit() *common.Decimal {
	if x != nil {
		return x.Debit
	}
	return nil
}

func (x *AppendLedgerEntriesRequest_LedgerEntry) GetCredit() *common.Decimal {
	if x != nil {
		return x.Credit
	}
	return nil
}

type AppendLedgerEntriesRequest_Transaction_Payout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     uint64                 `protobuf:"varint,10,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendLedgerEntriesRequest_Transaction_Payout) Reset() {
	*x = AppendLedgerEntriesRequest_Transaction_Payout{}
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendLedgerEntriesRequest_Transaction_Payout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendLedgerEntriesRequest_Transaction_Payout) ProtoMessage() {}

func (x *AppendLedgerEntriesRequest_Transaction_Payout) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendLedgerEntriesRequest_Transaction_Payout.ProtoReflect.Descriptor instead.
func (*AppendLedgerEntriesRequest_Transaction_Payout) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *AppendLedgerEntriesRequest_Transaction_Payout) GetPaymentId() uint64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

type AppendLedgerEntriesRequest_Transaction_ProviderSettlement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SettlementId  uint64                 `protobuf:"varint,10,opt,name=settlement_id,json=settlementId,proto3" json:"settlement_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendLedgerEntriesRequest_Transaction_ProviderSettlement) Reset() {
	*x = AppendLedgerEntriesRequest_Transaction_ProviderSettlement{}
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendLedgerEntriesRequest_Transaction_ProviderSettlement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendLedgerEntriesRequest_Transaction_ProviderSettlement) ProtoMessage() {}

func (x *AppendLedgerEntriesRequest_Transaction_ProviderSettlement) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendLedgerEntriesRequest_Transaction_ProviderSettlement.ProtoReflect.Descriptor instead.
func (*AppendLedgerEntriesRequest_Transaction_ProviderSettlement) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *AppendLedgerEntriesRequest_Transaction_ProviderSettlement) GetSettlementId() uint64 {
	if x != nil {
		return x.SettlementId
	}
	return 0
}

type AppendLedgerEntriesRequest_Transaction_FeeSettlement struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FeeSettlementId uint64                 `protobuf:"varint,10,opt,name=fee_settlement_id,json=feeSettlementId,proto3" json:"fee_settlement_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AppendLedgerEntriesRequest_Transaction_FeeSettlement) Reset() {
	*x = AppendLedgerEntriesRequest_Transaction_FeeSettlement{}
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendLedgerEntriesRequest_Transaction_FeeSettlement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendLedgerEntriesRequest_Transaction_FeeSettlement) ProtoMessage() {}

func (x *AppendLedgerEntriesRequest_Transaction_FeeSettlement) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendLedgerEntriesRequest_Transaction_FeeSettlement.ProtoReflect.Descriptor instead.
func (*AppendLedgerEntriesRequest_Transaction_FeeSettlement) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{0, 0, 2}
}

func (x *AppendLedgerEntriesRequest_Transaction_FeeSettlement) GetFeeSettlementId() uint64 {
	if x != nil {
		return x.FeeSettlementId
	}
	return 0
}

type PayoutRequest_TravelRuleData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the natural or legal person that requests payment with originating provider
	Originator []*ivms.Person `protobuf:"bytes,10,rep,name=originator,proto3" json:"originator,omitempty"`
	// the natural or legal person or legal arrangement who is identified
	// by the originator as the receiver of the requested payment.
	Beneficiary        []*ivms.Person `protobuf:"bytes,20,rep,name=beneficiary,proto3" json:"beneficiary,omitempty"`
	OriginatorProvider *ivms.Person   `protobuf:"bytes,30,opt,name=originator_provider,json=originatorProvider,proto3,oneof" json:"originator_provider,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PayoutRequest_TravelRuleData) Reset() {
	*x = PayoutRequest_TravelRuleData{}
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayoutRequest_TravelRuleData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayoutRequest_TravelRuleData) ProtoMessage() {}

func (x *PayoutRequest_TravelRuleData) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayoutRequest_TravelRuleData.ProtoReflect.Descriptor instead.
func (*PayoutRequest_TravelRuleData) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{2, 0}
}

func (x *PayoutRequest_TravelRuleData) GetOriginator() []*ivms.Person {
	if x != nil {
		return x.Originator
	}
	return nil
}

func (x *PayoutRequest_TravelRuleData) GetBeneficiary() []*ivms.Person {
	if x != nil {
		return x.Beneficiary
	}
	return nil
}

func (x *PayoutRequest_TravelRuleData) GetOriginatorProvider() *ivms.Person {
	if x != nil {
		return x.OriginatorProvider
	}
	return nil
}

type PayoutResponse_Accepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayoutResponse_Accepted) Reset() {
	*x = PayoutResponse_Accepted{}
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayoutResponse_Accepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayoutResponse_Accepted) ProtoMessage() {}

func (x *PayoutResponse_Accepted) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayoutResponse_Accepted.ProtoReflect.Descriptor instead.
func (*PayoutResponse_Accepted) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{3, 0}
}

type PayoutResponse_ManualAmlCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayoutResponse_ManualAmlCheck) Reset() {
	*x = PayoutResponse_ManualAmlCheck{}
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayoutResponse_ManualAmlCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayoutResponse_ManualAmlCheck) ProtoMessage() {}

func (x *PayoutResponse_ManualAmlCheck) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayoutResponse_ManualAmlCheck.ProtoReflect.Descriptor instead.
func (*PayoutResponse_ManualAmlCheck) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{3, 1}
}

type PayoutResponse_Failed struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Reason        PayoutResponse_Failed_Reason `protobuf:"varint,10,opt,name=reason,proto3,enum=tzero.v1.payment.PayoutResponse_Failed_Reason" json:"reason,omitempty"`
	Details       *string                      `protobuf:"bytes,20,opt,name=details,proto3,oneof" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayoutResponse_Failed) Reset() {
	*x = PayoutResponse_Failed{}
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayoutResponse_Failed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayoutResponse_Failed) ProtoMessage() {}

func (x *PayoutResponse_Failed) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayoutResponse_Failed.ProtoReflect.Descriptor instead.
func (*PayoutResponse_Failed) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{3, 2}
}

func (x *PayoutResponse_Failed) GetReason() PayoutResponse_Failed_Reason {
	if x != nil {
		return x.Reason
	}
	return PayoutResponse_Failed_REASON_UNSPECIFIED
}

func (x *PayoutResponse_Failed) GetDetails() string {
	if x != nil && x.Details != nil {
		return *x.Details
	}
	return ""
}

type UpdatePaymentRequest_Accepted struct {
	state          protoimpl.MessageState                        `protogen:"open.v1"`
	PayoutAmount   *common.Decimal                               `protobuf:"bytes,10,opt,name=payout_amount,json=payoutAmount,proto3" json:"payout_amount,omitempty"` // amount in currency of the payout
	TravelRuleData *UpdatePaymentRequest_Accepted_TravelRuleData `protobuf:"bytes,20,opt,name=travel_rule_data,json=travelRuleData,proto3,oneof" json:"travel_rule_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdatePaymentRequest_Accepted) Reset() {
	*x = UpdatePaymentRequest_Accepted{}
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentRequest_Accepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentRequest_Accepted) ProtoMessage() {}

func (x *UpdatePaymentRequest_Accepted) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentRequest_Accepted.ProtoReflect.Descriptor instead.
func (*UpdatePaymentRequest_Accepted) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{4, 0}
}

func (x *UpdatePaymentRequest_Accepted) GetPayoutAmount() *common.Decimal {
	if x != nil {
		return x.PayoutAmount
	}
	return nil
}

func (x *UpdatePaymentRequest_Accepted) GetTravelRuleData() *UpdatePaymentRequest_Accepted_TravelRuleData {
	if x != nil {
		return x.TravelRuleData
	}
	return nil
}

type UpdatePaymentRequest_Failed struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Reason        UpdatePaymentRequest_Failed_Reason `protobuf:"varint,10,opt,name=reason,proto3,enum=tzero.v1.payment.UpdatePaymentRequest_Failed_Reason" json:"reason,omitempty"`
	Details       *string                            `protobuf:"bytes,20,opt,name=details,proto3,oneof" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentRequest_Failed) Reset() {
	*x = UpdatePaymentRequest_Failed{}
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentRequest_Failed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentRequest_Failed) ProtoMessage() {}

func (x *UpdatePaymentRequest_Failed) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentRequest_Failed.ProtoReflect.Descriptor instead.
func (*UpdatePaymentRequest_Failed) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{4, 1}
}

func (x *UpdatePaymentRequest_Failed) GetReason() UpdatePaymentRequest_Failed_Reason {
	if x != nil {
		return x.Reason
	}
	return UpdatePaymentRequest_Failed_REASON_UNSPECIFIED
}

func (x *UpdatePaymentRequest_Failed) GetDetails() string {
	if x != nil && x.Details != nil {
		return *x.Details
	}
	return ""
}

type UpdatePaymentRequest_Confirmed struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PaidOutAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=paid_out_at,json=paidOutAt,proto3" json:"paid_out_at,omitempty"` // time of the payout
	// *
	// Payment receipt might contain metadata about payment recognizable by pay-in provider.
	Receipt       *common.PaymentReceipt `protobuf:"bytes,20,opt,name=receipt,proto3,oneof" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentRequest_Confirmed) Reset() {
	*x = UpdatePaymentRequest_Confirmed{}
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentRequest_Confirmed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentRequest_Confirmed) ProtoMessage() {}

func (x *UpdatePaymentRequest_Confirmed) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentRequest_Confirmed.ProtoReflect.Descriptor instead.
func (*UpdatePaymentRequest_Confirmed) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{4, 2}
}

func (x *UpdatePaymentRequest_Confirmed) GetPaidOutAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaidOutAt
	}
	return nil
}

func (x *UpdatePaymentRequest_Confirmed) GetReceipt() *common.PaymentReceipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

type UpdatePaymentRequest_ManualAmlCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentRequest_ManualAmlCheck) Reset() {
	*x = UpdatePaymentRequest_ManualAmlCheck{}
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentRequest_ManualAmlCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentRequest_ManualAmlCheck) ProtoMessage() {}

func (x *UpdatePaymentRequest_ManualAmlCheck) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentRequest_ManualAmlCheck.ProtoReflect.Descriptor instead.
func (*UpdatePaymentRequest_ManualAmlCheck) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{4, 3}
}

type UpdatePaymentRequest_Accepted_TravelRuleData struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	BeneficiaryProvider *ivms.Person           `protobuf:"bytes,10,opt,name=beneficiary_provider,json=beneficiaryProvider,proto3,oneof" json:"beneficiary_provider,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdatePaymentRequest_Accepted_TravelRuleData) Reset() {
	*x = UpdatePaymentRequest_Accepted_TravelRuleData{}
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentRequest_Accepted_TravelRuleData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentRequest_Accepted_TravelRuleData) ProtoMessage() {}

func (x *UpdatePaymentRequest_Accepted_TravelRuleData) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentRequest_Accepted_TravelRuleData.ProtoReflect.Descriptor instead.
func (*UpdatePaymentRequest_Accepted_TravelRuleData) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{4, 0, 0}
}

func (x *UpdatePaymentRequest_Accepted_TravelRuleData) GetBeneficiaryProvider() *ivms.Person {
	if x != nil {
		return x.BeneficiaryProvider
	}
	return nil
}

type UpdateLimitRequest_Limit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Incrementally growing for the provider - same as in Ledger.
	Version int64 `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"`
	// *
	// the Id of the counterparty provider, e.g. the provider that is providing the credit limit.
	// It's usually the payOut provider, which provides the credit line to the payIn provider.
	CounterpartId int32 `protobuf:"varint,15,opt,name=counterpart_id,json=counterpartId,proto3" json:"counterpart_id,omitempty"`
	// *
	// payout_limit = credit_limit - credit_usage - reserve, negative value means credit limit is exceeded,
	// e.g. if counterparty decreased credit limit
	PayoutLimit *common.Decimal `protobuf:"bytes,20,opt,name=payout_limit,json=payoutLimit,proto3" json:"payout_limit,omitempty"`
	// *
	// This is the credit limit that the counterparty is willing to extend to the provider.
	CreditLimit *common.Decimal `protobuf:"bytes,30,opt,name=credit_limit,json=creditLimit,proto3" json:"credit_limit,omitempty"`
	// *
	// This is the credit usage that the provider has used so far. It is the sum of all payouts made by the provider
	// minus the settlement net (settlement balance). It could be negative if the provider has received more
	// in settlements than made payouts.
	CreditUsage *common.Decimal `protobuf:"bytes,40,opt,name=credit_usage,json=creditUsage,proto3" json:"credit_usage,omitempty"`
	// *
	// This indicates how much is reserved for the pending payments (not yet finalized)
	Reserve       *common.Decimal `protobuf:"bytes,50,opt,name=reserve,proto3" json:"reserve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLimitRequest_Limit) Reset() {
	*x = UpdateLimitRequest_Limit{}
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLimitRequest_Limit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLimitRequest_Limit) ProtoMessage() {}

func (x *UpdateLimitRequest_Limit) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLimitRequest_Limit.ProtoReflect.Descriptor instead.
func (*UpdateLimitRequest_Limit) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{6, 0}
}

func (x *UpdateLimitRequest_Limit) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *UpdateLimitRequest_Limit) GetCounterpartId() int32 {
	if x != nil {
		return x.CounterpartId
	}
	return 0
}

func (x *UpdateLimitRequest_Limit) GetPayoutLimit() *common.Decimal {
	if x != nil {
		return x.PayoutLimit
	}
	return nil
}

func (x *UpdateLimitRequest_Limit) GetCreditLimit() *common.Decimal {
	if x != nil {
		return x.CreditLimit
	}
	return nil
}

func (x *UpdateLimitRequest_Limit) GetCreditUsage() *common.Decimal {
	if x != nil {
		return x.CreditUsage
	}
	return nil
}

func (x *UpdateLimitRequest_Limit) GetReserve() *common.Decimal {
	if x != nil {
		return x.Reserve
	}
	return nil
}

type ApprovePaymentQuoteResponse_Accepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovePaymentQuoteResponse_Accepted) Reset() {
	*x = ApprovePaymentQuoteResponse_Accepted{}
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovePaymentQuoteResponse_Accepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovePaymentQuoteResponse_Accepted) ProtoMessage() {}

func (x *ApprovePaymentQuoteResponse_Accepted) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovePaymentQuoteResponse_Accepted.ProtoReflect.Descriptor instead.
func (*ApprovePaymentQuoteResponse_Accepted) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{9, 0}
}

type ApprovePaymentQuoteResponse_Rejected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovePaymentQuoteResponse_Rejected) Reset() {
	*x = ApprovePaymentQuoteResponse_Rejected{}
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovePaymentQuoteResponse_Rejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovePaymentQuoteResponse_Rejected) ProtoMessage() {}

func (x *ApprovePaymentQuoteResponse_Rejected) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_payment_provider_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovePaymentQuoteResponse_Rejected.ProtoReflect.Descriptor instead.
func (*ApprovePaymentQuoteResponse_Rejected) Descriptor() ([]byte, []int) {
	return file_tzero_v1_payment_provider_proto_rawDescGZIP(), []int{9, 1}
}

var File_tzero_v1_payment_provider_proto protoreflect.FileDescriptor

const file_tzero_v1_payment_provider_proto_rawDesc = "" +
	"\n" +
	"\x1ftzero/v1/payment/provider.proto\x12\x10tzero.v1.payment\x1a$tzero/v1/common/payment_method.proto\x1a%tzero/v1/common/payment_receipt.proto\x1a\x1ctzero/v1/common/common.proto\x1a\x1divms101/v1/ivms/ivms101.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\x9e\n" +
	"\n" +
	"\x1aAppendLedgerEntriesRequest\x12f\n" +
	"\ftransactions\x18\x14 \x03(\v28.tzero.v1.payment.AppendLedgerEntriesRequest.TransactionB\b\xbaH\x05\x92\x01\x02\b\x01R\ftransactions\x1a\xc4\x05\n" +
	"\vTransaction\x12.\n" +
	"\x0etransaction_id\x18\n" +
	" \x01(\x04B\a\xbaH\x042\x02 \x00R\rtransactionId\x12\\\n" +
	"\aentries\x18\x1e \x03(\v28.tzero.v1.payment.AppendLedgerEntriesRequest.LedgerEntryB\b\xbaH\x05\x92\x01\x02\b\x01R\aentries\x12Z\n" +
	"\x06payout\x18\x82\x01 \x01(\v2?.tzero.v1.payment.AppendLedgerEntriesRequest.Transaction.PayoutH\x00R\x06payout\x12\x7f\n" +
	"\x13provider_settlement\x18\x8c\x01 \x01(\v2K.tzero.v1.payment.AppendLedgerEntriesRequest.Transaction.ProviderSettlementH\x00R\x12providerSettlement\x12p\n" +
	"\x0efee_settlement\x18\x96\x01 \x01(\v2F.tzero.v1.payment.AppendLedgerEntriesRequest.Transaction.FeeSettlementH\x00R\rfeeSettlement\x1a0\n" +
	"\x06Payout\x12&\n" +
	"\n" +
	"payment_id\x18\n" +
	" \x01(\x04B\a\xbaH\x042\x02 \x00R\tpaymentId\x1aB\n" +
	"\x12ProviderSettlement\x12,\n" +
	"\rsettlement_id\x18\n" +
	" \x01(\x04B\a\xbaH\x042\x02 \x00R\fsettlementId\x1aD\n" +
	"\rFeeSettlement\x123\n" +
	"\x11fee_settlement_id\x18\n" +
	" \x01(\x04B\a\xbaH\x042\x02 \x00R\x0ffeeSettlementIdB\x1c\n" +
	"\x13transaction_details\x12\x05\xbaH\x02\b\x01\x1a\xf6\x01\n" +
	"\vLedgerEntry\x12(\n" +
	"\x10account_owner_id\x18\n" +
	" \x01(\rR\x0eaccountOwnerId\x12[\n" +
	"\faccount_type\x18\x14 \x01(\x0e28.tzero.v1.payment.AppendLedgerEntriesRequest.AccountTypeR\vaccountType\x12.\n" +
	"\x05debit\x18( \x01(\v2\x18.tzero.v1.common.DecimalR\x05debit\x120\n" +
	"\x06credit\x182 \x01(\v2\x18.tzero.v1.common.DecimalR\x06credit\"\xd7\x01\n" +
	"\vAccountType\x12\x1c\n" +
	"\x18ACCOUNT_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ACCOUNT_TYPE_BALANCE\x10\x14\x12\x17\n" +
	"\x13ACCOUNT_TYPE_PAY_IN\x10(\x12\x18\n" +
	"\x14ACCOUNT_TYPE_PAY_OUT\x102\x12\x1c\n" +
	"\x18ACCOUNT_TYPE_FEE_EXPENSE\x10<\x12\x1e\n" +
	"\x1aACCOUNT_TYPE_SETTLEMENT_IN\x10P\x12\x1f\n" +
	"\x1bACCOUNT_TYPE_SETTLEMENT_OUT\x10Z\"\x1d\n" +
	"\x1bAppendLedgerEntriesResponse\"\xb1\x05\n" +
	"\rPayoutRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\n" +
	" \x01(\x04R\tpaymentId\x12\x1f\n" +
	"\tpayout_id\x18\x14 \x01(\x04B\x02\x18\x01R\bpayoutId\x12\x1a\n" +
	"\bcurrency\x18\x1e \x01(\tR\bcurrency\x12&\n" +
	"\x0fclient_quote_id\x18( \x01(\tR\rclientQuoteId\x120\n" +
	"\x06amount\x182 \x01(\v2\x18.tzero.v1.common.DecimalR\x06amount\x12K\n" +
	"\x0epayout_details\x18< \x01(\v2\x1f.tzero.v1.common.PaymentDetailsH\x00R\rpayoutDetails\x88\x01\x01\x12+\n" +
	"\x12pay_in_provider_id\x18P \x01(\rR\x0fpayInProviderId\x12^\n" +
	"\x10travel_rule_data\x18\xc8\x01 \x01(\v2..tzero.v1.payment.PayoutRequest.TravelRuleDataH\x01R\x0etravelRuleData\x88\x01\x01\x1a\xe7\x01\n" +
	"\x0eTravelRuleData\x129\n" +
	"\n" +
	"originator\x18\n" +
	" \x03(\v2\x0f.ivms101.PersonB\b\xbaH\x05\x92\x01\x02\b\x01R\n" +
	"originator\x12;\n" +
	"\vbeneficiary\x18\x14 \x03(\v2\x0f.ivms101.PersonB\b\xbaH\x05\x92\x01\x02\b\x01R\vbeneficiary\x12E\n" +
	"\x13originator_provider\x18\x1e \x01(\v2\x0f.ivms101.PersonH\x00R\x12originatorProvider\x88\x01\x01B\x16\n" +
	"\x14_originator_providerB\x11\n" +
	"\x0f_payout_detailsB\x13\n" +
	"\x11_travel_rule_data\"\xc1\x03\n" +
	"\x0ePayoutResponse\x12G\n" +
	"\baccepted\x18\x14 \x01(\v2).tzero.v1.payment.PayoutResponse.AcceptedH\x00R\baccepted\x12A\n" +
	"\x06failed\x18\x1e \x01(\v2'.tzero.v1.payment.PayoutResponse.FailedH\x00R\x06failed\x12[\n" +
	"\x10manual_aml_check\x18( \x01(\v2/.tzero.v1.payment.PayoutResponse.ManualAmlCheckH\x00R\x0emanualAmlCheck\x1a\n" +
	"\n" +
	"\bAccepted\x1a\x10\n" +
	"\x0eManualAmlCheck\x1a\x9d\x01\n" +
	"\x06Failed\x12F\n" +
	"\x06reason\x18\n" +
	" \x01(\x0e2..tzero.v1.payment.PayoutResponse.Failed.ReasonR\x06reason\x12\x1d\n" +
	"\adetails\x18\x14 \x01(\tH\x00R\adetails\x88\x01\x01\" \n" +
	"\x06Reason\x12\x16\n" +
	"\x12REASON_UNSPECIFIED\x10\x00B\n" +
	"\n" +
	"\b_detailsB\b\n" +
	"\x06result\"\xc3\t\n" +
	"\x14UpdatePaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x05 \x01(\x04R\tpaymentId\x12*\n" +
	"\x11payment_client_id\x18\n" +
	" \x01(\tR\x0fpaymentClientId\x12M\n" +
	"\baccepted\x18\x14 \x01(\v2/.tzero.v1.payment.UpdatePaymentRequest.AcceptedH\x00R\baccepted\x12G\n" +
	"\x06failed\x18\x1e \x01(\v2-.tzero.v1.payment.UpdatePaymentRequest.FailedH\x00R\x06failed\x12P\n" +
	"\tconfirmed\x18( \x01(\v20.tzero.v1.payment.UpdatePaymentRequest.ConfirmedH\x00R\tconfirmed\x12a\n" +
	"\x10manual_aml_check\x182 \x01(\v25.tzero.v1.payment.UpdatePaymentRequest.ManualAmlCheckH\x00R\x0emanualAmlCheck\x1a\xc1\x02\n" +
	"\bAccepted\x12=\n" +
	"\rpayout_amount\x18\n" +
	" \x01(\v2\x18.tzero.v1.common.DecimalR\fpayoutAmount\x12m\n" +
	"\x10travel_rule_data\x18\x14 \x01(\v2>.tzero.v1.payment.UpdatePaymentRequest.Accepted.TravelRuleDataH\x00R\x0etravelRuleData\x88\x01\x01\x1ar\n" +
	"\x0eTravelRuleData\x12G\n" +
	"\x14beneficiary_provider\x18\n" +
	" \x01(\v2\x0f.ivms101.PersonH\x00R\x13beneficiaryProvider\x88\x01\x01B\x17\n" +
	"\x15_beneficiary_providerB\x13\n" +
	"\x11_travel_rule_data\x1a\x9c\x02\n" +
	"\x06Failed\x12L\n" +
	"\x06reason\x18\n" +
	" \x01(\x0e24.tzero.v1.payment.UpdatePaymentRequest.Failed.ReasonR\x06reason\x12\x1d\n" +
	"\adetails\x18\x14 \x01(\tH\x00R\adetails\x88\x01\x01\"\x98\x01\n" +
	"\x06Reason\x12\x16\n" +
	"\x12REASON_UNSPECIFIED\x10\x00\x12&\n" +
	"\"REASON_NO_QUOTE_AFTER_AML_APPROVAL\x10\x01\x12,\n" +
	"(REASON_QUOTE_REJECTED_AFTER_AML_APPROVAL\x10\x02\x12 \n" +
	"\x1cREASON_AML_RISK_CHECK_FAILED\x10\x03B\n" +
	"\n" +
	"\b_details\x1a\x93\x01\n" +
	"\tConfirmed\x12:\n" +
	"\vpaid_out_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tpaidOutAt\x12>\n" +
	"\areceipt\x18\x14 \x01(\v2\x1f.tzero.v1.common.PaymentReceiptH\x00R\areceipt\x88\x01\x01B\n" +
	"\n" +
	"\b_receipt\x1a\x10\n" +
	"\x0eManualAmlCheckB\b\n" +
	"\x06result\"\x17\n" +
	"\x15UpdatePaymentResponse\"\x8e\x03\n" +
	"\x12UpdateLimitRequest\x12B\n" +
	"\x06limits\x18\n" +
	" \x03(\v2*.tzero.v1.payment.UpdateLimitRequest.LimitR\x06limits\x1a\xb3\x02\n" +
	"\x05Limit\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\x03R\aversion\x12%\n" +
	"\x0ecounterpart_id\x18\x0f \x01(\x05R\rcounterpartId\x12;\n" +
	"\fpayout_limit\x18\x14 \x01(\v2\x18.tzero.v1.common.DecimalR\vpayoutLimit\x12;\n" +
	"\fcredit_limit\x18\x1e \x01(\v2\x18.tzero.v1.common.DecimalR\vcreditLimit\x12;\n" +
	"\fcredit_usage\x18( \x01(\v2\x18.tzero.v1.common.DecimalR\vcreditUsage\x122\n" +
	"\areserve\x182 \x01(\v2\x18.tzero.v1.common.DecimalR\areserve\"\x15\n" +
	"\x13UpdateLimitResponse\"\xb0\x02\n" +
	"\x1aApprovePaymentQuoteRequest\x12&\n" +
	"\n" +
	"payment_id\x18\n" +
	" \x01(\x04B\a\xbaH\x042\x02 \x00R\tpaymentId\x12'\n" +
	"\x10pay_out_quote_id\x18\x14 \x01(\x03R\rpayOutQuoteId\x12:\n" +
	"\fpay_out_rate\x18\x1e \x01(\v2\x18.tzero.v1.common.DecimalR\n" +
	"payOutRate\x12>\n" +
	"\x0epay_out_amount\x18( \x01(\v2\x18.tzero.v1.common.DecimalR\fpayOutAmount\x12E\n" +
	"\x11settlement_amount\x182 \x01(\v2\x18.tzero.v1.common.DecimalR\x10settlementAmount\"\xeb\x01\n" +
	"\x1bApprovePaymentQuoteResponse\x12T\n" +
	"\baccepted\x18\n" +
	" \x01(\v26.tzero.v1.payment.ApprovePaymentQuoteResponse.AcceptedH\x00R\baccepted\x12T\n" +
	"\brejected\x18\x14 \x01(\v26.tzero.v1.payment.ApprovePaymentQuoteResponse.RejectedH\x00R\brejected\x1a\n" +
	"\n" +
	"\bAccepted\x1a\n" +
	"\n" +
	"\bRejectedB\b\n" +
	"\x06result2\x9e\x04\n" +
	"\x0fProviderService\x12P\n" +
	"\x06PayOut\x12\x1f.tzero.v1.payment.PayoutRequest\x1a .tzero.v1.payment.PayoutResponse\"\x03\x90\x02\x02\x12e\n" +
	"\rUpdatePayment\x12&.tzero.v1.payment.UpdatePaymentRequest\x1a'.tzero.v1.payment.UpdatePaymentResponse\"\x03\x90\x02\x02\x12_\n" +
	"\vUpdateLimit\x12$.tzero.v1.payment.UpdateLimitRequest\x1a%.tzero.v1.payment.UpdateLimitResponse\"\x03\x90\x02\x02\x12w\n" +
	"\x13AppendLedgerEntries\x12,.tzero.v1.payment.AppendLedgerEntriesRequest\x1a-.tzero.v1.payment.AppendLedgerEntriesResponse\"\x03\x90\x02\x02\x12x\n" +
	"\x14ApprovePaymentQuotes\x12,.tzero.v1.payment.ApprovePaymentQuoteRequest\x1a-.tzero.v1.payment.ApprovePaymentQuoteResponse\"\x03\x90\x02\x02B\xc4\x01\n" +
	"\x14com.tzero.v1.paymentB\rProviderProtoP\x01Z;github.com/t-0-network/provider-sdk-go/api/tzero/v1/payment\xa2\x02\x03TVP\xaa\x02\x10Tzero.V1.Payment\xca\x02\x10Tzero\\V1\\Payment\xe2\x02\x1cTzero\\V1\\Payment\\GPBMetadata\xea\x02\x12Tzero::V1::Paymentb\x06proto3"

var (
	file_tzero_v1_payment_provider_proto_rawDescOnce sync.Once
	file_tzero_v1_payment_provider_proto_rawDescData []byte
)

func file_tzero_v1_payment_provider_proto_rawDescGZIP() []byte {
	file_tzero_v1_payment_provider_proto_rawDescOnce.Do(func() {
		file_tzero_v1_payment_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tzero_v1_payment_provider_proto_rawDesc), len(file_tzero_v1_payment_provider_proto_rawDesc)))
	})
	return file_tzero_v1_payment_provider_proto_rawDescData
}

var file_tzero_v1_payment_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_tzero_v1_payment_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_tzero_v1_payment_provider_proto_goTypes = []any{
	(AppendLedgerEntriesRequest_AccountType)(0),                       // 0: tzero.v1.payment.AppendLedgerEntriesRequest.AccountType
	(PayoutResponse_Failed_Reason)(0),                                 // 1: tzero.v1.payment.PayoutResponse.Failed.Reason
	(UpdatePaymentRequest_Failed_Reason)(0),                           // 2: tzero.v1.payment.UpdatePaymentRequest.Failed.Reason
	(*AppendLedgerEntriesRequest)(nil),                                // 3: tzero.v1.payment.AppendLedgerEntriesRequest
	(*AppendLedgerEntriesResponse)(nil),                               // 4: tzero.v1.payment.AppendLedgerEntriesResponse
	(*PayoutRequest)(nil),                                             // 5: tzero.v1.payment.PayoutRequest
	(*PayoutResponse)(nil),                                            // 6: tzero.v1.payment.PayoutResponse
	(*UpdatePaymentRequest)(nil),                                      // 7: tzero.v1.payment.UpdatePaymentRequest
	(*UpdatePaymentResponse)(nil),                                     // 8: tzero.v1.payment.UpdatePaymentResponse
	(*UpdateLimitRequest)(nil),                                        // 9: tzero.v1.payment.UpdateLimitRequest
	(*UpdateLimitResponse)(nil),                                       // 10: tzero.v1.payment.UpdateLimitResponse
	(*ApprovePaymentQuoteRequest)(nil),                                // 11: tzero.v1.payment.ApprovePaymentQuoteRequest
	(*ApprovePaymentQuoteResponse)(nil),                               // 12: tzero.v1.payment.ApprovePaymentQuoteResponse
	(*AppendLedgerEntriesRequest_Transaction)(nil),                    // 13: tzero.v1.payment.AppendLedgerEntriesRequest.Transaction
	(*AppendLedgerEntriesRequest_LedgerEntry)(nil),                    // 14: tzero.v1.payment.AppendLedgerEntriesRequest.LedgerEntry
	(*AppendLedgerEntriesRequest_Transaction_Payout)(nil),             // 15: tzero.v1.payment.AppendLedgerEntriesRequest.Transaction.Payout
	(*AppendLedgerEntriesRequest_Transaction_ProviderSettlement)(nil), // 16: tzero.v1.payment.AppendLedgerEntriesRequest.Transaction.ProviderSettlement
	(*AppendLedgerEntriesRequest_Transaction_FeeSettlement)(nil),      // 17: tzero.v1.payment.AppendLedgerEntriesRequest.Transaction.FeeSettlement
	(*PayoutRequest_TravelRuleData)(nil),                              // 18: tzero.v1.payment.PayoutRequest.TravelRuleData
	(*PayoutResponse_Accepted)(nil),                                   // 19: tzero.v1.payment.PayoutResponse.Accepted
	(*PayoutResponse_ManualAmlCheck)(nil),                             // 20: tzero.v1.payment.PayoutResponse.ManualAmlCheck
	(*PayoutResponse_Failed)(nil),                                     // 21: tzero.v1.payment.PayoutResponse.Failed
	(*UpdatePaymentRequest_Accepted)(nil),                             // 22: tzero.v1.payment.UpdatePaymentRequest.Accepted
	(*UpdatePaymentRequest_Failed)(nil),                               // 23: tzero.v1.payment.UpdatePaymentRequest.Failed
	(*UpdatePaymentRequest_Confirmed)(nil),                            // 24: tzero.v1.payment.UpdatePaymentRequest.Confirmed
	(*UpdatePaymentRequest_ManualAmlCheck)(nil),                       // 25: tzero.v1.payment.UpdatePaymentRequest.ManualAmlCheck
	(*UpdatePaymentRequest_Accepted_TravelRuleData)(nil),              // 26: tzero.v1.payment.UpdatePaymentRequest.Accepted.TravelRuleData
	(*UpdateLimitRequest_Limit)(nil),                                  // 27: tzero.v1.payment.UpdateLimitRequest.Limit
	(*ApprovePaymentQuoteResponse_Accepted)(nil),                      // 28: tzero.v1.payment.ApprovePaymentQuoteResponse.Accepted
	(*ApprovePaymentQuoteResponse_Rejected)(nil),                      // 29: tzero.v1.payment.ApprovePaymentQuoteResponse.Rejected
	(*common.Decimal)(nil),                                            // 30: tzero.v1.common.Decimal
	(*common.PaymentDetails)(nil),                                     // 31: tzero.v1.common.PaymentDetails
	(*ivms.Person)(nil),                                               // 32: ivms101.Person
	(*timestamppb.Timestamp)(nil),                                     // 33: google.protobuf.Timestamp
	(*common.PaymentReceipt)(nil),                                     // 34: tzero.v1.common.PaymentReceipt
}
var file_tzero_v1_payment_provider_proto_depIdxs = []int32{
	13, // 0: tzero.v1.payment.AppendLedgerEntriesRequest.transactions:type_name -> tzero.v1.payment.AppendLedgerEntriesRequest.Transaction
	30, // 1: tzero.v1.payment.PayoutRequest.amount:type_name -> tzero.v1.common.Decimal
	31, // 2: tzero.v1.payment.PayoutRequest.payout_details:type_name -> tzero.v1.common.PaymentDetails
	18, // 3: tzero.v1.payment.PayoutRequest.travel_rule_data:type_name -> tzero.v1.payment.PayoutRequest.TravelRuleData
	19, // 4: tzero.v1.payment.PayoutResponse.accepted:type_name -> tzero.v1.payment.PayoutResponse.Accepted
	21, // 5: tzero.v1.payment.PayoutResponse.failed:type_name -> tzero.v1.payment.PayoutResponse.Failed
	20, // 6: tzero.v1.payment.PayoutResponse.manual_aml_check:type_name -> tzero.v1.payment.PayoutResponse.ManualAmlCheck
	22, // 7: tzero.v1.payment.UpdatePaymentRequest.accepted:type_name -> tzero.v1.payment.UpdatePaymentRequest.Accepted
	23, // 8: tzero.v1.payment.UpdatePaymentRequest.failed:type_name -> tzero.v1.payment.UpdatePaymentRequest.Failed
	24, // 9: tzero.v1.payment.UpdatePaymentRequest.confirmed:type_name -> tzero.v1.payment.UpdatePaymentRequest.Confirmed
	25, // 10: tzero.v1.payment.UpdatePaymentRequest.manual_aml_check:type_name -> tzero.v1.payment.UpdatePaymentRequest.ManualAmlCheck
	27, // 11: tzero.v1.payment.UpdateLimitRequest.limits:type_name -> tzero.v1.payment.UpdateLimitRequest.Limit
	30, // 12: tzero.v1.payment.ApprovePaymentQuoteRequest.pay_out_rate:type_name -> tzero.v1.common.Decimal
	30, // 13: tzero.v1.payment.ApprovePaymentQuoteRequest.pay_out_amount:type_name -> tzero.v1.common.Decimal
	30, // 14: tzero.v1.payment.ApprovePaymentQuoteRequest.settlement_amount:type_name -> tzero.v1.common.Decimal
	28, // 15: tzero.v1.payment.ApprovePaymentQuoteResponse.accepted:type_name -> tzero.v1.payment.ApprovePaymentQuoteResponse.Accepted
	29, // 16: tzero.v1.payment.ApprovePaymentQuoteResponse.rejected:type_name -> tzero.v1.payment.ApprovePaymentQuoteResponse.Rejected
	14, // 17: tzero.v1.payment.AppendLedgerEntriesRequest.Transaction.entries:type_name -> tzero.v1.payment.AppendLedgerEntriesRequest.LedgerEntry
	15, // 18: tzero.v1.payment.AppendLedgerEntriesRequest.Transaction.payout:type_name -> tzero.v1.payment.AppendLedgerEntriesRequest.Transaction.Payout
	16, // 19: tzero.v1.payment.AppendLedgerEntriesRequest.Transaction.provider_settlement:type_name -> tzero.v1.payment.AppendLedgerEntriesRequest.Transaction.ProviderSettlement
	17, // 20: tzero.v1.payment.AppendLedgerEntriesRequest.Transaction.fee_settlement:type_name -> tzero.v1.payment.AppendLedgerEntriesRequest.Transaction.FeeSettlement
	0,  // 21: tzero.v1.payment.AppendLedgerEntriesRequest.LedgerEntry.account_type:type_name -> tzero.v1.payment.AppendLedgerEntriesRequest.AccountType
	30, // 22: tzero.v1.payment.AppendLedgerEntriesRequest.LedgerEntry.debit:type_name -> tzero.v1.common.Decimal
	30, // 23: tzero.v1.payment.AppendLedgerEntriesRequest.LedgerEntry.credit:type_name -> tzero.v1.common.Decimal
	32, // 24: tzero.v1.payment.PayoutRequest.TravelRuleData.originator:type_name -> ivms101.Person
	32, // 25: tzero.v1.payment.PayoutRequest.TravelRuleData.beneficiary:type_name -> ivms101.Person
	32, // 26: tzero.v1.payment.PayoutRequest.TravelRuleData.originator_provider:type_name -> ivms101.Person
	1,  // 27: tzero.v1.payment.PayoutResponse.Failed.reason:type_name -> tzero.v1.payment.PayoutResponse.Failed.Reason
	30, // 28: tzero.v1.payment.UpdatePaymentRequest.Accepted.payout_amount:type_name -> tzero.v1.common.Decimal
	26, // 29: tzero.v1.payment.UpdatePaymentRequest.Accepted.travel_rule_data:type_name -> tzero.v1.payment.UpdatePaymentRequest.Accepted.TravelRuleData
	2,  // 30: tzero.v1.payment.UpdatePaymentRequest.Failed.reason:type_name -> tzero.v1.payment.UpdatePaymentRequest.Failed.Reason
	33, // 31: tzero.v1.payment.UpdatePaymentRequest.Confirmed.paid_out_at:type_name -> google.protobuf.Timestamp
	34, // 32: tzero.v1.payment.UpdatePaymentRequest.Confirmed.receipt:type_name -> tzero.v1.common.PaymentReceipt
	32, // 33: tzero.v1.payment.UpdatePaymentRequest.Accepted.TravelRuleData.beneficiary_provider:type_name -> ivms101.Person
	30, // 34: tzero.v1.payment.UpdateLimitRequest.Limit.payout_limit:type_name -> tzero.v1.common.Decimal
	30, // 35: tzero.v1.payment.UpdateLimitRequest.Limit.credit_limit:type_name -> tzero.v1.common.Decimal
	30, // 36: tzero.v1.payment.UpdateLimitRequest.Limit.credit_usage:type_name -> tzero.v1.common.Decimal
	30, // 37: tzero.v1.payment.UpdateLimitRequest.Limit.reserve:type_name -> tzero.v1.common.Decimal
	5,  // 38: tzero.v1.payment.ProviderService.PayOut:input_type -> tzero.v1.payment.PayoutRequest
	7,  // 39: tzero.v1.payment.ProviderService.UpdatePayment:input_type -> tzero.v1.payment.UpdatePaymentRequest
	9,  // 40: tzero.v1.payment.ProviderService.UpdateLimit:input_type -> tzero.v1.payment.UpdateLimitRequest
	3,  // 41: tzero.v1.payment.ProviderService.AppendLedgerEntries:input_type -> tzero.v1.payment.AppendLedgerEntriesRequest
	11, // 42: tzero.v1.payment.ProviderService.ApprovePaymentQuotes:input_type -> tzero.v1.payment.ApprovePaymentQuoteRequest
	6,  // 43: tzero.v1.payment.ProviderService.PayOut:output_type -> tzero.v1.payment.PayoutResponse
	8,  // 44: tzero.v1.payment.ProviderService.UpdatePayment:output_type -> tzero.v1.payment.UpdatePaymentResponse
	10, // 45: tzero.v1.payment.ProviderService.UpdateLimit:output_type -> tzero.v1.payment.UpdateLimitResponse
	4,  // 46: tzero.v1.payment.ProviderService.AppendLedgerEntries:output_type -> tzero.v1.payment.AppendLedgerEntriesResponse
	12, // 47: tzero.v1.payment.ProviderService.ApprovePaymentQuotes:output_type -> tzero.v1.payment.ApprovePaymentQuoteResponse
	43, // [43:48] is the sub-list for method output_type
	38, // [38:43] is the sub-list for method input_type
	38, // [38:38] is the sub-list for extension type_name
	38, // [38:38] is the sub-list for extension extendee
	0,  // [0:38] is the sub-list for field type_name
}

func init() { file_tzero_v1_payment_provider_proto_init() }
func file_tzero_v1_payment_provider_proto_init() {
	if File_tzero_v1_payment_provider_proto != nil {
		return
	}
	file_tzero_v1_payment_provider_proto_msgTypes[2].OneofWrappers = []any{}
	file_tzero_v1_payment_provider_proto_msgTypes[3].OneofWrappers = []any{
		(*PayoutResponse_Accepted_)(nil),
		(*PayoutResponse_Failed_)(nil),
		(*PayoutResponse_ManualAmlCheck_)(nil),
	}
	file_tzero_v1_payment_provider_proto_msgTypes[4].OneofWrappers = []any{
		(*UpdatePaymentRequest_Accepted_)(nil),
		(*UpdatePaymentRequest_Failed_)(nil),
		(*UpdatePaymentRequest_Confirmed_)(nil),
		(*UpdatePaymentRequest_ManualAmlCheck_)(nil),
	}
	file_tzero_v1_payment_provider_proto_msgTypes[9].OneofWrappers = []any{
		(*ApprovePaymentQuoteResponse_Accepted_)(nil),
		(*ApprovePaymentQuoteResponse_Rejected_)(nil),
	}
	file_tzero_v1_payment_provider_proto_msgTypes[10].OneofWrappers = []any{
		(*AppendLedgerEntriesRequest_Transaction_Payout_)(nil),
		(*AppendLedgerEntriesRequest_Transaction_ProviderSettlement_)(nil),
		(*AppendLedgerEntriesRequest_Transaction_FeeSettlement_)(nil),
	}
	file_tzero_v1_payment_provider_proto_msgTypes[15].OneofWrappers = []any{}
	file_tzero_v1_payment_provider_proto_msgTypes[18].OneofWrappers = []any{}
	file_tzero_v1_payment_provider_proto_msgTypes[19].OneofWrappers = []any{}
	file_tzero_v1_payment_provider_proto_msgTypes[20].OneofWrappers = []any{}
	file_tzero_v1_payment_provider_proto_msgTypes[21].OneofWrappers = []any{}
	file_tzero_v1_payment_provider_proto_msgTypes[23].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tzero_v1_payment_provider_proto_rawDesc), len(file_tzero_v1_payment_provider_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tzero_v1_payment_provider_proto_goTypes,
		DependencyIndexes: file_tzero_v1_payment_provider_proto_depIdxs,
		EnumInfos:         file_tzero_v1_payment_provider_proto_enumTypes,
		MessageInfos:      file_tzero_v1_payment_provider_proto_msgTypes,
	}.Build()
	File_tzero_v1_payment_provider_proto = out.File
	file_tzero_v1_payment_provider_proto_goTypes = nil
	file_tzero_v1_payment_provider_proto_depIdxs = nil
}
