// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: tzero/v1/payment/network.proto

package paymentconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	payment "github.com/t-0-network/provider-sdk-go/api/tzero/v1/payment"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NetworkServiceName is the fully-qualified name of the NetworkService service.
	NetworkServiceName = "tzero.v1.payment.NetworkService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NetworkServiceUpdateQuoteProcedure is the fully-qualified name of the NetworkService's
	// UpdateQuote RPC.
	NetworkServiceUpdateQuoteProcedure = "/tzero.v1.payment.NetworkService/UpdateQuote"
	// NetworkServiceGetQuoteProcedure is the fully-qualified name of the NetworkService's GetQuote RPC.
	NetworkServiceGetQuoteProcedure = "/tzero.v1.payment.NetworkService/GetQuote"
	// NetworkServiceCreatePaymentProcedure is the fully-qualified name of the NetworkService's
	// CreatePayment RPC.
	NetworkServiceCreatePaymentProcedure = "/tzero.v1.payment.NetworkService/CreatePayment"
	// NetworkServiceConfirmPayoutProcedure is the fully-qualified name of the NetworkService's
	// ConfirmPayout RPC.
	NetworkServiceConfirmPayoutProcedure = "/tzero.v1.payment.NetworkService/ConfirmPayout"
	// NetworkServiceCompleteManualAmlCheckProcedure is the fully-qualified name of the NetworkService's
	// CompleteManualAmlCheck RPC.
	NetworkServiceCompleteManualAmlCheckProcedure = "/tzero.v1.payment.NetworkService/CompleteManualAmlCheck"
)

// NetworkServiceClient is a client for the tzero.v1.payment.NetworkService service.
type NetworkServiceClient interface {
	// *
	// Used by the provider to publish pay-in and pay-out quotes (FX rates) into the network.
	// These quotes include tiered pricing bands and an expiration timestamp.
	UpdateQuote(context.Context, *connect.Request[payment.UpdateQuoteRequest]) (*connect.Response[payment.UpdateQuoteResponse], error)
	// *
	// Request the best available quote for a payout in a specific currency, for a given amount.
	// If the payout quote exists, but the credit limit is exceeded, this quote will not be considered.
	// Before calling this endpoint UpdateQuote should be periodically triggered in order to put pay-in quotes into the network.
	GetQuote(context.Context, *connect.Request[payment.GetQuoteRequest]) (*connect.Response[payment.GetQuoteResponse], error)
	// *
	// Submit a request to create a new payment. PayIn currency and QuoteId are the optional parameters.
	// If the payIn currency is not specified, the network will use USD as the default payIn currency, and considering
	// the amount in USD.
	// If specified, it must be a valid currency code - in this case the network will try to find the payIn quote for the
	// specified currency and considering the band from the provider initiated this request. So this is only possible, if
	// this provider already submitted the payIn quote for the specified currency using UpdateQuote rpc.
	// If the quoteID is specified, it must be a valid quoteId that was previously returned by the GetPayoutQuote method.
	// If the quoteId is not specified, the network will try to find a suitable quote for the payout currency and amount,
	// same way as GetPayoutQuote rpc.
	CreatePayment(context.Context, *connect.Request[payment.CreatePaymentRequest]) (*connect.Response[payment.CreatePaymentResponse], error)
	// *
	// Inform the network that a payout has been completed. This endpoint is called by the payout
	// provider, specifying the payment ID and payout ID, which was provided when the payout request was made to this provider.
	ConfirmPayout(context.Context, *connect.Request[payment.ConfirmPayoutRequest]) (*connect.Response[payment.ConfirmPayoutResponse], error)
	// *
	// Pay-out provider reports the result of manual AML check.
	// This endpoint is called after the manual AML check is completed. The network will find the new best quotes for the
	// payment and will return the updated settlement/payout amount along with the updated quotes in the response.
	CompleteManualAmlCheck(context.Context, *connect.Request[payment.CompleteManualAmlCheckRequest]) (*connect.Response[payment.CompleteManualAmlCheckResponse], error)
}

// NewNetworkServiceClient constructs a client for the tzero.v1.payment.NetworkService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNetworkServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NetworkServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	networkServiceMethods := payment.File_tzero_v1_payment_network_proto.Services().ByName("NetworkService").Methods()
	return &networkServiceClient{
		updateQuote: connect.NewClient[payment.UpdateQuoteRequest, payment.UpdateQuoteResponse](
			httpClient,
			baseURL+NetworkServiceUpdateQuoteProcedure,
			connect.WithSchema(networkServiceMethods.ByName("UpdateQuote")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
		getQuote: connect.NewClient[payment.GetQuoteRequest, payment.GetQuoteResponse](
			httpClient,
			baseURL+NetworkServiceGetQuoteProcedure,
			connect.WithSchema(networkServiceMethods.ByName("GetQuote")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		createPayment: connect.NewClient[payment.CreatePaymentRequest, payment.CreatePaymentResponse](
			httpClient,
			baseURL+NetworkServiceCreatePaymentProcedure,
			connect.WithSchema(networkServiceMethods.ByName("CreatePayment")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
		confirmPayout: connect.NewClient[payment.ConfirmPayoutRequest, payment.ConfirmPayoutResponse](
			httpClient,
			baseURL+NetworkServiceConfirmPayoutProcedure,
			connect.WithSchema(networkServiceMethods.ByName("ConfirmPayout")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
		completeManualAmlCheck: connect.NewClient[payment.CompleteManualAmlCheckRequest, payment.CompleteManualAmlCheckResponse](
			httpClient,
			baseURL+NetworkServiceCompleteManualAmlCheckProcedure,
			connect.WithSchema(networkServiceMethods.ByName("CompleteManualAmlCheck")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
	}
}

// networkServiceClient implements NetworkServiceClient.
type networkServiceClient struct {
	updateQuote            *connect.Client[payment.UpdateQuoteRequest, payment.UpdateQuoteResponse]
	getQuote               *connect.Client[payment.GetQuoteRequest, payment.GetQuoteResponse]
	createPayment          *connect.Client[payment.CreatePaymentRequest, payment.CreatePaymentResponse]
	confirmPayout          *connect.Client[payment.ConfirmPayoutRequest, payment.ConfirmPayoutResponse]
	completeManualAmlCheck *connect.Client[payment.CompleteManualAmlCheckRequest, payment.CompleteManualAmlCheckResponse]
}

// UpdateQuote calls tzero.v1.payment.NetworkService.UpdateQuote.
func (c *networkServiceClient) UpdateQuote(ctx context.Context, req *connect.Request[payment.UpdateQuoteRequest]) (*connect.Response[payment.UpdateQuoteResponse], error) {
	return c.updateQuote.CallUnary(ctx, req)
}

// GetQuote calls tzero.v1.payment.NetworkService.GetQuote.
func (c *networkServiceClient) GetQuote(ctx context.Context, req *connect.Request[payment.GetQuoteRequest]) (*connect.Response[payment.GetQuoteResponse], error) {
	return c.getQuote.CallUnary(ctx, req)
}

// CreatePayment calls tzero.v1.payment.NetworkService.CreatePayment.
func (c *networkServiceClient) CreatePayment(ctx context.Context, req *connect.Request[payment.CreatePaymentRequest]) (*connect.Response[payment.CreatePaymentResponse], error) {
	return c.createPayment.CallUnary(ctx, req)
}

// ConfirmPayout calls tzero.v1.payment.NetworkService.ConfirmPayout.
func (c *networkServiceClient) ConfirmPayout(ctx context.Context, req *connect.Request[payment.ConfirmPayoutRequest]) (*connect.Response[payment.ConfirmPayoutResponse], error) {
	return c.confirmPayout.CallUnary(ctx, req)
}

// CompleteManualAmlCheck calls tzero.v1.payment.NetworkService.CompleteManualAmlCheck.
func (c *networkServiceClient) CompleteManualAmlCheck(ctx context.Context, req *connect.Request[payment.CompleteManualAmlCheckRequest]) (*connect.Response[payment.CompleteManualAmlCheckResponse], error) {
	return c.completeManualAmlCheck.CallUnary(ctx, req)
}

// NetworkServiceHandler is an implementation of the tzero.v1.payment.NetworkService service.
type NetworkServiceHandler interface {
	// *
	// Used by the provider to publish pay-in and pay-out quotes (FX rates) into the network.
	// These quotes include tiered pricing bands and an expiration timestamp.
	UpdateQuote(context.Context, *connect.Request[payment.UpdateQuoteRequest]) (*connect.Response[payment.UpdateQuoteResponse], error)
	// *
	// Request the best available quote for a payout in a specific currency, for a given amount.
	// If the payout quote exists, but the credit limit is exceeded, this quote will not be considered.
	// Before calling this endpoint UpdateQuote should be periodically triggered in order to put pay-in quotes into the network.
	GetQuote(context.Context, *connect.Request[payment.GetQuoteRequest]) (*connect.Response[payment.GetQuoteResponse], error)
	// *
	// Submit a request to create a new payment. PayIn currency and QuoteId are the optional parameters.
	// If the payIn currency is not specified, the network will use USD as the default payIn currency, and considering
	// the amount in USD.
	// If specified, it must be a valid currency code - in this case the network will try to find the payIn quote for the
	// specified currency and considering the band from the provider initiated this request. So this is only possible, if
	// this provider already submitted the payIn quote for the specified currency using UpdateQuote rpc.
	// If the quoteID is specified, it must be a valid quoteId that was previously returned by the GetPayoutQuote method.
	// If the quoteId is not specified, the network will try to find a suitable quote for the payout currency and amount,
	// same way as GetPayoutQuote rpc.
	CreatePayment(context.Context, *connect.Request[payment.CreatePaymentRequest]) (*connect.Response[payment.CreatePaymentResponse], error)
	// *
	// Inform the network that a payout has been completed. This endpoint is called by the payout
	// provider, specifying the payment ID and payout ID, which was provided when the payout request was made to this provider.
	ConfirmPayout(context.Context, *connect.Request[payment.ConfirmPayoutRequest]) (*connect.Response[payment.ConfirmPayoutResponse], error)
	// *
	// Pay-out provider reports the result of manual AML check.
	// This endpoint is called after the manual AML check is completed. The network will find the new best quotes for the
	// payment and will return the updated settlement/payout amount along with the updated quotes in the response.
	CompleteManualAmlCheck(context.Context, *connect.Request[payment.CompleteManualAmlCheckRequest]) (*connect.Response[payment.CompleteManualAmlCheckResponse], error)
}

// NewNetworkServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNetworkServiceHandler(svc NetworkServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	networkServiceMethods := payment.File_tzero_v1_payment_network_proto.Services().ByName("NetworkService").Methods()
	networkServiceUpdateQuoteHandler := connect.NewUnaryHandler(
		NetworkServiceUpdateQuoteProcedure,
		svc.UpdateQuote,
		connect.WithSchema(networkServiceMethods.ByName("UpdateQuote")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceGetQuoteHandler := connect.NewUnaryHandler(
		NetworkServiceGetQuoteProcedure,
		svc.GetQuote,
		connect.WithSchema(networkServiceMethods.ByName("GetQuote")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceCreatePaymentHandler := connect.NewUnaryHandler(
		NetworkServiceCreatePaymentProcedure,
		svc.CreatePayment,
		connect.WithSchema(networkServiceMethods.ByName("CreatePayment")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceConfirmPayoutHandler := connect.NewUnaryHandler(
		NetworkServiceConfirmPayoutProcedure,
		svc.ConfirmPayout,
		connect.WithSchema(networkServiceMethods.ByName("ConfirmPayout")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	networkServiceCompleteManualAmlCheckHandler := connect.NewUnaryHandler(
		NetworkServiceCompleteManualAmlCheckProcedure,
		svc.CompleteManualAmlCheck,
		connect.WithSchema(networkServiceMethods.ByName("CompleteManualAmlCheck")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	return "/tzero.v1.payment.NetworkService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NetworkServiceUpdateQuoteProcedure:
			networkServiceUpdateQuoteHandler.ServeHTTP(w, r)
		case NetworkServiceGetQuoteProcedure:
			networkServiceGetQuoteHandler.ServeHTTP(w, r)
		case NetworkServiceCreatePaymentProcedure:
			networkServiceCreatePaymentHandler.ServeHTTP(w, r)
		case NetworkServiceConfirmPayoutProcedure:
			networkServiceConfirmPayoutHandler.ServeHTTP(w, r)
		case NetworkServiceCompleteManualAmlCheckProcedure:
			networkServiceCompleteManualAmlCheckHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNetworkServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNetworkServiceHandler struct{}

func (UnimplementedNetworkServiceHandler) UpdateQuote(context.Context, *connect.Request[payment.UpdateQuoteRequest]) (*connect.Response[payment.UpdateQuoteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tzero.v1.payment.NetworkService.UpdateQuote is not implemented"))
}

func (UnimplementedNetworkServiceHandler) GetQuote(context.Context, *connect.Request[payment.GetQuoteRequest]) (*connect.Response[payment.GetQuoteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tzero.v1.payment.NetworkService.GetQuote is not implemented"))
}

func (UnimplementedNetworkServiceHandler) CreatePayment(context.Context, *connect.Request[payment.CreatePaymentRequest]) (*connect.Response[payment.CreatePaymentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tzero.v1.payment.NetworkService.CreatePayment is not implemented"))
}

func (UnimplementedNetworkServiceHandler) ConfirmPayout(context.Context, *connect.Request[payment.ConfirmPayoutRequest]) (*connect.Response[payment.ConfirmPayoutResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tzero.v1.payment.NetworkService.ConfirmPayout is not implemented"))
}

func (UnimplementedNetworkServiceHandler) CompleteManualAmlCheck(context.Context, *connect.Request[payment.CompleteManualAmlCheckRequest]) (*connect.Response[payment.CompleteManualAmlCheckResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tzero.v1.payment.NetworkService.CompleteManualAmlCheck is not implemented"))
}
