// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tzero/v1/manage/dashboard.proto

package manage

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	common "github.com/t-0-network/provider-sdk-go/api/tzero/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPaymentsResponse_Payment_Type int32

const (
	GetPaymentsResponse_Payment_TYPE_UNSPECIFIED GetPaymentsResponse_Payment_Type = 0
	GetPaymentsResponse_Payment_TYPE_INITIATED   GetPaymentsResponse_Payment_Type = 10
	GetPaymentsResponse_Payment_TYPE_PAID_OUT    GetPaymentsResponse_Payment_Type = 20
)

// Enum value maps for GetPaymentsResponse_Payment_Type.
var (
	GetPaymentsResponse_Payment_Type_name = map[int32]string{
		0:  "TYPE_UNSPECIFIED",
		10: "TYPE_INITIATED",
		20: "TYPE_PAID_OUT",
	}
	GetPaymentsResponse_Payment_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_INITIATED":   10,
		"TYPE_PAID_OUT":    20,
	}
)

func (x GetPaymentsResponse_Payment_Type) Enum() *GetPaymentsResponse_Payment_Type {
	p := new(GetPaymentsResponse_Payment_Type)
	*p = x
	return p
}

func (x GetPaymentsResponse_Payment_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetPaymentsResponse_Payment_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_tzero_v1_manage_dashboard_proto_enumTypes[0].Descriptor()
}

func (GetPaymentsResponse_Payment_Type) Type() protoreflect.EnumType {
	return &file_tzero_v1_manage_dashboard_proto_enumTypes[0]
}

func (x GetPaymentsResponse_Payment_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetPaymentsResponse_Payment_Type.Descriptor instead.
func (GetPaymentsResponse_Payment_Type) EnumDescriptor() ([]byte, []int) {
	return file_tzero_v1_manage_dashboard_proto_rawDescGZIP(), []int{5, 0, 0}
}

type GetPaymentsResponse_Payment_Status int32

const (
	GetPaymentsResponse_Payment_STATUS_UNSPECIFIED            GetPaymentsResponse_Payment_Status = 0
	GetPaymentsResponse_Payment_STATUS_ACCEPTED               GetPaymentsResponse_Payment_Status = 10
	GetPaymentsResponse_Payment_STATUS_SUCCESS                GetPaymentsResponse_Payment_Status = 20
	GetPaymentsResponse_Payment_STATUS_FAILED                 GetPaymentsResponse_Payment_Status = 30
	GetPaymentsResponse_Payment_STATUS_PENDING_PRE_SETTLEMENT GetPaymentsResponse_Payment_Status = 40
)

// Enum value maps for GetPaymentsResponse_Payment_Status.
var (
	GetPaymentsResponse_Payment_Status_name = map[int32]string{
		0:  "STATUS_UNSPECIFIED",
		10: "STATUS_ACCEPTED",
		20: "STATUS_SUCCESS",
		30: "STATUS_FAILED",
		40: "STATUS_PENDING_PRE_SETTLEMENT",
	}
	GetPaymentsResponse_Payment_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":            0,
		"STATUS_ACCEPTED":               10,
		"STATUS_SUCCESS":                20,
		"STATUS_FAILED":                 30,
		"STATUS_PENDING_PRE_SETTLEMENT": 40,
	}
)

func (x GetPaymentsResponse_Payment_Status) Enum() *GetPaymentsResponse_Payment_Status {
	p := new(GetPaymentsResponse_Payment_Status)
	*p = x
	return p
}

func (x GetPaymentsResponse_Payment_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetPaymentsResponse_Payment_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_tzero_v1_manage_dashboard_proto_enumTypes[1].Descriptor()
}

func (GetPaymentsResponse_Payment_Status) Type() protoreflect.EnumType {
	return &file_tzero_v1_manage_dashboard_proto_enumTypes[1]
}

func (x GetPaymentsResponse_Payment_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetPaymentsResponse_Payment_Status.Descriptor instead.
func (GetPaymentsResponse_Payment_Status) EnumDescriptor() ([]byte, []int) {
	return file_tzero_v1_manage_dashboard_proto_rawDescGZIP(), []int{5, 0, 1}
}

type GetSettlementsResponse_Settlement_Type int32

const (
	GetSettlementsResponse_Settlement_TYPE_UNSPECIFIED GetSettlementsResponse_Settlement_Type = 0
	GetSettlementsResponse_Settlement_TYPE_SENT        GetSettlementsResponse_Settlement_Type = 10
	GetSettlementsResponse_Settlement_TYPE_RECEIVED    GetSettlementsResponse_Settlement_Type = 20
)

// Enum value maps for GetSettlementsResponse_Settlement_Type.
var (
	GetSettlementsResponse_Settlement_Type_name = map[int32]string{
		0:  "TYPE_UNSPECIFIED",
		10: "TYPE_SENT",
		20: "TYPE_RECEIVED",
	}
	GetSettlementsResponse_Settlement_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_SENT":        10,
		"TYPE_RECEIVED":    20,
	}
)

func (x GetSettlementsResponse_Settlement_Type) Enum() *GetSettlementsResponse_Settlement_Type {
	p := new(GetSettlementsResponse_Settlement_Type)
	*p = x
	return p
}

func (x GetSettlementsResponse_Settlement_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetSettlementsResponse_Settlement_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_tzero_v1_manage_dashboard_proto_enumTypes[2].Descriptor()
}

func (GetSettlementsResponse_Settlement_Type) Type() protoreflect.EnumType {
	return &file_tzero_v1_manage_dashboard_proto_enumTypes[2]
}

func (x GetSettlementsResponse_Settlement_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetSettlementsResponse_Settlement_Type.Descriptor instead.
func (GetSettlementsResponse_Settlement_Type) EnumDescriptor() ([]byte, []int) {
	return file_tzero_v1_manage_dashboard_proto_rawDescGZIP(), []int{7, 0, 0}
}

type GetVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVolumeRequest) Reset() {
	*x = GetVolumeRequest{}
	mi := &file_tzero_v1_manage_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVolumeRequest) ProtoMessage() {}

func (x *GetVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_manage_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVolumeRequest.ProtoReflect.Descriptor instead.
func (*GetVolumeRequest) Descriptor() ([]byte, []int) {
	return file_tzero_v1_manage_dashboard_proto_rawDescGZIP(), []int{0}
}

type GetVolumeResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Volumes       []*GetVolumeResponse_Volume `protobuf:"bytes,10,rep,name=volumes,proto3" json:"volumes,omitempty"`
	Total         *common.Decimal             `protobuf:"bytes,20,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVolumeResponse) Reset() {
	*x = GetVolumeResponse{}
	mi := &file_tzero_v1_manage_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVolumeResponse) ProtoMessage() {}

func (x *GetVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_manage_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVolumeResponse.ProtoReflect.Descriptor instead.
func (*GetVolumeResponse) Descriptor() ([]byte, []int) {
	return file_tzero_v1_manage_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *GetVolumeResponse) GetVolumes() []*GetVolumeResponse_Volume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *GetVolumeResponse) GetTotal() *common.Decimal {
	if x != nil {
		return x.Total
	}
	return nil
}

type GetLimitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLimitsRequest) Reset() {
	*x = GetLimitsRequest{}
	mi := &file_tzero_v1_manage_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLimitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLimitsRequest) ProtoMessage() {}

func (x *GetLimitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_manage_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLimitsRequest.ProtoReflect.Descriptor instead.
func (*GetLimitsRequest) Descriptor() ([]byte, []int) {
	return file_tzero_v1_manage_dashboard_proto_rawDescGZIP(), []int{2}
}

type GetLimitsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Limits        []*GetLimitsResponse_Limit `protobuf:"bytes,10,rep,name=limits,proto3" json:"limits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLimitsResponse) Reset() {
	*x = GetLimitsResponse{}
	mi := &file_tzero_v1_manage_dashboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLimitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLimitsResponse) ProtoMessage() {}

func (x *GetLimitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_manage_dashboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLimitsResponse.ProtoReflect.Descriptor instead.
func (*GetLimitsResponse) Descriptor() ([]byte, []int) {
	return file_tzero_v1_manage_dashboard_proto_rawDescGZIP(), []int{3}
}

func (x *GetLimitsResponse) GetLimits() []*GetLimitsResponse_Limit {
	if x != nil {
		return x.Limits
	}
	return nil
}

type GetPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *Page                  `protobuf:"bytes,10,opt,name=page,proto3,oneof" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentsRequest) Reset() {
	*x = GetPaymentsRequest{}
	mi := &file_tzero_v1_manage_dashboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentsRequest) ProtoMessage() {}

func (x *GetPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_manage_dashboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentsRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_tzero_v1_manage_dashboard_proto_rawDescGZIP(), []int{4}
}

func (x *GetPaymentsRequest) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetPaymentsResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Payments      []*GetPaymentsResponse_Payment `protobuf:"bytes,10,rep,name=payments,proto3" json:"payments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentsResponse) Reset() {
	*x = GetPaymentsResponse{}
	mi := &file_tzero_v1_manage_dashboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentsResponse) ProtoMessage() {}

func (x *GetPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_manage_dashboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentsResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_tzero_v1_manage_dashboard_proto_rawDescGZIP(), []int{5}
}

func (x *GetPaymentsResponse) GetPayments() []*GetPaymentsResponse_Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

type GetSettlementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *Page                  `protobuf:"bytes,10,opt,name=page,proto3,oneof" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettlementsRequest) Reset() {
	*x = GetSettlementsRequest{}
	mi := &file_tzero_v1_manage_dashboard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettlementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettlementsRequest) ProtoMessage() {}

func (x *GetSettlementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_manage_dashboard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettlementsRequest.ProtoReflect.Descriptor instead.
func (*GetSettlementsRequest) Descriptor() ([]byte, []int) {
	return file_tzero_v1_manage_dashboard_proto_rawDescGZIP(), []int{6}
}

func (x *GetSettlementsRequest) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetSettlementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettlementsResponse) Reset() {
	*x = GetSettlementsResponse{}
	mi := &file_tzero_v1_manage_dashboard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettlementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettlementsResponse) ProtoMessage() {}

func (x *GetSettlementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_manage_dashboard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettlementsResponse.ProtoReflect.Descriptor instead.
func (*GetSettlementsResponse) Descriptor() ([]byte, []int) {
	return file_tzero_v1_manage_dashboard_proto_rawDescGZIP(), []int{7}
}

type Provider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,20,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_tzero_v1_manage_dashboard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_manage_dashboard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_tzero_v1_manage_dashboard_proto_rawDescGZIP(), []int{8}
}

func (x *Provider) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Provider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *uint32                `protobuf:"varint,10,opt,name=page,proto3,oneof" json:"page,omitempty"`
	Size          *uint32                `protobuf:"varint,20,opt,name=size,proto3,oneof" json:"size,omitempty"` // 10 by default
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_tzero_v1_manage_dashboard_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_manage_dashboard_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_tzero_v1_manage_dashboard_proto_rawDescGZIP(), []int{9}
}

func (x *Page) GetPage() uint32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *Page) GetSize() uint32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

type GetVolumeResponse_Volume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *Provider              `protobuf:"bytes,10,opt,name=provider,proto3" json:"provider,omitempty"`
	PayIn         *common.Decimal        `protobuf:"bytes,20,opt,name=pay_in,json=payIn,proto3" json:"pay_in,omitempty"`
	PayOut        *common.Decimal        `protobuf:"bytes,30,opt,name=pay_out,json=payOut,proto3" json:"pay_out,omitempty"`
	Total         *common.Decimal        `protobuf:"bytes,40,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVolumeResponse_Volume) Reset() {
	*x = GetVolumeResponse_Volume{}
	mi := &file_tzero_v1_manage_dashboard_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVolumeResponse_Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVolumeResponse_Volume) ProtoMessage() {}

func (x *GetVolumeResponse_Volume) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_manage_dashboard_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVolumeResponse_Volume.ProtoReflect.Descriptor instead.
func (*GetVolumeResponse_Volume) Descriptor() ([]byte, []int) {
	return file_tzero_v1_manage_dashboard_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetVolumeResponse_Volume) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *GetVolumeResponse_Volume) GetPayIn() *common.Decimal {
	if x != nil {
		return x.PayIn
	}
	return nil
}

func (x *GetVolumeResponse_Volume) GetPayOut() *common.Decimal {
	if x != nil {
		return x.PayOut
	}
	return nil
}

func (x *GetVolumeResponse_Volume) GetTotal() *common.Decimal {
	if x != nil {
		return x.Total
	}
	return nil
}

type GetLimitsResponse_Limit struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Provider             *Provider              `protobuf:"bytes,10,opt,name=provider,proto3" json:"provider,omitempty"`
	CreditLeft           *common.Decimal        `protobuf:"bytes,20,opt,name=credit_left,json=creditLeft,proto3" json:"credit_left,omitempty"`
	CreditUsage          *common.Decimal        `protobuf:"bytes,30,opt,name=credit_usage,json=creditUsage,proto3" json:"credit_usage,omitempty"`
	PresettlementBalance *common.Decimal        `protobuf:"bytes,40,opt,name=presettlement_balance,json=presettlementBalance,proto3" json:"presettlement_balance,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetLimitsResponse_Limit) Reset() {
	*x = GetLimitsResponse_Limit{}
	mi := &file_tzero_v1_manage_dashboard_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLimitsResponse_Limit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLimitsResponse_Limit) ProtoMessage() {}

func (x *GetLimitsResponse_Limit) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_manage_dashboard_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLimitsResponse_Limit.ProtoReflect.Descriptor instead.
func (*GetLimitsResponse_Limit) Descriptor() ([]byte, []int) {
	return file_tzero_v1_manage_dashboard_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetLimitsResponse_Limit) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *GetLimitsResponse_Limit) GetCreditLeft() *common.Decimal {
	if x != nil {
		return x.CreditLeft
	}
	return nil
}

func (x *GetLimitsResponse_Limit) GetCreditUsage() *common.Decimal {
	if x != nil {
		return x.CreditUsage
	}
	return nil
}

func (x *GetLimitsResponse_Limit) GetPresettlementBalance() *common.Decimal {
	if x != nil {
		return x.PresettlementBalance
	}
	return nil
}

type GetPaymentsResponse_Payment struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Id            uint64                             `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
	Type          GetPaymentsResponse_Payment_Type   `protobuf:"varint,20,opt,name=type,proto3,enum=tzero.v1.manage.GetPaymentsResponse_Payment_Type" json:"type,omitempty"`
	Counterpart   *Provider                          `protobuf:"bytes,30,opt,name=counterpart,proto3" json:"counterpart,omitempty"`
	Status        GetPaymentsResponse_Payment_Status `protobuf:"varint,40,opt,name=status,proto3,enum=tzero.v1.manage.GetPaymentsResponse_Payment_Status" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp             `protobuf:"bytes,50,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	AcceptedAt    *timestamppb.Timestamp             `protobuf:"bytes,60,opt,name=accepted_at,json=acceptedAt,proto3,oneof" json:"accepted_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp             `protobuf:"bytes,70,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	UsdVolume     *common.Decimal                    `protobuf:"bytes,80,opt,name=usd_volume,json=usdVolume,proto3" json:"usd_volume,omitempty"` // TODO:
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentsResponse_Payment) Reset() {
	*x = GetPaymentsResponse_Payment{}
	mi := &file_tzero_v1_manage_dashboard_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentsResponse_Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentsResponse_Payment) ProtoMessage() {}

func (x *GetPaymentsResponse_Payment) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_manage_dashboard_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentsResponse_Payment.ProtoReflect.Descriptor instead.
func (*GetPaymentsResponse_Payment) Descriptor() ([]byte, []int) {
	return file_tzero_v1_manage_dashboard_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GetPaymentsResponse_Payment) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetPaymentsResponse_Payment) GetType() GetPaymentsResponse_Payment_Type {
	if x != nil {
		return x.Type
	}
	return GetPaymentsResponse_Payment_TYPE_UNSPECIFIED
}

func (x *GetPaymentsResponse_Payment) GetCounterpart() *Provider {
	if x != nil {
		return x.Counterpart
	}
	return nil
}

func (x *GetPaymentsResponse_Payment) GetStatus() GetPaymentsResponse_Payment_Status {
	if x != nil {
		return x.Status
	}
	return GetPaymentsResponse_Payment_STATUS_UNSPECIFIED
}

func (x *GetPaymentsResponse_Payment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetPaymentsResponse_Payment) GetAcceptedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AcceptedAt
	}
	return nil
}

func (x *GetPaymentsResponse_Payment) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *GetPaymentsResponse_Payment) GetUsdVolume() *common.Decimal {
	if x != nil {
		return x.UsdVolume
	}
	return nil
}

type GetSettlementsResponse_Settlement struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Id            uint64                                 `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
	Type          GetSettlementsResponse_Settlement_Type `protobuf:"varint,20,opt,name=type,proto3,enum=tzero.v1.manage.GetSettlementsResponse_Settlement_Type" json:"type,omitempty"`
	CounterpartId uint32                                 `protobuf:"varint,30,opt,name=counterpart_id,json=counterpartId,proto3" json:"counterpart_id,omitempty"`
	UsdVolume     *common.Decimal                        `protobuf:"bytes,40,opt,name=usd_volume,json=usdVolume,proto3" json:"usd_volume,omitempty"`
	CreatedAt     *timestamppb.Timestamp                 `protobuf:"bytes,50,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettlementsResponse_Settlement) Reset() {
	*x = GetSettlementsResponse_Settlement{}
	mi := &file_tzero_v1_manage_dashboard_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettlementsResponse_Settlement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettlementsResponse_Settlement) ProtoMessage() {}

func (x *GetSettlementsResponse_Settlement) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_manage_dashboard_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettlementsResponse_Settlement.ProtoReflect.Descriptor instead.
func (*GetSettlementsResponse_Settlement) Descriptor() ([]byte, []int) {
	return file_tzero_v1_manage_dashboard_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GetSettlementsResponse_Settlement) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetSettlementsResponse_Settlement) GetType() GetSettlementsResponse_Settlement_Type {
	if x != nil {
		return x.Type
	}
	return GetSettlementsResponse_Settlement_TYPE_UNSPECIFIED
}

func (x *GetSettlementsResponse_Settlement) GetCounterpartId() uint32 {
	if x != nil {
		return x.CounterpartId
	}
	return 0
}

func (x *GetSettlementsResponse_Settlement) GetUsdVolume() *common.Decimal {
	if x != nil {
		return x.UsdVolume
	}
	return nil
}

func (x *GetSettlementsResponse_Settlement) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_tzero_v1_manage_dashboard_proto protoreflect.FileDescriptor

const file_tzero_v1_manage_dashboard_proto_rawDesc = "" +
	"\n" +
	"\x1ftzero/v1/manage/dashboard.proto\x12\x0ftzero.v1.manage\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ctzero/v1/common/common.proto\"\x12\n" +
	"\x10GetVolumeRequest\"\xde\x02\n" +
	"\x11GetVolumeResponse\x12C\n" +
	"\avolumes\x18\n" +
	" \x03(\v2).tzero.v1.manage.GetVolumeResponse.VolumeR\avolumes\x12.\n" +
	"\x05total\x18\x14 \x01(\v2\x18.tzero.v1.common.DecimalR\x05total\x1a\xd3\x01\n" +
	"\x06Volume\x125\n" +
	"\bprovider\x18\n" +
	" \x01(\v2\x19.tzero.v1.manage.ProviderR\bprovider\x12/\n" +
	"\x06pay_in\x18\x14 \x01(\v2\x18.tzero.v1.common.DecimalR\x05payIn\x121\n" +
	"\apay_out\x18\x1e \x01(\v2\x18.tzero.v1.common.DecimalR\x06payOut\x12.\n" +
	"\x05total\x18( \x01(\v2\x18.tzero.v1.common.DecimalR\x05total\"\x12\n" +
	"\x10GetLimitsRequest\"\xdd\x02\n" +
	"\x11GetLimitsResponse\x12@\n" +
	"\x06limits\x18\n" +
	" \x03(\v2(.tzero.v1.manage.GetLimitsResponse.LimitR\x06limits\x1a\x85\x02\n" +
	"\x05Limit\x125\n" +
	"\bprovider\x18\n" +
	" \x01(\v2\x19.tzero.v1.manage.ProviderR\bprovider\x129\n" +
	"\vcredit_left\x18\x14 \x01(\v2\x18.tzero.v1.common.DecimalR\n" +
	"creditLeft\x12;\n" +
	"\fcredit_usage\x18\x1e \x01(\v2\x18.tzero.v1.common.DecimalR\vcreditUsage\x12M\n" +
	"\x15presettlement_balance\x18( \x01(\v2\x18.tzero.v1.common.DecimalR\x14presettlementBalance\"M\n" +
	"\x12GetPaymentsRequest\x12.\n" +
	"\x04page\x18\n" +
	" \x01(\v2\x15.tzero.v1.manage.PageH\x00R\x04page\x88\x01\x01B\a\n" +
	"\x05_page\"\xad\x06\n" +
	"\x13GetPaymentsResponse\x12H\n" +
	"\bpayments\x18\n" +
	" \x03(\v2,.tzero.v1.manage.GetPaymentsResponse.PaymentR\bpayments\x1a\xcb\x05\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\n" +
	" \x01(\x04R\x02id\x12E\n" +
	"\x04type\x18\x14 \x01(\x0e21.tzero.v1.manage.GetPaymentsResponse.Payment.TypeR\x04type\x12;\n" +
	"\vcounterpart\x18\x1e \x01(\v2\x19.tzero.v1.manage.ProviderR\vcounterpart\x12K\n" +
	"\x06status\x18( \x01(\x0e23.tzero.v1.manage.GetPaymentsResponse.Payment.StatusR\x06status\x129\n" +
	"\n" +
	"created_at\x182 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12@\n" +
	"\vaccepted_at\x18< \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"acceptedAt\x88\x01\x01\x12B\n" +
	"\fcompleted_at\x18F \x01(\v2\x1a.google.protobuf.TimestampH\x01R\vcompletedAt\x88\x01\x01\x127\n" +
	"\n" +
	"usd_volume\x18P \x01(\v2\x18.tzero.v1.common.DecimalR\tusdVolume\"C\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eTYPE_INITIATED\x10\n" +
	"\x12\x11\n" +
	"\rTYPE_PAID_OUT\x10\x14\"\x7f\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSTATUS_ACCEPTED\x10\n" +
	"\x12\x12\n" +
	"\x0eSTATUS_SUCCESS\x10\x14\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x1e\x12!\n" +
	"\x1dSTATUS_PENDING_PRE_SETTLEMENT\x10(B\x0e\n" +
	"\f_accepted_atB\x0f\n" +
	"\r_completed_at\"P\n" +
	"\x15GetSettlementsRequest\x12.\n" +
	"\x04page\x18\n" +
	" \x01(\v2\x15.tzero.v1.manage.PageH\x00R\x04page\x88\x01\x01B\a\n" +
	"\x05_page\"\xdf\x02\n" +
	"\x16GetSettlementsResponse\x1a\xc4\x02\n" +
	"\n" +
	"Settlement\x12\x0e\n" +
	"\x02id\x18\n" +
	" \x01(\x04R\x02id\x12K\n" +
	"\x04type\x18\x14 \x01(\x0e27.tzero.v1.manage.GetSettlementsResponse.Settlement.TypeR\x04type\x12%\n" +
	"\x0ecounterpart_id\x18\x1e \x01(\rR\rcounterpartId\x127\n" +
	"\n" +
	"usd_volume\x18( \x01(\v2\x18.tzero.v1.common.DecimalR\tusdVolume\x129\n" +
	"\n" +
	"created_at\x182 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\">\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tTYPE_SENT\x10\n" +
	"\x12\x11\n" +
	"\rTYPE_RECEIVED\x10\x14\".\n" +
	"\bProvider\x12\x0e\n" +
	"\x02id\x18\n" +
	" \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x14 \x01(\tR\x04name\"S\n" +
	"\x04Page\x12\x17\n" +
	"\x04page\x18\n" +
	" \x01(\rH\x00R\x04page\x88\x01\x01\x12 \n" +
	"\x04size\x18\x14 \x01(\rB\a\xbaH\x04\x1a\x02\x102H\x01R\x04size\x88\x01\x01B\a\n" +
	"\x05_pageB\a\n" +
	"\x05_size2\xf7\x02\n" +
	"\x10DashboardService\x12R\n" +
	"\tGetVolume\x12!.tzero.v1.manage.GetVolumeRequest\x1a\".tzero.v1.manage.GetVolumeResponse\x12R\n" +
	"\tGetLimits\x12!.tzero.v1.manage.GetLimitsRequest\x1a\".tzero.v1.manage.GetLimitsResponse\x12X\n" +
	"\vGetPayments\x12#.tzero.v1.manage.GetPaymentsRequest\x1a$.tzero.v1.manage.GetPaymentsResponse\x12a\n" +
	"\x0eGetSettlements\x12&.tzero.v1.manage.GetSettlementsRequest\x1a'.tzero.v1.manage.GetSettlementsResponseB\xbf\x01\n" +
	"\x13com.tzero.v1.manageB\x0eDashboardProtoP\x01Z:github.com/t-0-network/provider-sdk-go/api/tzero/v1/manage\xa2\x02\x03TVM\xaa\x02\x0fTzero.V1.Manage\xca\x02\x0fTzero\\V1\\Manage\xe2\x02\x1bTzero\\V1\\Manage\\GPBMetadata\xea\x02\x11Tzero::V1::Manageb\x06proto3"

var (
	file_tzero_v1_manage_dashboard_proto_rawDescOnce sync.Once
	file_tzero_v1_manage_dashboard_proto_rawDescData []byte
)

func file_tzero_v1_manage_dashboard_proto_rawDescGZIP() []byte {
	file_tzero_v1_manage_dashboard_proto_rawDescOnce.Do(func() {
		file_tzero_v1_manage_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tzero_v1_manage_dashboard_proto_rawDesc), len(file_tzero_v1_manage_dashboard_proto_rawDesc)))
	})
	return file_tzero_v1_manage_dashboard_proto_rawDescData
}

var file_tzero_v1_manage_dashboard_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_tzero_v1_manage_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_tzero_v1_manage_dashboard_proto_goTypes = []any{
	(GetPaymentsResponse_Payment_Type)(0),       // 0: tzero.v1.manage.GetPaymentsResponse.Payment.Type
	(GetPaymentsResponse_Payment_Status)(0),     // 1: tzero.v1.manage.GetPaymentsResponse.Payment.Status
	(GetSettlementsResponse_Settlement_Type)(0), // 2: tzero.v1.manage.GetSettlementsResponse.Settlement.Type
	(*GetVolumeRequest)(nil),                    // 3: tzero.v1.manage.GetVolumeRequest
	(*GetVolumeResponse)(nil),                   // 4: tzero.v1.manage.GetVolumeResponse
	(*GetLimitsRequest)(nil),                    // 5: tzero.v1.manage.GetLimitsRequest
	(*GetLimitsResponse)(nil),                   // 6: tzero.v1.manage.GetLimitsResponse
	(*GetPaymentsRequest)(nil),                  // 7: tzero.v1.manage.GetPaymentsRequest
	(*GetPaymentsResponse)(nil),                 // 8: tzero.v1.manage.GetPaymentsResponse
	(*GetSettlementsRequest)(nil),               // 9: tzero.v1.manage.GetSettlementsRequest
	(*GetSettlementsResponse)(nil),              // 10: tzero.v1.manage.GetSettlementsResponse
	(*Provider)(nil),                            // 11: tzero.v1.manage.Provider
	(*Page)(nil),                                // 12: tzero.v1.manage.Page
	(*GetVolumeResponse_Volume)(nil),            // 13: tzero.v1.manage.GetVolumeResponse.Volume
	(*GetLimitsResponse_Limit)(nil),             // 14: tzero.v1.manage.GetLimitsResponse.Limit
	(*GetPaymentsResponse_Payment)(nil),         // 15: tzero.v1.manage.GetPaymentsResponse.Payment
	(*GetSettlementsResponse_Settlement)(nil),   // 16: tzero.v1.manage.GetSettlementsResponse.Settlement
	(*common.Decimal)(nil),                      // 17: tzero.v1.common.Decimal
	(*timestamppb.Timestamp)(nil),               // 18: google.protobuf.Timestamp
}
var file_tzero_v1_manage_dashboard_proto_depIdxs = []int32{
	13, // 0: tzero.v1.manage.GetVolumeResponse.volumes:type_name -> tzero.v1.manage.GetVolumeResponse.Volume
	17, // 1: tzero.v1.manage.GetVolumeResponse.total:type_name -> tzero.v1.common.Decimal
	14, // 2: tzero.v1.manage.GetLimitsResponse.limits:type_name -> tzero.v1.manage.GetLimitsResponse.Limit
	12, // 3: tzero.v1.manage.GetPaymentsRequest.page:type_name -> tzero.v1.manage.Page
	15, // 4: tzero.v1.manage.GetPaymentsResponse.payments:type_name -> tzero.v1.manage.GetPaymentsResponse.Payment
	12, // 5: tzero.v1.manage.GetSettlementsRequest.page:type_name -> tzero.v1.manage.Page
	11, // 6: tzero.v1.manage.GetVolumeResponse.Volume.provider:type_name -> tzero.v1.manage.Provider
	17, // 7: tzero.v1.manage.GetVolumeResponse.Volume.pay_in:type_name -> tzero.v1.common.Decimal
	17, // 8: tzero.v1.manage.GetVolumeResponse.Volume.pay_out:type_name -> tzero.v1.common.Decimal
	17, // 9: tzero.v1.manage.GetVolumeResponse.Volume.total:type_name -> tzero.v1.common.Decimal
	11, // 10: tzero.v1.manage.GetLimitsResponse.Limit.provider:type_name -> tzero.v1.manage.Provider
	17, // 11: tzero.v1.manage.GetLimitsResponse.Limit.credit_left:type_name -> tzero.v1.common.Decimal
	17, // 12: tzero.v1.manage.GetLimitsResponse.Limit.credit_usage:type_name -> tzero.v1.common.Decimal
	17, // 13: tzero.v1.manage.GetLimitsResponse.Limit.presettlement_balance:type_name -> tzero.v1.common.Decimal
	0,  // 14: tzero.v1.manage.GetPaymentsResponse.Payment.type:type_name -> tzero.v1.manage.GetPaymentsResponse.Payment.Type
	11, // 15: tzero.v1.manage.GetPaymentsResponse.Payment.counterpart:type_name -> tzero.v1.manage.Provider
	1,  // 16: tzero.v1.manage.GetPaymentsResponse.Payment.status:type_name -> tzero.v1.manage.GetPaymentsResponse.Payment.Status
	18, // 17: tzero.v1.manage.GetPaymentsResponse.Payment.created_at:type_name -> google.protobuf.Timestamp
	18, // 18: tzero.v1.manage.GetPaymentsResponse.Payment.accepted_at:type_name -> google.protobuf.Timestamp
	18, // 19: tzero.v1.manage.GetPaymentsResponse.Payment.completed_at:type_name -> google.protobuf.Timestamp
	17, // 20: tzero.v1.manage.GetPaymentsResponse.Payment.usd_volume:type_name -> tzero.v1.common.Decimal
	2,  // 21: tzero.v1.manage.GetSettlementsResponse.Settlement.type:type_name -> tzero.v1.manage.GetSettlementsResponse.Settlement.Type
	17, // 22: tzero.v1.manage.GetSettlementsResponse.Settlement.usd_volume:type_name -> tzero.v1.common.Decimal
	18, // 23: tzero.v1.manage.GetSettlementsResponse.Settlement.created_at:type_name -> google.protobuf.Timestamp
	3,  // 24: tzero.v1.manage.DashboardService.GetVolume:input_type -> tzero.v1.manage.GetVolumeRequest
	5,  // 25: tzero.v1.manage.DashboardService.GetLimits:input_type -> tzero.v1.manage.GetLimitsRequest
	7,  // 26: tzero.v1.manage.DashboardService.GetPayments:input_type -> tzero.v1.manage.GetPaymentsRequest
	9,  // 27: tzero.v1.manage.DashboardService.GetSettlements:input_type -> tzero.v1.manage.GetSettlementsRequest
	4,  // 28: tzero.v1.manage.DashboardService.GetVolume:output_type -> tzero.v1.manage.GetVolumeResponse
	6,  // 29: tzero.v1.manage.DashboardService.GetLimits:output_type -> tzero.v1.manage.GetLimitsResponse
	8,  // 30: tzero.v1.manage.DashboardService.GetPayments:output_type -> tzero.v1.manage.GetPaymentsResponse
	10, // 31: tzero.v1.manage.DashboardService.GetSettlements:output_type -> tzero.v1.manage.GetSettlementsResponse
	28, // [28:32] is the sub-list for method output_type
	24, // [24:28] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_tzero_v1_manage_dashboard_proto_init() }
func file_tzero_v1_manage_dashboard_proto_init() {
	if File_tzero_v1_manage_dashboard_proto != nil {
		return
	}
	file_tzero_v1_manage_dashboard_proto_msgTypes[4].OneofWrappers = []any{}
	file_tzero_v1_manage_dashboard_proto_msgTypes[6].OneofWrappers = []any{}
	file_tzero_v1_manage_dashboard_proto_msgTypes[9].OneofWrappers = []any{}
	file_tzero_v1_manage_dashboard_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tzero_v1_manage_dashboard_proto_rawDesc), len(file_tzero_v1_manage_dashboard_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tzero_v1_manage_dashboard_proto_goTypes,
		DependencyIndexes: file_tzero_v1_manage_dashboard_proto_depIdxs,
		EnumInfos:         file_tzero_v1_manage_dashboard_proto_enumTypes,
		MessageInfos:      file_tzero_v1_manage_dashboard_proto_msgTypes,
	}.Build()
	File_tzero_v1_manage_dashboard_proto = out.File
	file_tzero_v1_manage_dashboard_proto_goTypes = nil
	file_tzero_v1_manage_dashboard_proto_depIdxs = nil
}
