// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: tzero/v1/payment_intent/network.proto

package payment_intentconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	payment_intent "github.com/t-0-network/provider-sdk-go/api/tzero/v1/payment_intent"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PaymentIntentServiceName is the fully-qualified name of the PaymentIntentService service.
	PaymentIntentServiceName = "tzero.v1.payment_intent.PaymentIntentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PaymentIntentServiceUpdateQuoteProcedure is the fully-qualified name of the
	// PaymentIntentService's UpdateQuote RPC.
	PaymentIntentServiceUpdateQuoteProcedure = "/tzero.v1.payment_intent.PaymentIntentService/UpdateQuote"
	// PaymentIntentServiceGetQuoteProcedure is the fully-qualified name of the PaymentIntentService's
	// GetQuote RPC.
	PaymentIntentServiceGetQuoteProcedure = "/tzero.v1.payment_intent.PaymentIntentService/GetQuote"
	// PaymentIntentServiceCreatePaymentIntentProcedure is the fully-qualified name of the
	// PaymentIntentService's CreatePaymentIntent RPC.
	PaymentIntentServiceCreatePaymentIntentProcedure = "/tzero.v1.payment_intent.PaymentIntentService/CreatePaymentIntent"
	// PaymentIntentServiceConfirmFundsReceivedProcedure is the fully-qualified name of the
	// PaymentIntentService's ConfirmFundsReceived RPC.
	PaymentIntentServiceConfirmFundsReceivedProcedure = "/tzero.v1.payment_intent.PaymentIntentService/ConfirmFundsReceived"
)

// PaymentIntentServiceClient is a client for the tzero.v1.payment_intent.PaymentIntentService
// service.
type PaymentIntentServiceClient interface {
	// *
	// Used by the provider to publish payment intent (pay-in) quotes into the network.
	// These quotes include tiered pricing bands and an expiration timestamp.
	UpdateQuote(context.Context, *connect.Request[payment_intent.UpdateQuoteRequest]) (*connect.Response[payment_intent.UpdateQuoteResponse], error)
	// *
	// GetQuote returns available quotes for a given currency and amount.
	//
	// Use this to check indicative rates before creating a payment intent.
	// The returned quotes show which providers can accept pay-ins and their current rates.
	//
	// Note: Quotes are indicative only. The actual rate used for settlement is determined
	// at the time of ConfirmFundsReceived.
	GetQuote(context.Context, *connect.Request[payment_intent.GetQuoteRequest]) (*connect.Response[payment_intent.GetQuoteResponse], error)
	// *
	// CreatePaymentIntent initiates a new payment intent.
	//
	// Called by the beneficiary provider (the one who will receive the settlement).
	// The network finds suitable pay-in providers, retrieves their payment details,
	// and returns available payment options to present to the end-user.
	//
	// The returned payment_intent_id must be stored by the beneficiary provider
	// to correlate with the PaymentIntentUpdate notification received later.
	//
	// Idempotency: Multiple calls with the same external_reference return the same payment_intent_id.
	CreatePaymentIntent(context.Context, *connect.Request[payment_intent.CreatePaymentIntentRequest]) (*connect.Response[payment_intent.CreatePaymentIntentResponse], error)
	// *
	// ConfirmFundsReceived confirms that the pay-in provider has received funds from the end-user.
	ConfirmFundsReceived(context.Context, *connect.Request[payment_intent.ConfirmFundsReceivedRequest]) (*connect.Response[payment_intent.ConfirmFundsReceivedResponse], error)
}

// NewPaymentIntentServiceClient constructs a client for the
// tzero.v1.payment_intent.PaymentIntentService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPaymentIntentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PaymentIntentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	paymentIntentServiceMethods := payment_intent.File_tzero_v1_payment_intent_network_proto.Services().ByName("PaymentIntentService").Methods()
	return &paymentIntentServiceClient{
		updateQuote: connect.NewClient[payment_intent.UpdateQuoteRequest, payment_intent.UpdateQuoteResponse](
			httpClient,
			baseURL+PaymentIntentServiceUpdateQuoteProcedure,
			connect.WithSchema(paymentIntentServiceMethods.ByName("UpdateQuote")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
		getQuote: connect.NewClient[payment_intent.GetQuoteRequest, payment_intent.GetQuoteResponse](
			httpClient,
			baseURL+PaymentIntentServiceGetQuoteProcedure,
			connect.WithSchema(paymentIntentServiceMethods.ByName("GetQuote")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
		createPaymentIntent: connect.NewClient[payment_intent.CreatePaymentIntentRequest, payment_intent.CreatePaymentIntentResponse](
			httpClient,
			baseURL+PaymentIntentServiceCreatePaymentIntentProcedure,
			connect.WithSchema(paymentIntentServiceMethods.ByName("CreatePaymentIntent")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
		confirmFundsReceived: connect.NewClient[payment_intent.ConfirmFundsReceivedRequest, payment_intent.ConfirmFundsReceivedResponse](
			httpClient,
			baseURL+PaymentIntentServiceConfirmFundsReceivedProcedure,
			connect.WithSchema(paymentIntentServiceMethods.ByName("ConfirmFundsReceived")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
	}
}

// paymentIntentServiceClient implements PaymentIntentServiceClient.
type paymentIntentServiceClient struct {
	updateQuote          *connect.Client[payment_intent.UpdateQuoteRequest, payment_intent.UpdateQuoteResponse]
	getQuote             *connect.Client[payment_intent.GetQuoteRequest, payment_intent.GetQuoteResponse]
	createPaymentIntent  *connect.Client[payment_intent.CreatePaymentIntentRequest, payment_intent.CreatePaymentIntentResponse]
	confirmFundsReceived *connect.Client[payment_intent.ConfirmFundsReceivedRequest, payment_intent.ConfirmFundsReceivedResponse]
}

// UpdateQuote calls tzero.v1.payment_intent.PaymentIntentService.UpdateQuote.
func (c *paymentIntentServiceClient) UpdateQuote(ctx context.Context, req *connect.Request[payment_intent.UpdateQuoteRequest]) (*connect.Response[payment_intent.UpdateQuoteResponse], error) {
	return c.updateQuote.CallUnary(ctx, req)
}

// GetQuote calls tzero.v1.payment_intent.PaymentIntentService.GetQuote.
func (c *paymentIntentServiceClient) GetQuote(ctx context.Context, req *connect.Request[payment_intent.GetQuoteRequest]) (*connect.Response[payment_intent.GetQuoteResponse], error) {
	return c.getQuote.CallUnary(ctx, req)
}

// CreatePaymentIntent calls tzero.v1.payment_intent.PaymentIntentService.CreatePaymentIntent.
func (c *paymentIntentServiceClient) CreatePaymentIntent(ctx context.Context, req *connect.Request[payment_intent.CreatePaymentIntentRequest]) (*connect.Response[payment_intent.CreatePaymentIntentResponse], error) {
	return c.createPaymentIntent.CallUnary(ctx, req)
}

// ConfirmFundsReceived calls tzero.v1.payment_intent.PaymentIntentService.ConfirmFundsReceived.
func (c *paymentIntentServiceClient) ConfirmFundsReceived(ctx context.Context, req *connect.Request[payment_intent.ConfirmFundsReceivedRequest]) (*connect.Response[payment_intent.ConfirmFundsReceivedResponse], error) {
	return c.confirmFundsReceived.CallUnary(ctx, req)
}

// PaymentIntentServiceHandler is an implementation of the
// tzero.v1.payment_intent.PaymentIntentService service.
type PaymentIntentServiceHandler interface {
	// *
	// Used by the provider to publish payment intent (pay-in) quotes into the network.
	// These quotes include tiered pricing bands and an expiration timestamp.
	UpdateQuote(context.Context, *connect.Request[payment_intent.UpdateQuoteRequest]) (*connect.Response[payment_intent.UpdateQuoteResponse], error)
	// *
	// GetQuote returns available quotes for a given currency and amount.
	//
	// Use this to check indicative rates before creating a payment intent.
	// The returned quotes show which providers can accept pay-ins and their current rates.
	//
	// Note: Quotes are indicative only. The actual rate used for settlement is determined
	// at the time of ConfirmFundsReceived.
	GetQuote(context.Context, *connect.Request[payment_intent.GetQuoteRequest]) (*connect.Response[payment_intent.GetQuoteResponse], error)
	// *
	// CreatePaymentIntent initiates a new payment intent.
	//
	// Called by the beneficiary provider (the one who will receive the settlement).
	// The network finds suitable pay-in providers, retrieves their payment details,
	// and returns available payment options to present to the end-user.
	//
	// The returned payment_intent_id must be stored by the beneficiary provider
	// to correlate with the PaymentIntentUpdate notification received later.
	//
	// Idempotency: Multiple calls with the same external_reference return the same payment_intent_id.
	CreatePaymentIntent(context.Context, *connect.Request[payment_intent.CreatePaymentIntentRequest]) (*connect.Response[payment_intent.CreatePaymentIntentResponse], error)
	// *
	// ConfirmFundsReceived confirms that the pay-in provider has received funds from the end-user.
	ConfirmFundsReceived(context.Context, *connect.Request[payment_intent.ConfirmFundsReceivedRequest]) (*connect.Response[payment_intent.ConfirmFundsReceivedResponse], error)
}

// NewPaymentIntentServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPaymentIntentServiceHandler(svc PaymentIntentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	paymentIntentServiceMethods := payment_intent.File_tzero_v1_payment_intent_network_proto.Services().ByName("PaymentIntentService").Methods()
	paymentIntentServiceUpdateQuoteHandler := connect.NewUnaryHandler(
		PaymentIntentServiceUpdateQuoteProcedure,
		svc.UpdateQuote,
		connect.WithSchema(paymentIntentServiceMethods.ByName("UpdateQuote")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	paymentIntentServiceGetQuoteHandler := connect.NewUnaryHandler(
		PaymentIntentServiceGetQuoteProcedure,
		svc.GetQuote,
		connect.WithSchema(paymentIntentServiceMethods.ByName("GetQuote")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	paymentIntentServiceCreatePaymentIntentHandler := connect.NewUnaryHandler(
		PaymentIntentServiceCreatePaymentIntentProcedure,
		svc.CreatePaymentIntent,
		connect.WithSchema(paymentIntentServiceMethods.ByName("CreatePaymentIntent")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	paymentIntentServiceConfirmFundsReceivedHandler := connect.NewUnaryHandler(
		PaymentIntentServiceConfirmFundsReceivedProcedure,
		svc.ConfirmFundsReceived,
		connect.WithSchema(paymentIntentServiceMethods.ByName("ConfirmFundsReceived")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	return "/tzero.v1.payment_intent.PaymentIntentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PaymentIntentServiceUpdateQuoteProcedure:
			paymentIntentServiceUpdateQuoteHandler.ServeHTTP(w, r)
		case PaymentIntentServiceGetQuoteProcedure:
			paymentIntentServiceGetQuoteHandler.ServeHTTP(w, r)
		case PaymentIntentServiceCreatePaymentIntentProcedure:
			paymentIntentServiceCreatePaymentIntentHandler.ServeHTTP(w, r)
		case PaymentIntentServiceConfirmFundsReceivedProcedure:
			paymentIntentServiceConfirmFundsReceivedHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPaymentIntentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPaymentIntentServiceHandler struct{}

func (UnimplementedPaymentIntentServiceHandler) UpdateQuote(context.Context, *connect.Request[payment_intent.UpdateQuoteRequest]) (*connect.Response[payment_intent.UpdateQuoteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tzero.v1.payment_intent.PaymentIntentService.UpdateQuote is not implemented"))
}

func (UnimplementedPaymentIntentServiceHandler) GetQuote(context.Context, *connect.Request[payment_intent.GetQuoteRequest]) (*connect.Response[payment_intent.GetQuoteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tzero.v1.payment_intent.PaymentIntentService.GetQuote is not implemented"))
}

func (UnimplementedPaymentIntentServiceHandler) CreatePaymentIntent(context.Context, *connect.Request[payment_intent.CreatePaymentIntentRequest]) (*connect.Response[payment_intent.CreatePaymentIntentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tzero.v1.payment_intent.PaymentIntentService.CreatePaymentIntent is not implemented"))
}

func (UnimplementedPaymentIntentServiceHandler) ConfirmFundsReceived(context.Context, *connect.Request[payment_intent.ConfirmFundsReceivedRequest]) (*connect.Response[payment_intent.ConfirmFundsReceivedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tzero.v1.payment_intent.PaymentIntentService.ConfirmFundsReceived is not implemented"))
}
