// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tzero/v1/common/payment_receipt.proto

package common

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentReceipt struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Details:
	//
	//	*PaymentReceipt_Sepa_
	//	*PaymentReceipt_Swift_
	//	*PaymentReceipt_Stablecoin_
	Details       isPaymentReceipt_Details `protobuf_oneof:"details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentReceipt) Reset() {
	*x = PaymentReceipt{}
	mi := &file_tzero_v1_common_payment_receipt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentReceipt) ProtoMessage() {}

func (x *PaymentReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_common_payment_receipt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentReceipt.ProtoReflect.Descriptor instead.
func (*PaymentReceipt) Descriptor() ([]byte, []int) {
	return file_tzero_v1_common_payment_receipt_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentReceipt) GetDetails() isPaymentReceipt_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *PaymentReceipt) GetSepa() *PaymentReceipt_Sepa {
	if x != nil {
		if x, ok := x.Details.(*PaymentReceipt_Sepa_); ok {
			return x.Sepa
		}
	}
	return nil
}

func (x *PaymentReceipt) GetSwift() *PaymentReceipt_Swift {
	if x != nil {
		if x, ok := x.Details.(*PaymentReceipt_Swift_); ok {
			return x.Swift
		}
	}
	return nil
}

func (x *PaymentReceipt) GetStablecoin() *PaymentReceipt_Stablecoin {
	if x != nil {
		if x, ok := x.Details.(*PaymentReceipt_Stablecoin_); ok {
			return x.Stablecoin
		}
	}
	return nil
}

type isPaymentReceipt_Details interface {
	isPaymentReceipt_Details()
}

type PaymentReceipt_Sepa_ struct {
	Sepa *PaymentReceipt_Sepa `protobuf:"bytes,10,opt,name=sepa,proto3,oneof"`
}

type PaymentReceipt_Swift_ struct {
	Swift *PaymentReceipt_Swift `protobuf:"bytes,30,opt,name=swift,proto3,oneof"`
}

type PaymentReceipt_Stablecoin_ struct {
	Stablecoin *PaymentReceipt_Stablecoin `protobuf:"bytes,40,opt,name=stablecoin,proto3,oneof"`
}

func (*PaymentReceipt_Sepa_) isPaymentReceipt_Details() {}

func (*PaymentReceipt_Swift_) isPaymentReceipt_Details() {}

func (*PaymentReceipt_Stablecoin_) isPaymentReceipt_Details() {}

type PaymentReceipt_Sepa struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	BankingTransactionReferenceId *string                `protobuf:"bytes,10,opt,name=banking_transaction_reference_id,json=bankingTransactionReferenceId,proto3,oneof" json:"banking_transaction_reference_id,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *PaymentReceipt_Sepa) Reset() {
	*x = PaymentReceipt_Sepa{}
	mi := &file_tzero_v1_common_payment_receipt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentReceipt_Sepa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentReceipt_Sepa) ProtoMessage() {}

func (x *PaymentReceipt_Sepa) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_common_payment_receipt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentReceipt_Sepa.ProtoReflect.Descriptor instead.
func (*PaymentReceipt_Sepa) Descriptor() ([]byte, []int) {
	return file_tzero_v1_common_payment_receipt_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PaymentReceipt_Sepa) GetBankingTransactionReferenceId() string {
	if x != nil && x.BankingTransactionReferenceId != nil {
		return *x.BankingTransactionReferenceId
	}
	return ""
}

type PaymentReceipt_Swift struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentReceipt_Swift) Reset() {
	*x = PaymentReceipt_Swift{}
	mi := &file_tzero_v1_common_payment_receipt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentReceipt_Swift) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentReceipt_Swift) ProtoMessage() {}

func (x *PaymentReceipt_Swift) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_common_payment_receipt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentReceipt_Swift.ProtoReflect.Descriptor instead.
func (*PaymentReceipt_Swift) Descriptor() ([]byte, []int) {
	return file_tzero_v1_common_payment_receipt_proto_rawDescGZIP(), []int{0, 1}
}

type PaymentReceipt_Stablecoin struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionHash string                 `protobuf:"bytes,10,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"` // on-chain hex encoded transaction hash
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PaymentReceipt_Stablecoin) Reset() {
	*x = PaymentReceipt_Stablecoin{}
	mi := &file_tzero_v1_common_payment_receipt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentReceipt_Stablecoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentReceipt_Stablecoin) ProtoMessage() {}

func (x *PaymentReceipt_Stablecoin) ProtoReflect() protoreflect.Message {
	mi := &file_tzero_v1_common_payment_receipt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentReceipt_Stablecoin.ProtoReflect.Descriptor instead.
func (*PaymentReceipt_Stablecoin) Descriptor() ([]byte, []int) {
	return file_tzero_v1_common_payment_receipt_proto_rawDescGZIP(), []int{0, 2}
}

func (x *PaymentReceipt_Stablecoin) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

var File_tzero_v1_common_payment_receipt_proto protoreflect.FileDescriptor

const file_tzero_v1_common_payment_receipt_proto_rawDesc = "" +
	"\n" +
	"%tzero/v1/common/payment_receipt.proto\x12\x0ftzero.v1.common\x1a\x1bbuf/validate/validate.proto\"\xd7\x03\n" +
	"\x0ePaymentReceipt\x12:\n" +
	"\x04sepa\x18\n" +
	" \x01(\v2$.tzero.v1.common.PaymentReceipt.SepaH\x00R\x04sepa\x12=\n" +
	"\x05swift\x18\x1e \x01(\v2%.tzero.v1.common.PaymentReceipt.SwiftH\x00R\x05swift\x12L\n" +
	"\n" +
	"stablecoin\x18( \x01(\v2*.tzero.v1.common.PaymentReceipt.StablecoinH\x00R\n" +
	"stablecoin\x1a\x84\x01\n" +
	"\x04Sepa\x12W\n" +
	" banking_transaction_reference_id\x18\n" +
	" \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18#H\x00R\x1dbankingTransactionReferenceId\x88\x01\x01B#\n" +
	"!_banking_transaction_reference_id\x1a\a\n" +
	"\x05Swift\x1aZ\n" +
	"\n" +
	"Stablecoin\x12L\n" +
	"\x10transaction_hash\x18\n" +
	" \x01(\tB!\xbaH\x1er\x1c\x10@\x18B2\x16^(0x)?[a-fA-F0-9]{64}$R\x0ftransactionHashB\x10\n" +
	"\adetails\x12\x05\xbaH\x02\b\x01B\xc4\x01\n" +
	"\x13com.tzero.v1.commonB\x13PaymentReceiptProtoP\x01Z:github.com/t-0-network/provider-sdk-go/api/tzero/v1/common\xa2\x02\x03TVC\xaa\x02\x0fTzero.V1.Common\xca\x02\x0fTzero\\V1\\Common\xe2\x02\x1bTzero\\V1\\Common\\GPBMetadata\xea\x02\x11Tzero::V1::Commonb\x06proto3"

var (
	file_tzero_v1_common_payment_receipt_proto_rawDescOnce sync.Once
	file_tzero_v1_common_payment_receipt_proto_rawDescData []byte
)

func file_tzero_v1_common_payment_receipt_proto_rawDescGZIP() []byte {
	file_tzero_v1_common_payment_receipt_proto_rawDescOnce.Do(func() {
		file_tzero_v1_common_payment_receipt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tzero_v1_common_payment_receipt_proto_rawDesc), len(file_tzero_v1_common_payment_receipt_proto_rawDesc)))
	})
	return file_tzero_v1_common_payment_receipt_proto_rawDescData
}

var file_tzero_v1_common_payment_receipt_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tzero_v1_common_payment_receipt_proto_goTypes = []any{
	(*PaymentReceipt)(nil),            // 0: tzero.v1.common.PaymentReceipt
	(*PaymentReceipt_Sepa)(nil),       // 1: tzero.v1.common.PaymentReceipt.Sepa
	(*PaymentReceipt_Swift)(nil),      // 2: tzero.v1.common.PaymentReceipt.Swift
	(*PaymentReceipt_Stablecoin)(nil), // 3: tzero.v1.common.PaymentReceipt.Stablecoin
}
var file_tzero_v1_common_payment_receipt_proto_depIdxs = []int32{
	1, // 0: tzero.v1.common.PaymentReceipt.sepa:type_name -> tzero.v1.common.PaymentReceipt.Sepa
	2, // 1: tzero.v1.common.PaymentReceipt.swift:type_name -> tzero.v1.common.PaymentReceipt.Swift
	3, // 2: tzero.v1.common.PaymentReceipt.stablecoin:type_name -> tzero.v1.common.PaymentReceipt.Stablecoin
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_tzero_v1_common_payment_receipt_proto_init() }
func file_tzero_v1_common_payment_receipt_proto_init() {
	if File_tzero_v1_common_payment_receipt_proto != nil {
		return
	}
	file_tzero_v1_common_payment_receipt_proto_msgTypes[0].OneofWrappers = []any{
		(*PaymentReceipt_Sepa_)(nil),
		(*PaymentReceipt_Swift_)(nil),
		(*PaymentReceipt_Stablecoin_)(nil),
	}
	file_tzero_v1_common_payment_receipt_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tzero_v1_common_payment_receipt_proto_rawDesc), len(file_tzero_v1_common_payment_receipt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tzero_v1_common_payment_receipt_proto_goTypes,
		DependencyIndexes: file_tzero_v1_common_payment_receipt_proto_depIdxs,
		MessageInfos:      file_tzero_v1_common_payment_receipt_proto_msgTypes,
	}.Build()
	File_tzero_v1_common_payment_receipt_proto = out.File
	file_tzero_v1_common_payment_receipt_proto_goTypes = nil
	file_tzero_v1_common_payment_receipt_proto_depIdxs = nil
}
