name: Generate Clients

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "proto/**"

jobs:
  test:
    runs-on: ubuntu-latest

    # Trigger only if the PR is opened or synchronized by T-0 CI APP (sync proto files)
    if: github.event.pull_request.user.login == 't-0-ci[bot]'

    steps:
      - name: Generate GitHub APP Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.CI_APP_ID }}
          private-key: ${{ secrets.CI_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: provider-sdk-go

      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
          cache-dependency-path: ./tools/go.sum

      - name: Generate Clients
        run: |
          go generate gen.go

      - name: Commit generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-generate GRPC clients"
          file_pattern: "api/**"
