name: test

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Validate Go module state
        run: |
          go mod tidy
          git diff --exit-code || (echo "go.mod diff found, please run 'go mod tidy'" && false)

      - name: Run Tests
        run: |
          go test -v ./...
